/* Map of the Caravaggios of the world.
   Consumes data/caravaggio.geojson (generated by ../scripts/build.py).
   Each feature = ONE work at its CURRENT location. Features are grouped by place:
   one pin per museum/church/collection, with the number of works held there. */

const KIND_LABEL = { museum: "Museum", church: "Church", private: "Private collection" };
const STATUS_LABEL = { lost: "lost", stolen: "stolen", destroyed: "destroyed" };
const ATTR_ACCEPTED = new Set(["certain", "generally accepted"]);
const GONE = new Set(["lost", "stolen", "destroyed"]);
const WIKI_LANGS = ["es", "en", "it"];

// Most works are in Europe; open there. The ~12 in the Americas are one zoom-out away.
const map = L.map("map", { zoomControl: true, worldCopyJump: true }).setView([43, 9], 5);
L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png", {
  maxZoom: 19, attribution: "© OpenStreetMap",
}).addTo(map);
requestAnimationFrame(() => map.invalidateSize());
window.addEventListener("resize", () => map.invalidateSize());

// clustering: overlapping venues (e.g. all of Rome) merge at low zoom into one badge
// showing the TOTAL number of works, and split apart as you zoom in.
const cluster = L.markerClusterGroup({
  maxClusterRadius: 44,
  showCoverageOnHover: false,
  spiderfyOnMaxZoom: true,
  iconCreateFunction(c) {
    const works = c.getAllChildMarkers().reduce((a, m) => a + (m.options.works || 1), 0);
    const size = works >= 25 ? 48 : works >= 10 ? 40 : 32;
    return L.divIcon({
      html: `<div class="cl" style="width:${size}px;height:${size}px;line-height:${size - 4}px">${works}</div>`,
      className: "", iconSize: [size, size],
    });
  },
}).addTo(map);

const legend = L.control({ position: "bottomleft" });
legend.onAdd = () => {
  const d = L.DomUtil.create("div", "legend");
  d.innerHTML =
    `<div class="row"><span class="k museum"></span>Museum` +
    ` <span class="k church"></span>Church` +
    ` <span class="k private"></span>Private</div>` +
    `<div class="row"><span class="k lost"></span>Lost / stolen` +
    ` <span class="k ring"></span>Disputed attribution</div>`;
  return d;
};
legend.addTo(map);

let allFeatures = [];   // raw point features from the geojson
const places = [];   // {marker, kind, feats, lat, lon, shown}
const works = [];    // {p (properties), lat, lon, marker} — one per painting, for the side panel
let panelVis = [];   // works currently listed in the panel
const state = { mode: "current", museum: true, church: true, private: true, onlyAccepted: false,
                yearMin: -Infinity, yearMax: Infinity };

function yearNum(p) {
  const m = (p.year || "").match(/1[5-9]\d{2}|20\d{2}/);
  return m ? +m[0] : null;
}
function inYear(p) {
  const y = yearNum(p);                       // unknown-date works stay visible
  return y == null || (y >= state.yearMin && y <= state.yearMax);
}
function passesAll(p) {
  const kindOk = state.mode === "painted" ? true : state[p.kind || "museum"];   // no venue type on map 2
  return kindOk && (!state.onlyAccepted || ATTR_ACCEPTED.has(p.attribution)) && inYear(p);
}
// active coordinate per map: current location, or where it was painted (map 2)
function activeCoord(f) {
  if (state.mode === "painted") {
    const p = f.properties;
    return (p.creation_lat != null && p.creation_lon != null) ? [p.creation_lon, p.creation_lat] : null;
  }
  return f.geometry.coordinates;
}

function esc(s) {
  return String(s).replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
}

// colour = location type; red = lost/stolen/destroyed; dashed ring = holds a disputed work
function pinIcon(kind, n, { lost = false, disputed = false } = {}) {
  const cls = lost ? "lost" : kind;
  return L.divIcon({
    className: "",
    html: `<div class="pin ${cls}${disputed ? " disp" : ""}">${n}</div>`,
    iconSize: [26, 26], iconAnchor: [13, 13], popupAnchor: [0, -14],
  });
}

// "Wikipedia: ES EN IT · Wikidata" — only the languages that actually have an article.
function linksRow(p) {
  const wp = WIKI_LANGS.filter(l => p["wikipedia_" + l]).map(l =>
    `<a class="tag" href="${esc(p["wikipedia_" + l])}" target="_blank" rel="noopener">${l.toUpperCase()}</a>`);
  const parts = [];
  if (wp.length) parts.push(`<span class="lbl">Wikipedia</span>${wp.join("")}`);
  if (p.wikidata) parts.push(`<a class="tag wd" href="${esc(p.wikidata)}" target="_blank" rel="noopener">Wikidata</a>`);
  return parts.join(" ");
}

// visible provenance line for overridden fields (skip those given in `skip`).
// Public-facing wording only — never names the internal editor.
function provLine(p, skip = []) {
  if (!p._overrides) return "";
  const rows = Object.entries(p._overrides)
    .filter(([field]) => !skip.includes(field))
    .map(([field, o]) => {
      const src = o.source ? ` · ${esc(o.source)}` : "";
      return `<div class="prov"${o.note ? ` title="${esc(o.note)}"` : ""}>` +
        `✎ ${esc(field)} · post-processed${src}</div>`;
    });
  return rows.join("");
}

// Place record: header (museum · city · country) + one row per work with a thumbnail.
const HEAD_SKIP_CURRENT = ["attribution", "title", "year", "genre", "medium", "dimensions", "image", "creation", "status"];
const HEAD_SKIP_PAINTED = ["attribution", "title", "year", "genre", "medium", "dimensions", "image", "city", "country", "location", "kind", "status"];
const WORK_SKIP = ["city", "country", "location", "kind", "creation"];

function placePopup(feats) {
  const p0 = feats[0].properties;
  const painted = state.mode === "painted";
  const n = feats.length;
  let head;
  if (painted) {
    head = `<div class="hd"><div class="nm">${esc(p0.creation_place || "Unknown")}</div>` +
      `<div class="meta">painted here · ${n} work${n > 1 ? "s" : ""}</div>` +
      `${provLine(p0, HEAD_SKIP_PAINTED)}</div>`;
  } else {
    const kindTxt = KIND_LABEL[p0.kind] || "";
    const where = [p0.city, p0.country].filter(Boolean).join(", ");
    head = `<div class="hd"><div class="nm">${esc(p0.location || "Location")}</div>` +
      `<div class="meta">${esc(where)}${kindTxt ? ` · ${kindTxt}` : ""} · ${n} work${n > 1 ? "s" : ""}</div>` +
      `${provLine(p0, HEAD_SKIP_CURRENT)}</div>`;
  }

  const items = feats.map(f => {
    const p = f.properties;
    const yr = p.year ? ` <span class="yr">${esc(p.year)}</span>` : "";
    const att = p.attribution && !ATTR_ACCEPTED.has(p.attribution)
      ? ` <span class="tag att">${esc(p.attribution)}</span>` : "";
    const st = p.status && GONE.has(p.status)
      ? ` <span class="tag gone">${esc(STATUS_LABEL[p.status] || p.status)}</span>` : "";
    const factBits = [p.medium, p.dimensions];
    if (painted && p.location) factBits.push(`now in ${p.location}${p.city ? `, ${p.city}` : ""}`);
    const facts = factBits.filter(Boolean).map(esc).join(" · ");
    const factsRow = facts ? `<div class="fx">${facts}</div>` : "";
    const desc = p.summary ? `<div class="ds">${esc(p.summary)}</div>` : "";
    const cap = `${p.title || ""}${p.year ? ` (${p.year})` : ""} — ${p0.location || ""}`;
    const thumb = p.image
      ? `<img class="th" src="${esc(p.image)}" data-full="${esc(fullImage(p.image))}" data-cap="${esc(cap)}" alt="" loading="lazy">`
      : `<span class="th ph"></span>`;
    return `<li>${thumb}<div class="wk">` +
      `<div class="wt">${esc(p.title || "Untitled")}${yr}${att}${st}</div>` +
      `${factsRow}${desc}<div class="lk">${linksRow(p)}</div>` +
      `${provLine(p, WORK_SKIP)}</div></li>`;
  }).join("");

  return `<div class="card">${head}<ul class="works">${items}</ul></div>`;
}

function refresh() {
  let workCount = 0, shownPlaces = 0;
  const countries = new Set();
  for (const pl of places) {
    const vis = pl.feats.filter(f => passesAll(f.properties));   // works here passing every filter
    if (vis.length) {
      const painted = state.mode === "painted";
      const lost = !painted && vis.some(f => GONE.has(f.properties.status));
      const disputed = vis.some(f => !ATTR_ACCEPTED.has(f.properties.attribution));
      pl.marker.options.works = vis.length;
      pl.marker.setIcon(pinIcon(painted ? "painted" : pl.kind, vis.length, { lost, disputed }));
      pl.marker.setPopupContent(placePopup(vis));
      if (!pl.shown) { cluster.addLayer(pl.marker); pl.shown = true; }
      shownPlaces++; workCount += vis.length;
      if (vis[0].properties.country) countries.add(vis[0].properties.country);
    } else if (pl.shown) { cluster.removeLayer(pl.marker); pl.shown = false; }
  }
  cluster.refreshClusters();
  document.getElementById("stats").textContent =
    `${workCount} works · ${shownPlaces} locations · ${countries.size} countries`;
  renderPanel();
}

// group features by place (key = rounded coordinates)
function keyOf(f) {
  const [lon, lat] = f.geometry.coordinates;
  return `${lat.toFixed(5)},${lon.toFixed(5)}`;
}

// (re)build markers for the current mode: group features by their active coordinate
function buildMarkers() {
  cluster.clearLayers();
  places.length = 0; works.length = 0;
  const byPlace = new Map();
  for (const f of allFeatures) {
    const c = activeCoord(f);
    if (!c) continue;                       // e.g. undated work has no creation place
    const k = `${c[1].toFixed(5)},${c[0].toFixed(5)}`;
    if (!byPlace.has(k)) byPlace.set(k, []);
    byPlace.get(k).push(f);
  }
  for (const feats of byPlace.values()) {
    const [lon, lat] = activeCoord(feats[0]);
    const kind = feats[0].properties.kind || "museum";
    const marker = L.marker([lat, lon], { works: feats.length })
      .bindPopup("", { maxWidth: 320, minWidth: 240 });
    places.push({ marker, kind, feats, lat, lon, shown: false });
    for (const f of feats) works.push({ p: f.properties, lat, lon, marker });
  }
  refresh();
}

fetch("caravaggio/data/caravaggio.geojson")
  .then(r => r.json())
  .then(gj => {
    allFeatures = (gj.features || []).filter(f => f.geometry && f.geometry.type === "Point");
    const yrs = allFeatures.map(f => yearNum(f.properties)).filter(v => v != null);
    buildTimeline(Math.min(...yrs), Math.max(...yrs));   // sets state.yearMin/Max
    buildMarkers();
    map.on("moveend", renderPanel);
  })
  .catch(err => {
    console.error("Could not load caravaggio.geojson:", err);
    document.getElementById("stats").textContent = "no data yet — generate caravaggio.geojson";
  });

// filters
document.querySelectorAll('.filters input[data-kind]').forEach(cb => {
  cb.addEventListener("change", () => { state[cb.dataset.kind] = cb.checked; refresh(); });
});
document.getElementById("only-accepted").addEventListener("change", e => {
  state.onlyAccepted = e.target.checked; refresh();
});

// ── map mode: "where they are today" (venues) vs "where they were painted" (cities) ──
document.querySelectorAll(".mode-btn").forEach(btn => {
  btn.addEventListener("click", () => {
    if (state.mode === btn.dataset.mode) return;
    state.mode = btn.dataset.mode;
    document.querySelectorAll(".mode-btn").forEach(b => b.classList.toggle("active", b === btn));
    document.body.classList.toggle("mode-painted", state.mode === "painted");
    if (nearestLine) { map.removeLayer(nearestLine); nearestLine = null; }
    buildMarkers();   // regroup by the active coordinate + refresh
  });
});

// ── time slider: filter the map + panel by year of creation (dual-handle range) ──
function buildTimeline(min, max) {
  const lo = document.getElementById("tl-min");
  const hi = document.getElementById("tl-max");
  const label = document.getElementById("tl-label");
  const fill = document.getElementById("tl-fill");
  lo.min = hi.min = min; lo.max = hi.max = max;
  lo.value = min; hi.value = max;
  state.yearMin = min; state.yearMax = max;

  const paint = () => {
    const span = max - min || 1;
    const a = (state.yearMin - min) / span * 100;
    const b = (state.yearMax - min) / span * 100;
    fill.style.left = a + "%"; fill.style.right = (100 - b) + "%";
    label.textContent = state.yearMin === state.yearMax ? `${state.yearMin}` : `${state.yearMin}–${state.yearMax}`;
  };
  const update = () => {
    let a = +lo.value, b = +hi.value;
    if (a > b) { if (document.activeElement === lo) { b = a; hi.value = b; } else { a = b; lo.value = a; } }
    state.yearMin = a; state.yearMax = b;
    paint(); refresh();
  };
  lo.addEventListener("input", update);
  hi.addEventListener("input", update);
  paint();
}

// ── side panel: the works currently within the map viewport, grouped by venue ──
function renderPanel() {
  const b = map.getBounds();
  const vis = works.filter(w => passesAll(w.p) && b.contains([w.lat, w.lon]));

  // group by the active place (venue on map 1, creation city on map 2)
  const painted = state.mode === "painted";
  const groups = new Map();
  for (const w of vis) {
    const k = `${w.lat.toFixed(5)},${w.lon.toFixed(5)}`;
    if (!groups.has(k)) groups.set(k, {
      location: painted ? (w.p.creation_place || "Unknown") : (w.p.location || "Location"),
      city: painted ? "" : (w.p.city || ""), items: [],
    });
    groups.get(k).items.push(w);
  }
  const ordered = [...groups.values()].sort((a, z) =>
    (a.city || "zzz").localeCompare(z.city || "zzz") || a.location.localeCompare(z.location));

  document.getElementById("panel-head").textContent =
    `${vis.length} work${vis.length === 1 ? "" : "s"} in view`;

  const ul = document.getElementById("worklist");
  if (!vis.length) {
    ul.innerHTML = `<li class="empty">Pan or zoom the map — the works in view are listed here.</li>`;
    panelVis = [];
    return;
  }
  panelVis = [];
  let html = "";
  for (const g of ordered) {
    g.items.sort((a, z) => (yearNum(a.p) || 9999) - (yearNum(z.p) || 9999));
    html += `<li class="grp"><span>${esc(g.location)}${g.city ? ` · ${esc(g.city)}` : ""}</span>` +
      `<span class="n">${g.items.length}</span></li>`;
    for (const w of g.items) {
      const i = panelVis.length; panelVis.push(w);
      const p = w.p;
      const cap = `${p.title || ""}${p.year ? ` (${p.year})` : ""} — ${p.location || ""}`;
      const thumb = p.image
        ? `<img class="th" src="${esc(p.image)}" data-full="${esc(fullImage(p.image))}" data-cap="${esc(cap)}" alt="">`
        : `<span class="th"></span>`;
      html += `<li data-i="${i}">${thumb}<div>` +
        `<div class="wt">${esc(p.title || "Untitled")}${p.year ? ` <span class="sub">${esc(p.year)}</span>` : ""}</div>` +
        (p.medium ? `<div class="sub">${esc(p.medium)}</div>` : "") + `</div></li>`;
    }
  }
  ul.innerHTML = html;
}

document.getElementById("worklist").addEventListener("click", e => {
  if (e.target.closest("img.th")) return;          // thumbnail → lightbox (handled below)
  const li = e.target.closest("li[data-i]");
  if (!li) return;
  const w = panelVis[+li.dataset.i];
  if (!w) return;
  map.setView([w.lat, w.lon], Math.max(map.getZoom(), 13));
  cluster.zoomToShowLayer(w.marker, () => w.marker.openPopup());
});

// ── lightbox: the painting at full size ──
function fullImage(thumbUrl) {
  if (!thumbUrl) return "";
  return /width=\d+/.test(thumbUrl) ? thumbUrl.replace(/width=\d+/, "width=1600") : thumbUrl;
}
const lb = document.getElementById("lightbox");
function openLightbox(url, cap) {
  document.getElementById("lb-img").src = url;
  document.getElementById("lb-cap").textContent = cap || "";
  lb.hidden = false;
}
function closeLightbox() { lb.hidden = true; document.getElementById("lb-img").src = ""; }
document.getElementById("lb-close").addEventListener("click", closeLightbox);
lb.addEventListener("click", e => { if (e.target === lb) closeLightbox(); });
document.addEventListener("keydown", e => { if (e.key === "Escape") closeLightbox(); });
document.addEventListener("click", e => {
  const img = e.target.closest("img.th");
  if (img && img.dataset.full) openLightbox(img.dataset.full, img.dataset.cap);
});

// ── geolocation: your nearest Caravaggio ──
function haversine(lat1, lon1, lat2, lon2) {
  const R = 6371, r = x => x * Math.PI / 180;
  const dLat = r(lat2 - lat1), dLon = r(lon2 - lon1);
  const s = Math.sin(dLat / 2) ** 2 + Math.cos(r(lat1)) * Math.cos(r(lat2)) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(s));
}
let userMarker = null, nearestLine = null;
function showBanner(html) {
  let el = document.getElementById("banner");
  if (!el) { el = document.createElement("div"); el.id = "banner"; document.body.appendChild(el); }
  el.innerHTML = `${html} <button id="banner-x" aria-label="Dismiss">✕</button>`;
  el.hidden = false;
  document.getElementById("banner-x").onclick = () => { el.hidden = true; };
}
document.getElementById("locate").addEventListener("click", () => {
  const btn = document.getElementById("locate");
  if (!navigator.geolocation) { showBanner("Geolocation is not available in this browser."); return; }
  btn.textContent = "📍 Locating…"; btn.disabled = true;
  navigator.geolocation.getCurrentPosition(pos => {
    btn.textContent = "📍 Nearest to me"; btn.disabled = false;
    const { latitude: lat, longitude: lon } = pos.coords;
    if (userMarker) map.removeLayer(userMarker);
    userMarker = L.marker([lat, lon], {
      icon: L.divIcon({ className: "", html: `<div class="me"></div>`, iconSize: [16, 16], iconAnchor: [8, 8] }),
      zIndexOffset: 1000,
    }).addTo(map).bindPopup("You are here");
    let best = null, bd = Infinity;
    for (const w of works) {
      if (!passesAll(w.p)) continue;
      const d = haversine(lat, lon, w.lat, w.lon);
      if (d < bd) { bd = d; best = w; }
    }
    if (!best) { showBanner("No works match the current filters."); return; }
    const km = bd < 1 ? `${Math.round(bd * 1000)} m` : `${bd < 10 ? bd.toFixed(1) : Math.round(bd)} km`;
    if (nearestLine) map.removeLayer(nearestLine);
    nearestLine = L.polyline([[lat, lon], [best.lat, best.lon]],
      { color: "#1a73e8", weight: 2, dashArray: "5,7", opacity: .8 }).addTo(map);
    map.fitBounds([[lat, lon], [best.lat, best.lon]], { padding: [70, 70], maxZoom: 12 });
    cluster.zoomToShowLayer(best.marker, () => best.marker.openPopup());
    showBanner(`Your nearest Caravaggio: <b>${esc(best.p.title || "Untitled")}</b> — ` +
      `${esc([best.p.location, best.p.city].filter(Boolean).join(", "))} · <b>${km}</b> away`);
  }, err => {
    btn.textContent = "📍 Nearest to me"; btn.disabled = false;
    showBanner("Could not get your location: " + esc(err.message));
  }, { enableHighAccuracy: false, timeout: 10000, maximumAge: 60000 });
});
