/* Map of the Caravaggios of the world.
   Consumes data/caravaggio.geojson (generated by ../scripts/build.py).
   Each feature = ONE work at its CURRENT location. Features are grouped by place:
   one pin per museum/church/collection, with the number of works held there. */

const KIND_LABEL = { museum: "Museum", church: "Church", private: "Private collection" };
const ATTR_ACCEPTED = new Set(["certain", "generally accepted"]);
const WIKI_LANGS = ["es", "en", "it"];

// Most works are in Europe; open there. The ~12 in the Americas are one zoom-out away.
const map = L.map("map", { zoomControl: true, worldCopyJump: true }).setView([43, 9], 5);
L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png", {
  maxZoom: 19, attribution: "© OpenStreetMap",
}).addTo(map);
requestAnimationFrame(() => map.invalidateSize());
window.addEventListener("resize", () => map.invalidateSize());

const group = L.layerGroup().addTo(map);
const places = [];   // {marker, kind, count, country, hasAccepted, latlng}
const state = { museum: true, church: true, private: true, onlyAccepted: false };

function esc(s) {
  return String(s).replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
}

function pinIcon(kind, n) {
  return L.divIcon({
    className: "",
    html: `<div class="pin ${kind}">${n}</div>`,
    iconSize: [26, 26], iconAnchor: [13, 13], popupAnchor: [0, -14],
  });
}

function wikiLinks(p) {
  const links = WIKI_LANGS
    .filter(l => p["wikipedia_" + l])
    .map(l => `<a class="tag" href="${esc(p["wikipedia_" + l])}" target="_blank" rel="noopener">${l.toUpperCase()}</a>`);
  if (p.wikidata) links.push(`<a class="tag wd" href="${esc(p.wikidata)}" target="_blank" rel="noopener">Wikidata</a>`);
  return links.join("");
}

// Place record: header (museum · city · country) + one row per work with a thumbnail.
function placePopup(feats) {
  const p0 = feats[0].properties;
  const kindTxt = KIND_LABEL[p0.kind] || "";
  const where = [p0.city, p0.country].filter(Boolean).join(", ");
  const head =
    `<div class="hd"><div class="nm">${esc(p0.location || "Location")}</div>` +
    `<div class="meta">${esc(where)}${kindTxt ? ` · ${kindTxt}` : ""} · ` +
    `${feats.length} work${feats.length > 1 ? "s" : ""}</div></div>`;

  const items = feats.map(f => {
    const p = f.properties;
    const yr = p.year ? ` <span class="yr">${esc(p.year)}</span>` : "";
    const att = p.attribution && !ATTR_ACCEPTED.has(p.attribution)
      ? ` <span class="tag att">${esc(p.attribution)}</span>` : "";
    const thumb = p.image
      ? `<img class="th" src="${esc(p.image)}" alt="" loading="lazy">`
      : `<span class="th ph"></span>`;
    return `<li>${thumb}<div class="wk">` +
      `<div class="wt">${esc(p.title || "Untitled")}${yr}${att}</div>` +
      `<div class="lk">${wikiLinks(p)}</div></div></li>`;
  }).join("");

  return `<div class="card">${head}<ul class="works">${items}</ul></div>`;
}

function refresh() {
  for (const pl of places) {
    const kindOn = state[pl.kind];
    const attrOn = !state.onlyAccepted || pl.hasAccepted;
    if (kindOn && attrOn) pl.marker.addTo(group);
    else group.removeLayer(pl.marker);
  }
  const shown = places.filter(pl => map.hasLayer(pl.marker));
  const works = shown.reduce((a, pl) => a + pl.count, 0);
  const countries = new Set(shown.map(pl => pl.country).filter(Boolean)).size;
  document.getElementById("stats").textContent =
    `${works} works · ${shown.length} locations · ${countries} countries`;
}

// group features by place (key = rounded coordinates)
function keyOf(f) {
  const [lon, lat] = f.geometry.coordinates;
  return `${lat.toFixed(5)},${lon.toFixed(5)}`;
}

fetch("caravaggio/data/caravaggio.geojson")
  .then(r => r.json())
  .then(gj => {
    const byPlace = new Map();
    for (const f of gj.features || []) {
      if (!f.geometry || f.geometry.type !== "Point") continue;
      const k = keyOf(f);
      if (!byPlace.has(k)) byPlace.set(k, []);
      byPlace.get(k).push(f);
    }

    for (const feats of byPlace.values()) {
      const p0 = feats[0].properties;
      const [lon, lat] = feats[0].geometry.coordinates;
      const kind = p0.kind || "museum";
      const marker = L.marker([lat, lon], { icon: pinIcon(kind, feats.length) })
        .bindPopup(placePopup(feats), { maxWidth: 320, minWidth: 240 });
      places.push({
        marker, kind, count: feats.length,
        country: p0.country || null,
        hasAccepted: feats.some(f => ATTR_ACCEPTED.has(f.properties.attribution)),
      });
    }
    refresh();
  })
  .catch(err => {
    console.error("Could not load caravaggio.geojson:", err);
    document.getElementById("stats").textContent = "no data yet — generate caravaggio.geojson";
  });

// filters
document.querySelectorAll('.filters input[data-kind]').forEach(cb => {
  cb.addEventListener("change", () => { state[cb.dataset.kind] = cb.checked; refresh(); });
});
document.getElementById("only-accepted").addEventListener("change", e => {
  state.onlyAccepted = e.target.checked; refresh();
});
