/* Map of the Caravaggios of the world.
   Consumes data/caravaggio.geojson (generated by ../scripts/build.py).
   Each feature = ONE work at its CURRENT location. Features are grouped by place:
   one pin per museum/church/collection, with the number of works held there. */

const KIND_LABEL = { museum: "Museum", church: "Church", private: "Private collection" };
const STATUS_LABEL = { lost: "lost", stolen: "stolen", destroyed: "destroyed" };
const ATTR_ACCEPTED = new Set(["certain", "generally accepted"]);
const GONE = new Set(["lost", "stolen", "destroyed"]);
const WIKI_LANGS = ["es", "en", "it"];

// painters loaded onto the (shared) map 1. Add a painter = add a line here.
const PAINTERS = [
  { slug: "caravaggio", name: "Caravaggio", file: "atlas/data/caravaggio.geojson" },
  { slug: "leonardo", name: "Leonardo da Vinci", file: "atlas/data/leonardo.geojson" },
  { slug: "raphael", name: "Raphael", file: "atlas/data/raphael.geojson" },
  { slug: "goya", name: "Goya", file: "atlas/data/goya.geojson" },
  { slug: "velazquez", name: "Velázquez", file: "atlas/data/velazquez.geojson" },
  { slug: "botticelli", name: "Botticelli", file: "atlas/data/botticelli.geojson" },
  { slug: "giotto", name: "Giotto", file: "atlas/data/giotto.geojson" },
  { slug: "ribera", name: "Ribera", file: "atlas/data/ribera.geojson" },
  { slug: "zurbaran", name: "Zurbarán", file: "atlas/data/zurbaran.geojson" },
  { slug: "masaccio", name: "Masaccio", file: "atlas/data/masaccio.geojson" },
  { slug: "titian", name: "Titian", file: "atlas/data/titian.geojson" },
  { slug: "vermeer", name: "Vermeer", file: "atlas/data/vermeer.geojson" },
  { slug: "rembrandt", name: "Rembrandt", file: "atlas/data/rembrandt.geojson" },
  { slug: "rubens", name: "Rubens", file: "atlas/data/rubens.geojson" },
  { slug: "vaneyck", name: "Jan van Eyck", file: "atlas/data/vaneyck.geojson" },
  { slug: "bruegel", name: "Pieter Bruegel the Elder", file: "atlas/data/bruegel.geojson" },
  { slug: "durer", name: "Albrecht Dürer", file: "atlas/data/durer.geojson" },
  { slug: "bosch", name: "Hieronymus Bosch", file: "atlas/data/bosch.geojson" },
  { slug: "fraangelico", name: "Fra Angelico", file: "atlas/data/fraangelico.geojson" },
  { slug: "piero", name: "Piero della Francesca", file: "atlas/data/piero.geojson" },
  { slug: "elgreco", name: "El Greco", file: "atlas/data/elgreco.geojson" },
  { slug: "poussin", name: "Nicolas Poussin", file: "atlas/data/poussin.geojson" },
  { slug: "veronese", name: "Veronese", file: "atlas/data/veronese.geojson" },
  { slug: "mantegna", name: "Mantegna", file: "atlas/data/mantegna.geojson" },
  { slug: "artemisia", name: "Artemisia Gentileschi", file: "atlas/data/artemisia.geojson" },
  { slug: "michelangelo", name: "Michelangelo", file: "atlas/data/michelangelo.geojson" },
  { slug: "tintoretto", name: "Tintoretto", file: "atlas/data/tintoretto.geojson" },
  { slug: "vandyck", name: "Anthony van Dyck", file: "atlas/data/vandyck.geojson" },
  { slug: "franshals", name: "Frans Hals", file: "atlas/data/franshals.geojson" },
  { slug: "holbein", name: "Hans Holbein the Younger", file: "atlas/data/holbein.geojson" },
  { slug: "david", name: "Jacques-Louis David", file: "atlas/data/david.geojson" },
  { slug: "weyden", name: "Rogier van der Weyden", file: "atlas/data/weyden.geojson" },
  { slug: "giorgione", name: "Giorgione", file: "atlas/data/giorgione.geojson" },
  { slug: "correggio", name: "Correggio", file: "atlas/data/correggio.geojson" },
  { slug: "parmigianino", name: "Parmigianino", file: "atlas/data/parmigianino.geojson" },
  { slug: "murillo", name: "Murillo", file: "atlas/data/murillo.geojson" },
  { slug: "cranach", name: "Lucas Cranach the Elder", file: "atlas/data/cranach.geojson" },
  { slug: "duccio", name: "Duccio", file: "atlas/data/duccio.geojson" },
  { slug: "ghirlandaio", name: "Domenico Ghirlandaio", file: "atlas/data/ghirlandaio.geojson" },
  { slug: "delatour", name: "Georges de La Tour", file: "atlas/data/delatour.geojson" },
  { slug: "memling", name: "Hans Memling", file: "atlas/data/memling.geojson" },
  { slug: "delsarto", name: "Andrea del Sarto", file: "atlas/data/delsarto.geojson" },
  { slug: "lorrain", name: "Claude Lorrain", file: "atlas/data/lorrain.geojson" },
];
const DATA_V = "0.27.2";   // MAJOR.MINOR.PATCH + cache-bust. Patch per change, minor for features. Keep atlas.html ?v= in sync. See README Changelog.
const BUILD_AT = "2026-08-20 17:31";   // update together with DATA_V — shown in the navbar
{ const b = document.getElementById("build"); if (b) b.textContent = `v${DATA_V} · updated ${BUILD_AT}`; }
// clicking the project title reloads the atlas to its clean default view (drops any #preset / filters)
document.querySelector(".brand")?.addEventListener("click", e => {
  e.preventDefault();
  history.replaceState(null, "", location.pathname);   // strip hash/query so reload is pristine
  location.reload();
});

// ── mobile bottom sheet: hosts marker popups on phones (see the popupopen handler) ──
const isMobile = () => window.matchMedia("(max-width: 640px)").matches;
function openSheet(html) {
  const body = document.getElementById("sheet-body");
  body.innerHTML = html;
  const b = body.querySelector(".pop-museum");           // clickable venue title → open in list
  if (b) b.addEventListener("click", () => { closeSheet(); selectMuseum(b.dataset.museum); });
  document.getElementById("sheet").hidden = false;
}
function closeSheet() { const s = document.getElementById("sheet"); if (s) s.hidden = true; }
document.getElementById("sheet-close")?.addEventListener("click", closeSheet);

// Each painter has a FIXED colour, by its position in the manifest (stable, always the
// same). The palette cycles if there are ever more painters than colours.
const PALETTE = [
  "#7a4a2b", "#3f6fb0", "#4a8f5f", "#9c4f7c", "#c8892a", "#2f8f8f", "#8a5cc0", "#b0483a",
  "#5b7f2f", "#c0568a", "#3a6b8f", "#8a6d2f", "#6a4fb0", "#2f8f6a", "#a0562a", "#4a4a8f",
  "#7d9b2f", "#b04f6a", "#2f6f9c", "#9c7a2f", "#5f4a9c", "#2f9c8a", "#b06a3a", "#6a5f4a",
  "#8f3f5a", "#3f8f5f", "#8f6f3f", "#5a3f8f", "#3f7f8f", "#8f4f3f", "#4f8f3f", "#7f3f8f",
  "#b08a2f", "#2f5f8f", "#8a2f6a", "#5f8a2f", "#2f8a8a", "#8a5f2f", "#6a2f8a", "#2f8a5f",
  "#a03f6a", "#3f6a3f", "#6a3f3f", "#3f3f6a", "#6a6a2f", "#2f6a6a", "#8f7a5a", "#5a5a8f",
];
const MULTI_COLOR = "#3f342b";   // a venue holding works by more than one painter
const LOST_COLOR = "#c0392b";
const painterColors = Object.fromEntries(PAINTERS.map((p, i) => [p.name, PALETTE[i % PALETTE.length]]));
function colorFor(name) { return painterColors[name] || MULTI_COLOR; }

// Most works are in Europe; open there. The ~12 in the Americas are one zoom-out away.
const map = L.map("map", { zoomControl: true, worldCopyJump: true }).setView([43, 9], 5);
L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png", {
  maxZoom: 19, attribution: "© OpenStreetMap",
}).addTo(map);
requestAnimationFrame(() => map.invalidateSize());
window.addEventListener("resize", () => map.invalidateSize());

// clustering: overlapping venues (e.g. all of Rome) merge at low zoom into one badge
// showing the TOTAL number of works, and split apart as you zoom in.
const cluster = L.markerClusterGroup({
  maxClusterRadius: 44,
  showCoverageOnHover: false,
  spiderfyOnMaxZoom: true,
  iconCreateFunction(c) {
    const works = c.getAllChildMarkers().reduce((a, m) => a + (m.options.works || 1), 0);
    const size = works >= 25 ? 48 : works >= 10 ? 40 : 32;
    return L.divIcon({
      html: `<div class="cl" style="width:${size}px;height:${size}px;line-height:${size - 4}px">${works}</div>`,
      className: "", iconSize: [size, size],
    });
  },
}).addTo(map);

let legendDiv;
const legend = L.control({ position: "bottomleft" });
legend.onAdd = () => { legendDiv = L.DomUtil.create("div", "legend"); return legendDiv; };
legend.addTo(map);
// reflects the current selection: the coloured painters (or a note when too many)
function updateLegend() {
  if (!legendDiv) return;
  const shown = PAINTERS.filter(p => state.painters[p.name] !== false);
  // Only useful when focused on a few painters — hidden by default (all/most selected)
  // so it never covers the map. Appears once you narrow to a handful.
  if (!shown.length || shown.length > 8 || shown.length === PAINTERS.length) {
    legendDiv.style.display = "none"; return;
  }
  legendDiv.style.display = "";
  const rows = shown.map(p => `<span class="le"><span class="k" style="background:${colorFor(p.name)}"></span>${esc(p.name)}</span>`).join("");
  legendDiv.innerHTML = `<div class="row">${rows}` +
    (shown.length > 1 ? `<span class="le"><span class="k" style="background:${MULTI_COLOR}"></span>Several</span>` : "") + `</div>`;
}

let allFeatures = [];   // raw point features from the geojson
const places = [];   // {marker, kind, feats, lat, lon, shown}
const works = [];    // {p (properties), lat, lon, marker} — one per painting, for the side panel
let panelVis = [];   // works currently listed in the panel
const state = { mode: "current", museum: true, church: true, private: true,
                acceptedOnly: true, museumFilter: null, yearMin: -Infinity, yearMax: Infinity, painters: {} };

// museum index (derived from the works): each venue with its painters + work count
const museumIndex = [];
function museumKey(p) { return p.museum_id || `${p.location || ""}|${p.city || ""}`; }
function buildMuseumIndex() {
  const m = new Map();
  for (const f of allFeatures) {
    const p = f.properties;
    if (!p.location) continue;
    const k = museumKey(p);
    if (!m.has(k)) m.set(k, {
      key: k, location: p.location, city: p.city || "", country: p.country || "",
      lat: f.geometry.coordinates[1], lon: f.geometry.coordinates[0], painters: new Set(), count: 0,
    });
    const e = m.get(k); e.painters.add(p.painter); e.count++;
  }
  museumIndex.length = 0;
  museumIndex.push(...[...m.values()].sort((a, b) => b.count - a.count));
}
PAINTERS.forEach(p => { state.painters[p.name] = true; });

function yearNum(p) {
  const m = (p.year || "").match(/1[2-9]\d{2}|20\d{2}/);   // 12xx+ (Giotto onward)
  return m ? +m[0] : null;
}
function inYear(p) {
  const y = yearNum(p);                       // unknown-date works stay visible
  return y == null || (y >= state.yearMin && y <= state.yearMax);
}
function passesAll(p) {
  const kindOk = state.mode === "painted" ? true : state[p.kind || "museum"];   // no venue type on map 2
  const painterOk = state.painters[p.painter] !== false;
  const attrOk = !state.acceptedOnly || ATTR_ACCEPTED.has(p.attribution);
  const museumOk = !state.museumFilter || museumKey(p) === state.museumFilter;
  return painterOk && kindOk && attrOk && museumOk && inYear(p);
}
// active coordinate per map: current location, or where it was painted (map 2)
function activeCoord(f) {
  if (state.mode === "painted") {
    const p = f.properties;
    return (p.creation_lat != null && p.creation_lon != null) ? [p.creation_lon, p.creation_lat] : null;
  }
  return f.geometry.coordinates;
}

function esc(s) {
  return String(s).replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
}

// subtle "?" for a disputed attribution (a scholarly nuance, not an error → not a warning ⚠)
function disputedMark(p) {
  return (p.attribution && !ATTR_ACCEPTED.has(p.attribution))
    ? ` <span class="qm" title="Disputed attribution">?</span>` : "";
}

// small painter tag: coloured dot + name (works belong to different painters now)
function painterTag(p) {
  if (!p.painter) return "";
  const c = colorFor(p.painter);
  return `<span class="pby"><span class="pdot" style="background:${c}"></span>${esc(p.painter)}</span>`;
}

// colour = painter (red overrides for lost/stolen); dashed ring = holds a disputed work
function pinIcon(color, n, { disputed = false } = {}) {
  return L.divIcon({
    className: "",
    html: `<div class="pin${disputed ? " disp" : ""}" style="background:${color}">${n}</div>`,
    iconSize: [26, 26], iconAnchor: [13, 13], popupAnchor: [0, -14],
  });
}

// "Wikipedia: ES EN IT · Wikidata" — only the languages that actually have an article.
function linksRow(p) {
  const wp = WIKI_LANGS.filter(l => p["wikipedia_" + l]).map(l =>
    `<a class="tag" href="${esc(p["wikipedia_" + l])}" target="_blank" rel="noopener">${l.toUpperCase()}</a>`);
  const parts = [];
  if (wp.length) parts.push(`<span class="lbl">Wikipedia</span>${wp.join("")}`);
  if (p.wikidata) parts.push(`<a class="tag wd" href="${esc(p.wikidata)}" target="_blank" rel="noopener">Wikidata</a>`);
  return parts.join(" ");
}

// Per-field "post-processed" chips are kept OUT of the public card (they singled out
// edited fields and read oddly). Provenance still lives in the data (_overrides); the
// card's Wikipedia/Wikidata links are the consistent, per-work source. Flip to re-enable.
const SHOW_PROVENANCE = false;

// visible provenance line for overridden fields (skip those given in `skip`).
function provLine(p, skip = []) {
  if (!SHOW_PROVENANCE || !p._overrides) return "";
  const rows = Object.entries(p._overrides)
    .filter(([field]) => !skip.includes(field))
    .map(([field, o]) => {
      const src = o.source ? ` · ${esc(o.source)}` : "";
      return `<div class="prov"${o.note ? ` title="${esc(o.note)}"` : ""}>` +
        `✎ ${esc(field)} · post-processed${src}</div>`;
    });
  return rows.join("");
}

// Place record: header (museum · city · country) + one row per work with a thumbnail.
const HEAD_SKIP_CURRENT = ["attribution", "title", "year", "genre", "medium", "dimensions", "image", "creation", "status"];
const HEAD_SKIP_PAINTED = ["attribution", "title", "year", "genre", "medium", "dimensions", "image", "city", "country", "location", "kind", "status"];
const WORK_SKIP = ["city", "country", "location", "kind", "creation"];

function placePopup(feats) {
  const p0 = feats[0].properties;
  const painted = state.mode === "painted";
  const n = feats.length;
  let head;
  if (painted) {
    head = `<div class="hd"><div class="nm">${esc(p0.creation_place || "Unknown")}</div>` +
      `<div class="meta">painted here · ${n} work${n > 1 ? "s" : ""}</div>` +
      `${provLine(p0, HEAD_SKIP_PAINTED)}</div>`;
  } else {
    const kindTxt = KIND_LABEL[p0.kind] || "";
    const where = [p0.city, p0.country].filter(Boolean).join(", ");
    // the venue name is a button → opens this museum in the side list (filters to it)
    head = `<div class="hd"><button type="button" class="nm pop-museum" data-museum="${esc(museumKey(p0))}"` +
      ` title="Show all works of this venue in the list">${esc(p0.location || "Location")}<span class="pm-arrow"> ↗</span></button>` +
      `<div class="meta">${esc(where)}${kindTxt ? ` · ${kindTxt}` : ""} · ${n} work${n > 1 ? "s" : ""}</div>` +
      `${provLine(p0, HEAD_SKIP_CURRENT)}</div>`;
  }

  const items = feats.map(f => {
    const p = f.properties;
    const yr = p.year ? ` <span class="yr">${esc(p.year)}</span>` : "";
    const att = p.attribution && !ATTR_ACCEPTED.has(p.attribution)
      ? ` <span class="tag att">${esc(p.attribution)}</span>` : "";
    const st = p.status && GONE.has(p.status)
      ? ` <span class="tag gone">${esc(STATUS_LABEL[p.status] || p.status)}</span>` : "";
    const factBits = [p.medium, p.dimensions];
    if (painted && p.location) factBits.push(`now in ${p.location}${p.city ? `, ${p.city}` : ""}`);
    const facts = factBits.filter(Boolean).map(esc).join(" · ");
    const factsRow = facts ? `<div class="fx">${facts}</div>` : "";
    const desc = p.summary ? `<div class="ds">${esc(p.summary)}</div>` : "";
    const cap = `${p.title || ""}${p.year ? ` (${p.year})` : ""} — ${p0.location || ""}`;
    const thumb = p.image
      ? `<img class="th" src="${esc(p.image)}" data-full="${esc(fullImage(p.image))}" data-cap="${esc(cap)}" alt="" loading="lazy">`
      : `<span class="th ph"></span>`;
    return `<li>${thumb}<div class="wk">` +
      `<div class="wt">${esc(p.title || "Untitled")}${yr}${att}${st}</div>` +
      `<div class="by">${painterTag(p)}</div>` +
      `${factsRow}${desc}<div class="lk">${linksRow(p)}</div>` +
      `${provLine(p, WORK_SKIP)}</div></li>`;
  }).join("");

  return `<div class="card">${head}<ul class="works">${items}</ul></div>`;
}

function refresh() {
  updateLegend();
  let workCount = 0, shownPlaces = 0;
  const countries = new Set();
  for (const pl of places) {
    const vis = pl.feats.filter(f => passesAll(f.properties));   // works here passing every filter
    if (vis.length) {
      const painted = state.mode === "painted";
      const lost = !painted && vis.some(f => GONE.has(f.properties.status));
      const disputed = vis.some(f => !ATTR_ACCEPTED.has(f.properties.attribution));
      const painters = new Set(vis.map(f => f.properties.painter));
      const color = lost ? LOST_COLOR
        : painters.size === 1 ? colorFor([...painters][0]) : MULTI_COLOR;
      pl.marker.options.works = vis.length;
      pl.marker.setIcon(pinIcon(color, vis.length, { disputed }));
      pl.marker.setPopupContent(placePopup(vis));
      if (!pl.shown) { cluster.addLayer(pl.marker); pl.shown = true; }
      shownPlaces++; workCount += vis.length;
      if (vis[0].properties.country) countries.add(vis[0].properties.country);
    } else if (pl.shown) { cluster.removeLayer(pl.marker); pl.shown = false; }
  }
  cluster.refreshClusters();
  document.getElementById("stats").textContent =
    `${workCount} works · ${shownPlaces} locations · ${countries.size} countries`;
  renderPanel();
  if (typeof view !== "undefined" && view.table) renderTable();
}

// group features by place (key = rounded coordinates)
function keyOf(f) {
  const [lon, lat] = f.geometry.coordinates;
  return `${lat.toFixed(5)},${lon.toFixed(5)}`;
}

// (re)build markers for the current mode: group features by their active coordinate
function buildMarkers() {
  cluster.clearLayers();
  places.length = 0; works.length = 0;
  const byPlace = new Map();
  for (const f of allFeatures) {
    const c = activeCoord(f);
    if (!c) continue;                       // e.g. undated work has no creation place
    const k = `${c[1].toFixed(5)},${c[0].toFixed(5)}`;
    if (!byPlace.has(k)) byPlace.set(k, []);
    byPlace.get(k).push(f);
  }
  for (const feats of byPlace.values()) {
    const [lon, lat] = activeCoord(feats[0]);
    const kind = feats[0].properties.kind || "museum";
    const marker = L.marker([lat, lon], { works: feats.length })
      // autoPan:false → opening a popup never scrolls the map out from under you
      .bindPopup("", { maxWidth: 320, minWidth: 240, autoPan: false });
    places.push({ marker, kind, feats, lat, lon, shown: false });
    for (const f of feats) works.push({ p: f.properties, lat, lon, marker });
  }
  refresh();
}

Promise.all(PAINTERS.map(p =>
  fetch(p.file + "?v=" + DATA_V).then(r => r.ok ? r.json() : { features: [] }).catch(() => ({ features: [] }))))
  .then(gjs => {
    allFeatures = [];
    gjs.forEach(gj => (gj.features || []).forEach(f => {
      if (f.geometry && f.geometry.type === "Point") allFeatures.push(f);
    }));
    const yrs = allFeatures.map(f => yearNum(f.properties)).filter(v => v != null);
    const [lo, hi] = robustBounds(yrs);   // ignore sparse mis-dated outliers (e.g. copies dated 1900)
    buildTimeline(lo, hi);                 // sets state.yearMin/Max
    buildMuseumIndex();
    buildPainterSelect();
    applyHash();                       // #caravaggio or #leonardo/painted → preset
    buildMarkers();
    map.on("moveend", renderPanel);
    // clicking the venue name at the top of a popup → open that museum in the side list
    map.on("popupopen", e => {
      // On phones a marker popup is taller than the small map and its header/close get cut
      // off the top. Route it into a fixed bottom sheet instead — always fully visible.
      if (isMobile()) { openSheet(e.popup.getContent()); map.closePopup(e.popup); return; }
      const b = e.popup.getElement() && e.popup.getElement().querySelector(".pop-museum");
      if (b) b.addEventListener("click", () => { map.closePopup(); selectMuseum(b.dataset.museum); });
    });
    map.on("click", closeSheet);   // tapping the map background dismisses the sheet
    window.addEventListener("hashchange", () => { applyHash(); buildMarkers(); });
  })
  .catch(err => {
    console.error("Could not load painter data:", err);
    document.getElementById("stats").textContent = "no data yet — generate the geojson files";
  });

// slider bounds. The low end is the true earliest year (early works are genuine, just
// sparse). The high end ignores isolated outliers — mis-dated copies (e.g. a Raphael
// "painting" dated 1900) sit alone, so we keep the largest year that has at least MIN
// works within a W-year window below it.
function robustBounds(years) {
  const s = years.slice().sort((a, b) => a - b), W = 15, MIN = 5;
  let hi = s[s.length - 1];
  for (let i = s.length - 1; i >= 0; i--) {
    if (s.filter(v => v >= s[i] - W && v <= s[i]).length >= MIN) { hi = s[i]; break; }
  }
  return [s[0], hi];
}

// hash presets: #caravaggio (focus one painter) · #leonardo/painted (+ map 2)
function applyHash() {
  const parts = location.hash.replace(/^#/, "").split("/").filter(Boolean);
  const focus = PAINTERS.find(p => p.slug === parts[0]);
  PAINTERS.forEach(p => { state.painters[p.name] = focus ? p === focus : true; });
  if (document.getElementById("painters-btn")) { updatePainterBtn(); renderPainterList(); }
  state.mode = parts.includes("painted") ? "painted" : "current";
  document.querySelectorAll(".mode-btn").forEach(b => b.classList.toggle("active", b.dataset.mode === state.mode));
  document.body.classList.toggle("mode-painted", state.mode === "painted");
}

// painter selector: a button + a searchable checklist popover (scales to many painters)
function buildPainterSelect() {
  const box = document.getElementById("painters");
  if (!box) return;
  box.innerHTML =
    `<button id="painters-btn" class="chip" type="button" aria-expanded="false">All painters ▾</button>` +
    `<div id="painters-pop" class="pop" hidden>` +
    `<input id="painters-search" class="pop-search" placeholder="Search painters or museums…" autocomplete="off">` +
    `<div class="pop-actions"><button type="button" data-act="all">All</button>` +
    `<button type="button" data-act="none">None</button></div>` +
    `<ul id="painters-list" class="pop-list"></ul></div>`;

  const btn = document.getElementById("painters-btn");
  const pop = document.getElementById("painters-pop");
  const search = document.getElementById("painters-search");

  btn.addEventListener("click", () => {
    const open = pop.hidden;
    pop.hidden = !open; btn.setAttribute("aria-expanded", String(open));
    if (open) { search.value = ""; renderPainterList(); search.focus(); }
  });
  document.addEventListener("click", e => {
    if (!pop.hidden && !box.contains(e.target)) { pop.hidden = true; btn.setAttribute("aria-expanded", "false"); }
  });
  document.addEventListener("keydown", e => { if (e.key === "Escape") pop.hidden = true; });
  search.addEventListener("input", renderPainterList);
  pop.querySelectorAll("[data-act]").forEach(b => b.addEventListener("click", () => {
    const on = b.dataset.act === "all";
    PAINTERS.forEach(p => { state.painters[p.name] = on; });
    renderPainterList(); updatePainterBtn(); refresh();
  }));
  renderPainterList(); updatePainterBtn();
}

// unified search: painters (toggle) + museums (filter to that venue)
function renderPainterList() {
  const q = (document.getElementById("painters-search")?.value || "").toLowerCase().trim();
  const ul = document.getElementById("painters-list");
  let html = "";

  const museumRow = m =>
    `<li class="mrow" data-museum="${esc(m.key)}"><span class="micon">🏛</span><div>` +
    `<div class="mname">${esc(m.location)}</div>` +
    `<div class="msub">${esc([m.city, m.country].filter(Boolean).join(", "))} · ${m.count} works · ` +
    `${m.painters.size} painter${m.painters.size > 1 ? "s" : ""}</div></div></li>`;

  if (q) {   // when searching: matching museums first (there are hundreds otherwise)
    const mus = museumIndex.filter(m =>
      m.location.toLowerCase().includes(q) || m.city.toLowerCase().includes(q)).slice(0, 8);
    if (mus.length) html += `<li class="pop-h">Museums</li>` + mus.map(museumRow).join("");
  }

  const pnt = PAINTERS.filter(p => p.name.toLowerCase().includes(q));
  if (pnt.length) {
    if (q && html) html += `<li class="pop-h">Painters</li>`;
    html += pnt.map(p => {
      const on = state.painters[p.name] !== false;
      return `<li class="prow"><label><input type="checkbox" data-painter="${esc(p.name)}"${on ? " checked" : ""}>` +
        `<span class="sw" style="background:${on ? colorFor(p.name) : "#cfc7bd"}"></span>${esc(p.name)}</label>` +
        `<button type="button" class="only" data-only="${esc(p.name)}">only</button></li>`;
    }).join("");
  }

  if (!q && museumIndex.length) {   // idle state: surface the museum search
    html += `<li class="pop-h">Popular museums · type to search all ${museumIndex.length}</li>` +
      museumIndex.slice(0, 6).map(museumRow).join("");
  }
  ul.innerHTML = html || `<li class="pop-empty">no match</li>`;

  ul.querySelectorAll("input[data-painter]").forEach(cb => cb.addEventListener("change", () => {
    state.painters[cb.dataset.painter] = cb.checked;
    refresh(); updatePainterBtn(); renderPainterList();
  }));
  // "only" (Kayak-style): deselect everyone, keep just this painter
  ul.querySelectorAll("button[data-only]").forEach(b => b.addEventListener("click", e => {
    e.preventDefault(); e.stopPropagation();
    PAINTERS.forEach(p => { state.painters[p.name] = p.name === b.dataset.only; });
    refresh(); updatePainterBtn(); renderPainterList();
  }));
  ul.querySelectorAll(".mrow").forEach(row => row.addEventListener("click", () => selectMuseum(row.dataset.museum)));
}

function selectMuseum(key) {
  state.museumFilter = key;
  const mu = museumIndex.find(m => m.key === key);
  const pop = document.getElementById("painters-pop");
  pop.hidden = true; document.getElementById("painters-btn").setAttribute("aria-expanded", "false");
  if (mu) { if (!view.map) { view.map = true; setView(); } map.setView([mu.lat, mu.lon], 14); }
  renderMuseumChip(); refresh();
}
function clearMuseum() { state.museumFilter = null; renderMuseumChip(); refresh(); }
function renderMuseumChip() {
  let el = document.getElementById("museum-chip");
  if (!state.museumFilter) { if (el) el.remove(); return; }
  const mu = museumIndex.find(m => m.key === state.museumFilter);
  if (!el) {
    el = document.createElement("span"); el.id = "museum-chip"; el.className = "chip mchip";
    document.getElementById("painters").after(el);
  }
  el.innerHTML = `🏛 ${esc(mu ? mu.location : "Museum")}${mu && mu.city ? ", " + esc(mu.city) : ""} ` +
    `<button type="button" aria-label="Clear museum">✕</button>`;
  el.querySelector("button").addEventListener("click", clearMuseum);
}

function updatePainterBtn() {
  const btn = document.getElementById("painters-btn");
  const sel = PAINTERS.filter(p => state.painters[p.name] !== false);
  const label = sel.length === PAINTERS.length ? `All ${PAINTERS.length} painters`
    : sel.length === 0 ? "No painters"
      : sel.length <= 2 ? sel.map(p => p.name.split(" ")[0]).join(", ")
        : `${sel.length} painters`;
  btn.textContent = "🎨 " + label + " ▾";
}

// filters
document.querySelectorAll('.filters input[data-kind]').forEach(cb => {
  cb.addEventListener("change", () => { state[cb.dataset.kind] = cb.checked; refresh(); });
});
document.getElementById("accepted-only").addEventListener("change", e => {
  state.acceptedOnly = e.target.checked; refresh();
});

// ── show/hide map and list (at least one stays visible) ──
const view = { map: true, panel: true };
function setView() {
  document.body.classList.toggle("hide-map", !view.map);
  document.body.classList.toggle("hide-panel", !view.panel);
  document.getElementById("v-map").classList.toggle("active", view.map);
  document.getElementById("v-list").classList.toggle("active", view.panel);
  if (view.map) setTimeout(() => map.invalidateSize(), 60);
  renderPanel();
}
document.getElementById("v-map").addEventListener("click", () => {
  if (view.map && !view.panel) return;      // it's the only pane shown → keep it
  view.map = !view.map; setView();
});
document.getElementById("v-list").addEventListener("click", () => {
  if (view.panel && !view.map) return;
  view.panel = !view.panel; setView();
});

// ── database view: every work as a sortable, filterable, exportable table ──
const TABLE_COLS = [
  { key: "img", label: "", sortable: false },
  { key: "painter", label: "Painter" },
  { key: "title", label: "Title" },
  { key: "year", label: "Year", num: true },
  { key: "medium", label: "Technique" },
  { key: "dimensions", label: "Size" },
  { key: "attribution", label: "Attribution" },
  { key: "location", label: "Museum / venue" },
  { key: "city", label: "City" },
  { key: "country", label: "Country" },
  { key: "links", label: "Links", sortable: false },
];
let tableSort = { key: "painter", dir: 1 };
let tableRowCache = [];
view.table = false;

// table respects the painter / attribution / year / museum filters (not the map-only kind toggles)
function tablePass(p) {
  return state.painters[p.painter] !== false
    && (!state.acceptedOnly || ATTR_ACCEPTED.has(p.attribution))
    && (!state.museumFilter || museumKey(p) === state.museumFilter)
    && inYear(p);
}
function tableRows() {
  const q = (document.getElementById("table-search")?.value || "").toLowerCase().trim();
  let rows = allFeatures.map(f => f.properties).filter(tablePass);
  if (q) rows = rows.filter(p => [p.painter, p.title, p.location, p.city, p.country, p.year, p.medium]
    .some(v => (v || "").toString().toLowerCase().includes(q)));
  const k = tableSort.key, num = TABLE_COLS.find(c => c.key === k)?.num;
  rows.sort((a, b) => {
    const va = num ? (yearNum(a) ?? -1e9) : (a[k] || "").toString().toLowerCase();
    const vb = num ? (yearNum(b) ?? -1e9) : (b[k] || "").toString().toLowerCase();
    return (va < vb ? -1 : va > vb ? 1 : 0) * tableSort.dir;
  });
  return rows;
}
function renderTable() {
  const thead = document.querySelector("#works-table thead");
  const tbody = document.querySelector("#works-table tbody");
  if (!thead) return;
  thead.innerHTML = "<tr>" + TABLE_COLS.map(c => {
    if (c.sortable === false) return `<th class="th-${c.key}">${esc(c.label)}</th>`;
    const arrow = tableSort.key === c.key ? (tableSort.dir === 1 ? " ▲" : " ▼") : "";
    return `<th class="th-${c.key} sortable" data-key="${c.key}">${esc(c.label)}<span class="ar">${arrow}</span></th>`;
  }).join("") + "</tr>";
  const rows = tableRows();
  tableRowCache = rows;
  document.getElementById("table-count").textContent =
    `${rows.length.toLocaleString()} work${rows.length === 1 ? "" : "s"}`;
  tbody.innerHTML = rows.map((p, i) => {
    const thumb = p.image
      ? `<img class="tth" src="${esc(p.image)}" data-full="${esc(fullImage(p.image))}" data-cap="${esc((p.title || "") + " — " + (p.location || ""))}" alt="" loading="lazy">`
      : `<span class="tth ph"></span>`;
    const att = p.attribution && !ATTR_ACCEPTED.has(p.attribution)
      ? `<span class="tag att">${esc(p.attribution)}</span>` : esc(p.attribution || "");
    return `<tr data-ri="${i}">` +
      `<td class="c-img">${thumb}</td>` +
      `<td class="c-painter"><span class="sw" style="background:${colorFor(p.painter)}"></span>${esc(p.painter)}</td>` +
      `<td class="c-title">${esc(p.title || "Untitled")}</td>` +
      `<td class="c-year">${esc(p.year || "")}</td>` +
      `<td class="c-medium">${esc(p.medium || "")}</td>` +
      `<td class="c-dim">${esc(p.dimensions || "")}</td>` +
      `<td class="c-attr">${att}</td>` +
      `<td class="c-loc">${esc(p.location || "")}</td>` +
      `<td class="c-city">${esc(p.city || "")}</td>` +
      `<td class="c-country">${esc(p.country || "")}</td>` +
      `<td class="c-links">${linksRow(p)}</td>` +
      "</tr>";
  }).join("");
  thead.querySelectorAll("th.sortable").forEach(th => th.addEventListener("click", () => {
    const k = th.dataset.key;
    if (tableSort.key === k) tableSort.dir *= -1; else tableSort = { key: k, dir: 1 };
    renderTable();
  }));
  tbody.querySelectorAll(".tth[data-full]").forEach(img => img.addEventListener("click", () =>
    openLightbox(img.dataset.full, img.dataset.cap)));
  // click a row (not a thumbnail/link) → jump to that work on the map
  tbody.querySelectorAll("tr[data-ri]").forEach(tr => tr.addEventListener("click", e => {
    if (e.target.closest("a, img")) return;
    const p = tableRowCache[+tr.dataset.ri];
    const w = p && works.find(w => w.p === p);
    if (!w) return;
    setTableView(false);
    if (!view.map) { view.map = true; setView(); }
    setTimeout(() => { map.setView([w.lat, w.lon], Math.max(map.getZoom(), 13));
      cluster.zoomToShowLayer(w.marker, () => w.marker.openPopup()); }, 80);
  }));
}
function setTableView(on) {
  view.table = on;
  document.body.classList.toggle("show-table", on);
  document.getElementById("v-table").classList.toggle("active", on);
  document.getElementById("table").hidden = !on;
  document.getElementById("main").hidden = on;
  if (on) renderTable();
  else setTimeout(() => map.invalidateSize(), 60);
}
document.getElementById("v-table").addEventListener("click", () => setTableView(!view.table));
document.getElementById("table-search").addEventListener("input", renderTable);
document.getElementById("table-csv").addEventListener("click", () => {
  const cols = TABLE_COLS.filter(c => !["img", "links"].includes(c.key));
  const cell = s => `"${(s ?? "").toString().replace(/"/g, '""')}"`;
  const lines = [cols.map(c => cell(c.label)).join(",")];
  for (const p of tableRows()) lines.push(cols.map(c => cell(p[c.key])).join(","));
  const blob = new Blob([lines.join("\n")], { type: "text/csv;charset=utf-8" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob); a.download = "atlas-of-painting.csv"; a.click();
  URL.revokeObjectURL(a.href);
});

// ── map mode: "where they are today" (venues) vs "where they were painted" (cities) ──
document.querySelectorAll(".mode-btn").forEach(btn => {
  btn.addEventListener("click", () => {
    if (state.mode === btn.dataset.mode) return;
    state.mode = btn.dataset.mode;
    document.querySelectorAll(".mode-btn").forEach(b => b.classList.toggle("active", b === btn));
    document.body.classList.toggle("mode-painted", state.mode === "painted");
    if (nearestLine) { map.removeLayer(nearestLine); nearestLine = null; }
    buildMarkers();   // regroup by the active coordinate + refresh
  });
});

// ── time slider: filter the map + panel by year of creation (dual-handle range) ──
function buildTimeline(min, max) {
  const lo = document.getElementById("tl-min");
  const hi = document.getElementById("tl-max");
  const label = document.getElementById("tl-label");
  const fill = document.getElementById("tl-fill");
  lo.min = hi.min = min; lo.max = hi.max = max;
  lo.value = min; hi.value = max;
  state.yearMin = min; state.yearMax = max;

  const paint = () => {
    const span = max - min || 1;
    const a = (state.yearMin - min) / span * 100;
    const b = (state.yearMax - min) / span * 100;
    fill.style.left = a + "%"; fill.style.right = (100 - b) + "%";
    label.textContent = state.yearMin === state.yearMax ? `${state.yearMin}` : `${state.yearMin}–${state.yearMax}`;
  };
  const update = () => {
    let a = +lo.value, b = +hi.value;
    if (a > b) { if (document.activeElement === lo) { b = a; hi.value = b; } else { a = b; lo.value = a; } }
    state.yearMin = a; state.yearMax = b;
    paint(); refresh();
  };
  lo.addEventListener("input", update);
  hi.addEventListener("input", update);
  paint();
}

// ── side panel: the works currently within the map viewport, grouped by venue ──
function renderPanel() {
  const bounded = view.map;                    // when the map is hidden, list ALL works (no bounds)
  const b = bounded ? map.getBounds() : null;
  const vis = works.filter(w => passesAll(w.p) && (!bounded || b.contains([w.lat, w.lon])));

  // group by the active place (venue on map 1, creation city on map 2)
  const painted = state.mode === "painted";
  const groups = new Map();
  for (const w of vis) {
    const k = `${w.lat.toFixed(5)},${w.lon.toFixed(5)}`;
    if (!groups.has(k)) groups.set(k, {
      location: painted ? (w.p.creation_place || "Unknown") : (w.p.location || "Location"),
      city: painted ? "" : (w.p.city || ""), items: [],
    });
    groups.get(k).items.push(w);
  }
  const ordered = [...groups.values()].sort((a, z) =>
    (a.city || "zzz").localeCompare(z.city || "zzz") || a.location.localeCompare(z.location));

  document.getElementById("panel-head").textContent =
    `${vis.length} work${vis.length === 1 ? "" : "s"}${bounded ? " in view" : ""}`;

  const ul = document.getElementById("worklist");
  if (!vis.length) {
    ul.innerHTML = `<li class="empty">Pan or zoom the map — the works in view are listed here.</li>`;
    panelVis = [];
    return;
  }
  panelVis = [];
  let html = "";
  for (const g of ordered) {
    g.items.sort((a, z) => (yearNum(a.p) || 9999) - (yearNum(z.p) || 9999));
    html += `<li class="grp"><span>${esc(g.location)}${g.city ? ` · ${esc(g.city)}` : ""}</span>` +
      `<span class="n">${g.items.length}</span></li>`;
    for (const w of g.items) {
      const i = panelVis.length; panelVis.push(w);
      const p = w.p;
      const cap = `${p.title || ""}${p.year ? ` (${p.year})` : ""} — ${p.location || ""}`;
      const thumb = p.image
        ? `<img class="th" src="${esc(p.image)}" data-full="${esc(fullImage(p.image))}" data-cap="${esc(cap)}" alt="">`
        : `<span class="th"></span>`;
      html += `<li data-i="${i}">${thumb}<div>` +
        `<div class="wt">${esc(p.title || "Untitled")}${p.year ? ` <span class="sub">${esc(p.year)}</span>` : ""}${disputedMark(p)}</div>` +
        `<div class="sub">${painterTag(p)}${p.medium ? " · " + esc(p.medium) : ""}</div></div></li>`;
    }
  }
  ul.innerHTML = html;
}

document.getElementById("worklist").addEventListener("click", e => {
  if (e.target.closest("img.th")) return;          // thumbnail → lightbox (handled below)
  const li = e.target.closest("li[data-i]");
  if (!li) return;
  const w = panelVis[+li.dataset.i];
  if (!w) return;
  const go = () => {
    map.setView([w.lat, w.lon], Math.max(map.getZoom(), 13));
    cluster.zoomToShowLayer(w.marker, () => w.marker.openPopup());
  };
  if (!view.map) { view.map = true; setView(); setTimeout(go, 120); } else go();
});

// ── lightbox: the painting at full size ──
function fullImage(thumbUrl) {
  if (!thumbUrl) return "";
  return /width=\d+/.test(thumbUrl) ? thumbUrl.replace(/width=\d+/, "width=1600") : thumbUrl;
}
const lb = document.getElementById("lightbox");
function openLightbox(url, cap) {
  document.getElementById("lb-img").src = url;
  document.getElementById("lb-cap").textContent = cap || "";
  lb.hidden = false;
}
function closeLightbox() { lb.hidden = true; document.getElementById("lb-img").src = ""; }
document.getElementById("lb-close").addEventListener("click", closeLightbox);
lb.addEventListener("click", e => { if (e.target === lb) closeLightbox(); });
document.addEventListener("keydown", e => { if (e.key === "Escape") closeLightbox(); });
document.addEventListener("click", e => {
  const img = e.target.closest("img.th");
  if (img && img.dataset.full) openLightbox(img.dataset.full, img.dataset.cap);
});
// Wikimedia Commons occasionally resets HTTP/2 under a burst of thumbnail requests
// (big popup/table). Degrade a failed thumbnail to the neutral placeholder box instead
// of a broken-image icon. (Capture phase — <img> error events don't bubble.)
document.addEventListener("error", e => {
  const img = e.target;
  if (img.tagName === "IMG" && (img.classList.contains("th") || img.classList.contains("tth"))) {
    img.classList.add("ph"); img.removeAttribute("src"); img.removeAttribute("data-full");
  }
}, true);

// ── geolocation: your nearest Caravaggio ──
function haversine(lat1, lon1, lat2, lon2) {
  const R = 6371, r = x => x * Math.PI / 180;
  const dLat = r(lat2 - lat1), dLon = r(lon2 - lon1);
  const s = Math.sin(dLat / 2) ** 2 + Math.cos(r(lat1)) * Math.cos(r(lat2)) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(s));
}
let userMarker = null, nearestLine = null;
function showBanner(html) {
  let el = document.getElementById("banner");
  if (!el) { el = document.createElement("div"); el.id = "banner"; document.body.appendChild(el); }
  el.innerHTML = `${html} <button id="banner-x" aria-label="Dismiss">✕</button>`;
  el.hidden = false;
  document.getElementById("banner-x").onclick = () => { el.hidden = true; };
}
// "Near me" is a toggle: first click locates + frames your nearest work; click again
// (it stays pressed) clears the pins and restores the map to exactly where it was.
let nearMeActive = false, nearMePrevView = null;
function clearNearMe() {
  const btn = document.getElementById("locate");
  if (userMarker) { map.removeLayer(userMarker); userMarker = null; }
  if (nearestLine) { map.removeLayer(nearestLine); nearestLine = null; }
  const bn = document.getElementById("banner"); if (bn) bn.hidden = true;
  btn.textContent = "📍 Near me"; btn.classList.remove("active"); btn.disabled = false;
  if (nearMePrevView) { map.setView(nearMePrevView.center, nearMePrevView.zoom); nearMePrevView = null; }
  nearMeActive = false;
}
document.getElementById("locate").addEventListener("click", () => {
  const btn = document.getElementById("locate");
  if (nearMeActive) { clearNearMe(); return; }              // toggle off → restore previous view
  if (!navigator.geolocation) { showBanner("Geolocation is not available in this browser."); return; }
  btn.textContent = "📍 Locating…"; btn.disabled = true;
  navigator.geolocation.getCurrentPosition(pos => {
    btn.disabled = false;
    const { latitude: lat, longitude: lon } = pos.coords;
    let best = null, bd = Infinity;
    for (const w of works) {
      if (!passesAll(w.p)) continue;
      const d = haversine(lat, lon, w.lat, w.lon);
      if (d < bd) { bd = d; best = w; }
    }
    if (!best) { btn.textContent = "📍 Near me"; showBanner("No works match the current filters."); return; }
    nearMePrevView = { center: map.getCenter(), zoom: map.getZoom() };   // remember, to restore on toggle-off
    if (userMarker) map.removeLayer(userMarker);
    userMarker = L.marker([lat, lon], {
      icon: L.divIcon({ className: "", html: `<div class="me"></div>`, iconSize: [16, 16], iconAnchor: [8, 8] }),
      zIndexOffset: 1000,
    }).addTo(map).bindPopup("You are here");
    const km = bd < 1 ? `${Math.round(bd * 1000)} m` : `${bd < 10 ? bd.toFixed(1) : Math.round(bd)} km`;
    if (nearestLine) map.removeLayer(nearestLine);
    nearestLine = L.polyline([[lat, lon], [best.lat, best.lon]],
      { color: "#1a73e8", weight: 2, dashArray: "5,7", opacity: .8 }).addTo(map);
    map.fitBounds([[lat, lon], [best.lat, best.lon]], { padding: [70, 70], maxZoom: 12 });
    cluster.zoomToShowLayer(best.marker, () => best.marker.openPopup());
    btn.textContent = "📍 Near me"; btn.classList.add("active");   // pressed → click again to reset
    nearMeActive = true;
    showBanner(`Your nearest painting: <b>${esc(best.p.title || "Untitled")}</b> — ` +
      `${esc([best.p.location, best.p.city].filter(Boolean).join(", "))} · <b>${km}</b> away · ` +
      `<span class="bn-hint">tap “Near me” again to reset the view</span>`);
  }, err => {
    btn.textContent = "📍 Near me"; btn.disabled = false;
    showBanner("Could not get your location: " + esc(err.message));
  }, { enableHighAccuracy: false, timeout: 10000, maximumAge: 60000 });
});
