/* Map of the Caravaggios of the world.
   Consumes data/caravaggio.geojson (generated by ../scripts/build.py).
   Each feature = ONE work at its CURRENT location. Features are grouped by place:
   one pin per museum/church/collection, with the number of works held there. */

const KIND_LABEL = { museum: "Museum", church: "Church", private: "Private collection" };
const STATUS_LABEL = { lost: "lost", stolen: "stolen", destroyed: "destroyed" };
const ATTR_ACCEPTED = new Set(["certain", "generally accepted"]);
const GONE = new Set(["lost", "stolen", "destroyed"]);
const WIKI_LANGS = ["es", "en", "it"];

// painters loaded onto the (shared) map 1. Add a painter = add a line here.
const PAINTERS = [
  { slug: "caravaggio", name: "Caravaggio", file: "atlas/data/caravaggio.geojson" },
  { slug: "leonardo", name: "Leonardo da Vinci", file: "atlas/data/leonardo.geojson" },
  { slug: "raphael", name: "Raphael", file: "atlas/data/raphael.geojson" },
  { slug: "goya", name: "Goya", file: "atlas/data/goya.geojson" },
  { slug: "velazquez", name: "Velázquez", file: "atlas/data/velazquez.geojson" },
  { slug: "botticelli", name: "Botticelli", file: "atlas/data/botticelli.geojson" },
  { slug: "giotto", name: "Giotto", file: "atlas/data/giotto.geojson" },
  { slug: "ribera", name: "Ribera", file: "atlas/data/ribera.geojson" },
  { slug: "zurbaran", name: "Zurbarán", file: "atlas/data/zurbaran.geojson" },
  { slug: "masaccio", name: "Masaccio", file: "atlas/data/masaccio.geojson" },
  { slug: "titian", name: "Titian", file: "atlas/data/titian.geojson" },
  { slug: "vermeer", name: "Vermeer", file: "atlas/data/vermeer.geojson" },
  { slug: "rembrandt", name: "Rembrandt", file: "atlas/data/rembrandt.geojson" },
  { slug: "rubens", name: "Rubens", file: "atlas/data/rubens.geojson" },
  { slug: "vaneyck", name: "Jan van Eyck", file: "atlas/data/vaneyck.geojson" },
  { slug: "bruegel", name: "Pieter Bruegel the Elder", file: "atlas/data/bruegel.geojson" },
  { slug: "durer", name: "Albrecht Dürer", file: "atlas/data/durer.geojson" },
  { slug: "bosch", name: "Hieronymus Bosch", file: "atlas/data/bosch.geojson" },
  { slug: "fraangelico", name: "Fra Angelico", file: "atlas/data/fraangelico.geojson" },
  { slug: "piero", name: "Piero della Francesca", file: "atlas/data/piero.geojson" },
  { slug: "elgreco", name: "El Greco", file: "atlas/data/elgreco.geojson" },
  { slug: "poussin", name: "Nicolas Poussin", file: "atlas/data/poussin.geojson" },
  { slug: "veronese", name: "Veronese", file: "atlas/data/veronese.geojson" },
  { slug: "mantegna", name: "Mantegna", file: "atlas/data/mantegna.geojson" },
  { slug: "artemisia", name: "Artemisia Gentileschi", file: "atlas/data/artemisia.geojson" },
  { slug: "michelangelo", name: "Michelangelo", file: "atlas/data/michelangelo.geojson" },
  { slug: "tintoretto", name: "Tintoretto", file: "atlas/data/tintoretto.geojson" },
  { slug: "vandyck", name: "Anthony van Dyck", file: "atlas/data/vandyck.geojson" },
  { slug: "franshals", name: "Frans Hals", file: "atlas/data/franshals.geojson" },
  { slug: "holbein", name: "Hans Holbein the Younger", file: "atlas/data/holbein.geojson" },
  { slug: "david", name: "Jacques-Louis David", file: "atlas/data/david.geojson" },
  { slug: "weyden", name: "Rogier van der Weyden", file: "atlas/data/weyden.geojson" },
  { slug: "giorgione", name: "Giorgione", file: "atlas/data/giorgione.geojson" },
  { slug: "correggio", name: "Correggio", file: "atlas/data/correggio.geojson" },
  { slug: "parmigianino", name: "Parmigianino", file: "atlas/data/parmigianino.geojson" },
  { slug: "murillo", name: "Murillo", file: "atlas/data/murillo.geojson" },
  { slug: "cranach", name: "Lucas Cranach the Elder", file: "atlas/data/cranach.geojson" },
  { slug: "duccio", name: "Duccio", file: "atlas/data/duccio.geojson" },
  { slug: "ghirlandaio", name: "Domenico Ghirlandaio", file: "atlas/data/ghirlandaio.geojson" },
  { slug: "delatour", name: "Georges de La Tour", file: "atlas/data/delatour.geojson" },
  { slug: "memling", name: "Hans Memling", file: "atlas/data/memling.geojson" },
  { slug: "delsarto", name: "Andrea del Sarto", file: "atlas/data/delsarto.geojson" },
  { slug: "lorrain", name: "Claude Lorrain", file: "atlas/data/lorrain.geojson" },
  { slug: "vangogh", name: "Vincent van Gogh", file: "atlas/data/vangogh.geojson" },
  { slug: "monet", name: "Claude Monet", file: "atlas/data/monet.geojson" },
  { slug: "manet", name: "Édouard Manet", file: "atlas/data/manet.geojson" },
  { slug: "cezanne", name: "Paul Cézanne", file: "atlas/data/cezanne.geojson" },
  { slug: "renoir", name: "Pierre-Auguste Renoir", file: "atlas/data/renoir.geojson" },
  { slug: "degas", name: "Edgar Degas", file: "atlas/data/degas.geojson" },
  { slug: "gauguin", name: "Paul Gauguin", file: "atlas/data/gauguin.geojson" },
  { slug: "seurat", name: "Georges Seurat", file: "atlas/data/seurat.geojson" },
  { slug: "pissarro", name: "Camille Pissarro", file: "atlas/data/pissarro.geojson" },
  { slug: "sorolla", name: "Joaquín Sorolla", file: "atlas/data/sorolla.geojson" },
  { slug: "picasso", name: "Pablo Picasso", file: "atlas/data/picasso.geojson" },
  { slug: "frida", name: "Frida Kahlo", file: "atlas/data/frida.geojson" },
  { slug: "rivera", name: "Diego Rivera", file: "atlas/data/rivera.geojson" },
  { slug: "turner", name: "J.M.W. Turner", file: "atlas/data/turner.geojson" },
  { slug: "bellini", name: "Giovanni Bellini", file: "atlas/data/bellini.geojson" },
  { slug: "friedrich", name: "Caspar David Friedrich", file: "atlas/data/friedrich.geojson" },
  { slug: "canaletto", name: "Canaletto", file: "atlas/data/canaletto.geojson" },
  { slug: "delacroix", name: "Eugène Delacroix", file: "atlas/data/delacroix.geojson" },
  { slug: "tiepolo", name: "Giovanni Battista Tiepolo", file: "atlas/data/tiepolo.geojson" },
  { slug: "uccello", name: "Paolo Uccello", file: "atlas/data/uccello.geojson" },
  { slug: "lippi", name: "Fra Filippo Lippi", file: "atlas/data/lippi.geojson" },
  { slug: "perugino", name: "Pietro Perugino", file: "atlas/data/perugino.geojson" },
  { slug: "bronzino", name: "Bronzino", file: "atlas/data/bronzino.geojson" },
  { slug: "carracci", name: "Annibale Carracci", file: "atlas/data/carracci.geojson" },
  { slug: "reni", name: "Guido Reni", file: "atlas/data/reni.geojson" },
  { slug: "guardi", name: "Francesco Guardi", file: "atlas/data/guardi.geojson" },
  { slug: "zuloaga", name: "Ignacio Zuloaga", file: "atlas/data/zuloaga.geojson" },
  { slug: "dali", name: "Salvador Dalí", file: "atlas/data/dali.geojson" },
  { slug: "miro", name: "Joan Miró", file: "atlas/data/miro.geojson" },
];
const DATA_V = "0.40.0";   // MAJOR.MINOR.PATCH + cache-bust. Patch per change, minor for features. Keep atlas.html ?v= in sync. See README Changelog.
const BUILD_AT = "2026-08-24 00:13";   // update together with DATA_V — shown in the navbar
{ const b = document.getElementById("build"); if (b) b.textContent = `v${DATA_V} · ${BUILD_AT}`; }
// clicking the project title reloads the atlas to its clean default view (drops any #preset / filters)
document.querySelector(".brand")?.addEventListener("click", e => {
  e.preventDefault();
  history.replaceState(null, "", location.pathname);   // strip hash/query so reload is pristine
  location.reload();
});

// ── error / missing-work report (posts to the shared Google Apps Script, like frontones) ──
const REPORT_ENDPOINT = "https://script.google.com/macros/s/AKfycbxgpFado69HbPzmWw0d1uqqwMT3ipapcUwtSp9pWyOELcrND5idSUE2k4WG9D4QWa4Q/exec";
function openReport(prefill = {}) {
  const f = document.getElementById("report-form");
  f.painter.value = prefill.painter || "";
  f.title.value = prefill.title || "";
  f.qid.value = prefill.qid || "";
  document.getElementById("report-msg").textContent = "";
  document.getElementById("report-panel").hidden = false;
}
function closeReport() {
  document.getElementById("report-panel").hidden = true;
  document.getElementById("report-form").reset();
}
document.getElementById("report-open")?.addEventListener("click", () => openReport());
document.getElementById("report-cancel")?.addEventListener("click", closeReport);
document.getElementById("report-panel")?.addEventListener("click", e => {
  if (e.target.id === "report-panel") closeReport();      // click backdrop to dismiss
});
document.getElementById("report-form")?.addEventListener("submit", e => {
  e.preventDefault();
  const data = new URLSearchParams(new FormData(e.target));
  const send = document.getElementById("report-send"), msg = document.getElementById("report-msg");
  send.disabled = true; msg.textContent = "Sending…";
  fetch(REPORT_ENDPOINT, { method: "POST", mode: "no-cors", body: data })
    .then(() => { msg.textContent = "Thanks! I'll review it. 🙌"; setTimeout(closeReport, 1500); })
    .catch(() => { msg.textContent = "Couldn't send — please try again later."; })
    .finally(() => { send.disabled = false; });
});

// ── mobile bottom sheet: hosts marker popups on phones (see the popupopen handler) ──
const isMobile = () => window.matchMedia("(max-width: 640px)").matches;
function openSheet(html) {
  const body = document.getElementById("sheet-body");
  body.innerHTML = html;
  const b = body.querySelector(".pop-museum");           // clickable venue title → open in list
  if (b) b.addEventListener("click", () => { closeSheet(); selectMuseum(b.dataset.museum); });
  document.getElementById("sheet").hidden = false;
}
function closeSheet() { const s = document.getElementById("sheet"); if (s) s.hidden = true; }
document.getElementById("sheet-close")?.addEventListener("click", closeSheet);

// Each painter has a FIXED colour, by its position in the manifest (stable, always the
// same). The palette cycles if there are ever more painters than colours.
const PALETTE = [
  "#7a4a2b", "#3f6fb0", "#4a8f5f", "#9c4f7c", "#c8892a", "#2f8f8f", "#8a5cc0", "#b0483a",
  "#5b7f2f", "#c0568a", "#3a6b8f", "#8a6d2f", "#6a4fb0", "#2f8f6a", "#a0562a", "#4a4a8f",
  "#7d9b2f", "#b04f6a", "#2f6f9c", "#9c7a2f", "#5f4a9c", "#2f9c8a", "#b06a3a", "#6a5f4a",
  "#8f3f5a", "#3f8f5f", "#8f6f3f", "#5a3f8f", "#3f7f8f", "#8f4f3f", "#4f8f3f", "#7f3f8f",
  "#b08a2f", "#2f5f8f", "#8a2f6a", "#5f8a2f", "#2f8a8a", "#8a5f2f", "#6a2f8a", "#2f8a5f",
  "#a03f6a", "#3f6a3f", "#6a3f3f", "#3f3f6a", "#6a6a2f", "#2f6a6a", "#8f7a5a", "#5a5a8f",
  "#b0692f", "#2f8fb0", "#7a9c3f", "#9c3f7a", "#3f9c7a", "#9c6a3f", "#5f3f9c", "#3f7a9c",
  "#6a8f4a", "#b0417a", "#417a8f", "#8f6a41", "#7a41b0", "#41a06a", "#a0552f", "#4a6a8f",
  "#9c8f3f", "#6a417a", "#2f7a5a", "#8f414a", "#5a8f2f", "#417a6a", "#8f5a7a", "#3f5a7a",
];
const MULTI_COLOR = "#3f342b";   // a venue holding works by more than one painter
const LOST_COLOR = "#c0392b";
const painterColors = Object.fromEntries(PAINTERS.map((p, i) => [p.name, PALETTE[i % PALETTE.length]]));
function colorFor(name) { return painterColors[name] || MULTI_COLOR; }

// a {colour: count} map → a CSS background: solid for one painter, a pie (conic-gradient) for several
function pieStyle(counts) {
  const entries = Object.entries(counts).sort((a, b) => b[1] - a[1]);
  if (entries.length <= 1) return { style: `background:${entries.length ? entries[0][0] : MULTI_COLOR}`, pie: false };
  const total = entries.reduce((s, [, n]) => s + n, 0);
  let acc = 0;
  const stops = entries.map(([col, n]) => {
    const a = acc / total * 360; acc += n; return `${col} ${a}deg ${acc / total * 360}deg`;
  }).join(",");
  return { style: `background:conic-gradient(${stops})`, pie: true };
}

// art-historical period per painter (one primary bucket each) — groups the painter selector
const ERAS = [
  { key: "1", label: "Gothic & early Renaissance" },
  { key: "2", label: "High Renaissance & Mannerism" },
  { key: "3", label: "Baroque" },
  { key: "4", label: "18th–19th century" },
  { key: "5", label: "Impressionism & Post-Impressionism" },
  { key: "6", label: "Modern (20th c.)" },
];
// one primary period each; painters that genuinely straddle two get an array (listed in both)
const ERA_OF = {
  giotto: "1", duccio: "1", masaccio: "1", fraangelico: "1", piero: "1", botticelli: "1",
  ghirlandaio: "1", mantegna: "1", vaneyck: "1", weyden: "1", memling: "1", bosch: "1",
  leonardo: "2", raphael: "2", michelangelo: "2", durer: "2", cranach: "2", holbein: "2",
  giorgione: "2", titian: "2", correggio: "2", delsarto: "2", parmigianino: "2", bruegel: "2",
  tintoretto: "2", veronese: "2", elgreco: ["2", "3"],   // Mannerism ↔ Baroque (d. 1614)
  caravaggio: "3", artemisia: "3", rubens: "3", vandyck: "3", rembrandt: "3", vermeer: "3",
  franshals: "3", velazquez: "3", ribera: "3", zurbaran: "3", murillo: "3", poussin: "3",
  lorrain: "3", delatour: "3",
  goya: "4", david: "4",
  manet: "5", monet: "5", renoir: "5", degas: "5", pissarro: "5", cezanne: ["5", "6"],  // Post-Imp ↔ Modern
  vangogh: "5", gauguin: "5", seurat: "5", sorolla: "5",
  picasso: "6", frida: "6", rivera: "6",
  // added 2026-08-22
  uccello: "1", lippi: "1", perugino: "1", bellini: "1",
  bronzino: "2",
  carracci: "3", reni: "3",
  canaletto: "4", tiepolo: "4", guardi: "4", turner: "4", friedrich: "4", delacroix: "4",
  zuloaga: "5",
  dali: "6", miro: "6",
};
const erasOf = slug => [].concat(ERA_OF[slug] || []);

// the OTHER axis: national school (the way museums arrange their rooms)
const SCHOOLS = [
  { key: "it", label: "Italian" }, { key: "es", label: "Spanish" }, { key: "fr", label: "French" },
  { key: "nl", label: "Dutch" }, { key: "fl", label: "Flemish / Netherlandish" },
  { key: "de", label: "German" }, { key: "en", label: "English" }, { key: "mx", label: "Mexican" },
];
const SCHOOL_OF = {
  duccio: "it", giotto: "it", masaccio: "it", fraangelico: "it", piero: "it", botticelli: "it",
  ghirlandaio: "it", mantegna: "it", leonardo: "it", raphael: "it", michelangelo: "it",
  giorgione: "it", titian: "it", correggio: "it", delsarto: "it", parmigianino: "it",
  tintoretto: "it", veronese: "it", caravaggio: "it", artemisia: "it",
  velazquez: "es", goya: "es", elgreco: ["es", "it"], ribera: "es", zurbaran: "es", murillo: "es",
  sorolla: "es", picasso: ["es", "fr"],   // El Greco trained in Venice; Picasso = École de Paris
  poussin: "fr", lorrain: "fr", delatour: "fr", david: "fr", manet: "fr", monet: "fr",
  renoir: "fr", degas: "fr", pissarro: "fr", cezanne: "fr", gauguin: "fr", seurat: "fr",
  rembrandt: "nl", vermeer: "nl", franshals: "nl", vangogh: ["nl", "fr"],   // Dutch, painted in France
  vaneyck: "fl", weyden: "fl", memling: "fl", bosch: "fl", bruegel: "fl", rubens: "fl", vandyck: "fl",
  durer: "de", cranach: "de", holbein: "de",
  frida: "mx", rivera: "mx",
  // added 2026-08-22
  bellini: "it", canaletto: "it", tiepolo: "it", uccello: "it", lippi: "it", perugino: "it",
  bronzino: "it", carracci: "it", reni: "it", guardi: "it",
  turner: "en", friedrich: "de", delacroix: "fr", zuloaga: "es", dali: "es", miro: "es",
};
const schoolsOf = slug => [].concat(SCHOOL_OF[slug] || []);

// birth year per painter — sorts the selector chronologically WITHIN each group (the eras/schools
// are already roughly chronological between groups). Early ones are the accepted "c." estimates.
const BORN = {
  duccio: 1255, giotto: 1267, vaneyck: 1390, fraangelico: 1395, weyden: 1399, masaccio: 1401,
  piero: 1415, memling: 1430, mantegna: 1431, botticelli: 1445, ghirlandaio: 1448, bosch: 1450,
  leonardo: 1452, durer: 1471, cranach: 1472, michelangelo: 1475, giorgione: 1477, raphael: 1483,
  delsarto: 1486, titian: 1488, correggio: 1489, holbein: 1497, parmigianino: 1503, tintoretto: 1518,
  bruegel: 1525, veronese: 1528, elgreco: 1541, caravaggio: 1571, rubens: 1577, franshals: 1582,
  artemisia: 1593, delatour: 1593, poussin: 1594, velazquez: 1599, vandyck: 1599, lorrain: 1600,
  zurbaran: 1598, ribera: 1591, murillo: 1617, rembrandt: 1606, vermeer: 1632, goya: 1746,
  david: 1748, pissarro: 1830, manet: 1832, degas: 1834, cezanne: 1839, monet: 1840, renoir: 1841,
  gauguin: 1848, vangogh: 1853, seurat: 1859, sorolla: 1863, picasso: 1881, rivera: 1886, frida: 1907,
  // added 2026-08-22
  uccello: 1397, lippi: 1406, bellini: 1430, perugino: 1448, bronzino: 1503, carracci: 1560,
  reni: 1575, tiepolo: 1696, canaletto: 1697, guardi: 1712, friedrich: 1774, turner: 1775,
  delacroix: 1798, zuloaga: 1870, miro: 1893, dali: 1904,
};
const bornOf = slug => BORN[slug] || 9999;

// short label per painter for the selector button (the first name is often wrong — "Ignacio"
// for Zuloaga, "Giovanni" for Bellini/Tiepolo). Falls back to the first word.
const NICK = {
  caravaggio: "Caravaggio", leonardo: "Leonardo", raphael: "Raphael", goya: "Goya",
  velazquez: "Velázquez", botticelli: "Botticelli", giotto: "Giotto", ribera: "Ribera",
  zurbaran: "Zurbarán", masaccio: "Masaccio", titian: "Titian", vermeer: "Vermeer",
  rembrandt: "Rembrandt", rubens: "Rubens", vaneyck: "Van Eyck", bruegel: "Bruegel",
  durer: "Dürer", bosch: "Bosch", fraangelico: "Fra Angelico", piero: "Piero", elgreco: "El Greco",
  poussin: "Poussin", veronese: "Veronese", mantegna: "Mantegna", artemisia: "Artemisia",
  michelangelo: "Michelangelo", tintoretto: "Tintoretto", vandyck: "Van Dyck", franshals: "Hals",
  holbein: "Holbein", david: "David", weyden: "Van der Weyden", giorgione: "Giorgione",
  correggio: "Correggio", parmigianino: "Parmigianino", murillo: "Murillo", cranach: "Cranach",
  duccio: "Duccio", ghirlandaio: "Ghirlandaio", delatour: "La Tour", memling: "Memling",
  delsarto: "Del Sarto", lorrain: "Lorrain", vangogh: "Van Gogh", monet: "Monet", manet: "Manet",
  cezanne: "Cézanne", renoir: "Renoir", degas: "Degas", gauguin: "Gauguin", seurat: "Seurat",
  pissarro: "Pissarro", sorolla: "Sorolla", picasso: "Picasso", frida: "Frida", rivera: "Rivera",
  turner: "Turner", bellini: "Bellini", friedrich: "Friedrich", canaletto: "Canaletto",
  delacroix: "Delacroix", tiepolo: "Tiepolo", uccello: "Uccello", lippi: "Lippi",
  perugino: "Perugino", bronzino: "Bronzino", carracci: "Carracci", reni: "Reni",
  guardi: "Guardi", zuloaga: "Zuloaga", dali: "Dalí", miro: "Miró",
};
const nickOf = p => NICK[p.slug] || (p.name || "").split(" ")[0];
let painterGroupBy = "period";   // "period" | "school"

// Most works are in Europe; open there. The ~12 in the Americas are one zoom-out away.
const map = L.map("map", { zoomControl: true, worldCopyJump: true }).setView([43, 9], 5);
L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png", {
  maxZoom: 19, attribution: "© OpenStreetMap",
}).addTo(map);
requestAnimationFrame(() => map.invalidateSize());
window.addEventListener("resize", () => map.invalidateSize());

// clustering: overlapping venues (e.g. all of Rome) merge at low zoom into one badge
// showing the TOTAL number of works, and split apart as you zoom in.
const cluster = L.markerClusterGroup({
  maxClusterRadius: 44,
  showCoverageOnHover: false,
  spiderfyOnMaxZoom: true,
  iconCreateFunction(c) {
    // aggregate the painter-colour breakdown across all works in the cluster
    const agg = {};
    let works = 0;
    for (const m of c.getAllChildMarkers()) {
      const cc = m.options.colorCounts;
      if (cc) for (const [col, n] of Object.entries(cc)) { agg[col] = (agg[col] || 0) + n; works += n; }
      else works += (m.options.works || 1);
    }
    const size = works >= 25 ? 48 : works >= 10 ? 40 : 32;
    const { style, pie } = pieStyle(agg);
    return L.divIcon({
      html: `<div class="cl${pie ? " pie" : ""}" style="width:${size}px;height:${size}px;${style}"><span class="cl-n">${works}</span></div>`,
      className: "", iconSize: [size, size],
    });
  },
}).addTo(map);

let legendDiv;
const legend = L.control({ position: "bottomleft" });
legend.onAdd = () => { legendDiv = L.DomUtil.create("div", "legend"); return legendDiv; };
legend.addTo(map);
// reflects the current selection: the coloured painters (or a note when too many)
function updateLegend() {
  if (!legendDiv) return;
  const shown = PAINTERS.filter(p => state.painters[p.name] !== false);
  // Only useful when focused on a few painters — hidden by default (all/most selected)
  // so it never covers the map. Appears once you narrow to a handful.
  if (!shown.length || shown.length > 8 || shown.length === PAINTERS.length) {
    legendDiv.style.display = "none"; return;
  }
  legendDiv.style.display = "";
  const rows = shown.map(p => `<span class="le"><span class="k" style="background:${colorFor(p.name)}"></span>${esc(p.name)}</span>`).join("");
  legendDiv.innerHTML = `<div class="row">${rows}` +
    (shown.length > 1 ? `<span class="le"><span class="k" style="background:${MULTI_COLOR}"></span>Several</span>` : "") + `</div>`;
}

let allFeatures = [];   // raw point features from the geojson
const places = [];   // {marker, kind, feats, lat, lon, shown}
const works = [];    // {p (properties), lat, lon, marker} — one per painting, for the side panel
let panelVis = [];   // works currently listed in the panel
const state = { mode: "current", museum: true, church: true, private: true,
                acceptedOnly: true, museumFilter: null, near: null,
                yearMin: -Infinity, yearMax: Infinity, painters: {} };

// museum index (derived from the works): each venue with its painters + work count
const museumIndex = [];
function museumKey(p) { return p.museum_id || `${p.location || ""}|${p.city || ""}`; }
function buildMuseumIndex() {
  const m = new Map();
  for (const f of allFeatures) {
    const p = f.properties;
    if (!p.location) continue;
    const k = museumKey(p);
    if (!m.has(k)) m.set(k, {
      key: k, location: p.location, city: p.city || "", country: p.country || "",
      lat: f.geometry.coordinates[1], lon: f.geometry.coordinates[0], painters: new Set(), count: 0,
    });
    const e = m.get(k); e.painters.add(p.painter); e.count++;
  }
  museumIndex.length = 0;
  museumIndex.push(...[...m.values()].sort((a, b) => b.count - a.count));
}
PAINTERS.forEach(p => { state.painters[p.name] = true; });

function yearNum(p) {
  const m = (p.year || "").match(/1[2-9]\d{2}|20\d{2}/);   // 12xx+ (Giotto onward)
  return m ? +m[0] : null;
}
function inYear(p) {
  const y = yearNum(p);                       // unknown-date works stay visible
  return y == null || (y >= state.yearMin && y <= state.yearMax);
}
function passesAll(p) {
  const kindOk = state.mode === "painted" ? true : state[p.kind || "museum"];   // no venue type on map 2
  const painterOk = state.painters[p.painter] !== false;
  const attrOk = !state.acceptedOnly || ATTR_ACCEPTED.has(p.attribution);
  const museumOk = !state.museumFilter || museumKey(p) === state.museumFilter;
  return painterOk && kindOk && attrOk && museumOk && inYear(p);
}
// active coordinate per map: current location, or where it was painted (map 2)
function activeCoord(f) {
  if (state.mode === "painted") {
    const p = f.properties;
    return (p.creation_lat != null && p.creation_lon != null) ? [p.creation_lon, p.creation_lat] : null;
  }
  return f.geometry.coordinates;
}

function esc(s) {
  return String(s).replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
}

// subtle "?" for a disputed attribution (a scholarly nuance, not an error → not a warning ⚠)
function disputedMark(p) {
  if (!p.attribution || ATTR_ACCEPTED.has(p.attribution)) return "";
  // show WHY when we have a recorded reason, else the generic label
  const why = p.attribution_note || `${p.attribution} attribution`;
  return ` <span class="qm" title="${esc(why)}">?</span>`;
}

// small painter tag: coloured dot + name (works belong to different painters now)
function painterTag(p) {
  if (!p.painter) return "";
  const c = colorFor(p.painter);
  return `<span class="pby"><span class="pdot" style="background:${c}"></span>${esc(p.painter)}</span>`;
}

// colour = painter (red overrides for lost/stolen); dashed ring = holds a disputed work
function pinIcon(colorCounts, n, { disputed = false } = {}) {
  const { style, pie } = pieStyle(colorCounts);   // one painter → solid; several → pie of their colours
  return L.divIcon({
    className: "",
    html: `<div class="pin${pie ? " pie" : ""}${disputed ? " disp" : ""}" style="${style}"><span class="pn">${n}</span></div>`,
    iconSize: [26, 26], iconAnchor: [13, 13], popupAnchor: [0, -14],
  });
}

// "Wikipedia: ES EN IT · Wikidata" — only the languages that actually have an article.
function linksRow(p) {
  const wp = WIKI_LANGS.filter(l => p["wikipedia_" + l]).map(l =>
    `<a class="tag" href="${esc(p["wikipedia_" + l])}" target="_blank" rel="noopener">${l.toUpperCase()}</a>`);
  const parts = [];
  if (wp.length) parts.push(`<span class="lbl">Wikipedia</span>${wp.join("")}`);
  if (p.wikidata) parts.push(`<a class="tag wd" href="${esc(p.wikidata)}" target="_blank" rel="noopener">Wikidata</a>`);
  if (p.wga_url) parts.push(`<a class="tag wga" href="${esc(p.wga_url)}" target="_blank" rel="noopener" title="Web Gallery of Art record">WGA</a>`);
  return parts.join(" ");
}

// Per-field "post-processed" chips are kept OUT of the public card (they singled out
// edited fields and read oddly). Provenance still lives in the data (_overrides); the
// card's Wikipedia/Wikidata links are the consistent, per-work source. Flip to re-enable.
const SHOW_PROVENANCE = false;

// visible provenance line for overridden fields (skip those given in `skip`).
function provLine(p, skip = []) {
  if (!SHOW_PROVENANCE || !p._overrides) return "";
  const rows = Object.entries(p._overrides)
    .filter(([field]) => !skip.includes(field))
    .map(([field, o]) => {
      const src = o.source ? ` · ${esc(o.source)}` : "";
      return `<div class="prov"${o.note ? ` title="${esc(o.note)}"` : ""}>` +
        `✎ ${esc(field)} · post-processed${src}</div>`;
    });
  return rows.join("");
}

// Place record: header (museum · city · country) + one row per work with a thumbnail.
const HEAD_SKIP_CURRENT = ["attribution", "title", "year", "genre", "medium", "dimensions", "image", "creation", "status"];
const HEAD_SKIP_PAINTED = ["attribution", "title", "year", "genre", "medium", "dimensions", "image", "city", "country", "location", "kind", "status"];
const WORK_SKIP = ["city", "country", "location", "kind", "creation"];

function placePopup(feats) {
  const p0 = feats[0].properties;
  const painted = state.mode === "painted";
  const n = feats.length;
  let head;
  if (painted) {
    head = `<div class="hd"><div class="nm">${esc(p0.creation_place || "Unknown")}</div>` +
      `<div class="meta">painted here · ${n} work${n > 1 ? "s" : ""}</div>` +
      `${provLine(p0, HEAD_SKIP_PAINTED)}</div>`;
  } else {
    const kindTxt = KIND_LABEL[p0.kind] || "";
    const where = [p0.city, p0.country].filter(Boolean).join(", ");
    // the venue name is a button → opens this museum in the side list (filters to it)
    head = `<div class="hd"><button type="button" class="nm pop-museum" data-museum="${esc(museumKey(p0))}"` +
      ` title="Show all works of this venue in the list">${esc(p0.location || "Location")}<span class="pm-arrow"> ↗</span></button>` +
      `<div class="meta">${esc(where)}${kindTxt ? ` · ${kindTxt}` : ""} · ${n} work${n > 1 ? "s" : ""}</div>` +
      `${provLine(p0, HEAD_SKIP_CURRENT)}</div>`;
  }

  const items = feats.map(f => {
    const p = f.properties;
    const yr = p.year ? ` <span class="yr">${esc(p.year)}</span>` : "";
    const att = p.attribution && !ATTR_ACCEPTED.has(p.attribution)
      ? ` <span class="tag att">${esc(p.attribution)}</span>` : "";
    const st = p.status && GONE.has(p.status)
      ? ` <span class="tag gone">${esc(STATUS_LABEL[p.status] || p.status)}</span>` : "";
    const factBits = [p.medium, p.dimensions];
    if (painted && p.location) factBits.push(`now in ${p.location}${p.city ? `, ${p.city}` : ""}`);
    const facts = factBits.filter(Boolean).map(esc).join(" · ");
    const factsRow = facts ? `<div class="fx">${facts}</div>` : "";
    const desc = p.summary ? `<div class="ds">${esc(p.summary)}</div>` : "";
    const cap = `${p.title || ""}${p.year ? ` (${p.year})` : ""} — ${p0.location || ""}`;
    const thumb = p.image
      ? `<img class="th" src="${esc(p.image)}" data-full="${esc(fullImage(p.image))}" data-cap="${esc(cap)}" alt="" loading="lazy">`
      : `<span class="th ph"></span>`;
    return `<li>${thumb}<div class="wk">` +
      `<div class="wt">${esc(p.title || "Untitled")}${yr}${att}${st}</div>` +
      `<div class="by">${painterTag(p)}</div>` +
      `${factsRow}${desc}<div class="lk">${linksRow(p)}</div>` +
      `${provLine(p, WORK_SKIP)}</div></li>`;
  }).join("");

  return `<div class="card">${head}<ul class="works">${items}</ul></div>`;
}

function refresh() {
  updateLegend();
  let workCount = 0, shownPlaces = 0;
  const countries = new Set();
  for (const pl of places) {
    const vis = pl.feats.filter(f => passesAll(f.properties));   // works here passing every filter
    if (vis.length) {
      const painted = state.mode === "painted";
      const disputed = vis.some(f => !ATTR_ACCEPTED.has(f.properties.attribution));
      // per-work colour breakdown → the marker (and its cluster) is a solid colour or a pie
      const colorCounts = {};
      for (const f of vis) {
        const c = (!painted && GONE.has(f.properties.status)) ? LOST_COLOR : colorFor(f.properties.painter);
        colorCounts[c] = (colorCounts[c] || 0) + 1;
      }
      pl.marker.options.colorCounts = colorCounts;
      pl.marker.options.works = vis.length;
      pl.marker.setIcon(pinIcon(colorCounts, vis.length, { disputed }));
      pl.marker.setPopupContent(placePopup(vis));
      // hover label: the venue (map 1) or the place it was painted (map 2), + count
      const label = painted ? (vis[0].properties.creation_place || "") : (vis[0].properties.location || "");
      if (label) pl.marker.bindTooltip(`${label} · ${vis.length}`, { direction: "top", offset: [0, -12] });
      if (!pl.shown) { cluster.addLayer(pl.marker); pl.shown = true; }
      shownPlaces++; workCount += vis.length;
      if (vis[0].properties.country) countries.add(vis[0].properties.country);
    } else if (pl.shown) { cluster.removeLayer(pl.marker); pl.shown = false; }
  }
  cluster.refreshClusters();
  document.getElementById("stats").textContent =
    `${workCount} works · ${shownPlaces} locations · ${countries.size} countries`;
  if (state.near) renderNearMe(); else renderPanel();
  if (typeof view !== "undefined" && view.table) renderTable();
}

// group features by place (key = rounded coordinates)
function keyOf(f) {
  const [lon, lat] = f.geometry.coordinates;
  return `${lat.toFixed(5)},${lon.toFixed(5)}`;
}

// (re)build markers for the current mode: group features by their active coordinate
function buildMarkers() {
  cluster.clearLayers();
  places.length = 0; works.length = 0;
  const byPlace = new Map();
  for (const f of allFeatures) {
    const c = activeCoord(f);
    if (!c) continue;                       // e.g. undated work has no creation place
    const k = `${c[1].toFixed(5)},${c[0].toFixed(5)}`;
    if (!byPlace.has(k)) byPlace.set(k, []);
    byPlace.get(k).push(f);
  }
  for (const feats of byPlace.values()) {
    const [lon, lat] = activeCoord(feats[0]);
    const kind = feats[0].properties.kind || "museum";
    const marker = L.marker([lat, lon], { works: feats.length })
      // autoPan:false → opening a popup never scrolls the map out from under you
      .bindPopup("", { maxWidth: 320, minWidth: 240, autoPan: false });
    places.push({ marker, kind, feats, lat, lon, shown: false });
    for (const f of feats) works.push({ p: f.properties, lat, lon, marker });
  }
  refresh();
}

// One bundled file (fast: 1 request, minified, no build-provenance) — fall back to the 72
// per-painter files if the bundle isn't there (dev before running scripts/bundle_data.py).
fetch("atlas/data/all.geojson?v=" + DATA_V)
  .then(r => { if (!r.ok) throw new Error("no bundle"); return r.json(); }).then(gj => [gj])
  .catch(() => Promise.all(PAINTERS.map(p =>
    fetch(p.file + "?v=" + DATA_V).then(r => r.ok ? r.json() : { features: [] }).catch(() => ({ features: [] })))))
  .then(gjs => {
    allFeatures = [];
    gjs.forEach(gj => (gj.features || []).forEach(f => {
      if (f.geometry && f.geometry.type === "Point") allFeatures.push(f);
    }));
    const yrs = allFeatures.map(f => yearNum(f.properties)).filter(v => v != null);
    const [lo, hi] = robustBounds(yrs);   // ignore sparse mis-dated outliers (e.g. copies dated 1900)
    buildTimeline(lo, hi);                 // sets state.yearMin/Max
    buildMuseumIndex();
    buildPainterSelect();
    applyHash();                       // #caravaggio or #leonardo/painted → preset
    buildMarkers();
    deepLink();                        // ?w=<qid> opens that painting's ficha; ?m=<id> its museum
    map.on("moveend", renderPanel);
    // clicking the venue name at the top of a popup → open that museum in the side list
    map.on("popupopen", e => {
      // On phones a marker popup is taller than the small map and its header/close get cut
      // off the top. Route it into a fixed bottom sheet instead — always fully visible.
      if (isMobile()) { openSheet(e.popup.getContent()); map.closePopup(e.popup); return; }
      const b = e.popup.getElement() && e.popup.getElement().querySelector(".pop-museum");
      if (b) b.addEventListener("click", () => { map.closePopup(); selectMuseum(b.dataset.museum); });
    });
    map.on("click", closeSheet);   // tapping the map background dismisses the sheet
    window.addEventListener("hashchange", () => { applyHash(); buildMarkers(); });
  })
  .catch(err => {
    console.error("Could not load painter data:", err);
    document.getElementById("stats").textContent = "no data yet — generate the geojson files";
  });

// slider bounds. The low end is the true earliest year (early works are genuine, just
// sparse). The high end ignores isolated outliers — mis-dated copies (e.g. a Raphael
// "painting" dated 1900) sit alone, so we keep the largest year that has at least MIN
// works within a W-year window below it.
function robustBounds(years) {
  const s = years.slice().sort((a, b) => a - b), W = 15, MIN = 5;
  let hi = s[s.length - 1];
  for (let i = s.length - 1; i >= 0; i--) {
    if (s.filter(v => v >= s[i] - W && v <= s[i]).length >= MIN) { hi = s[i]; break; }
  }
  return [s[0], hi];
}

// hash presets: #caravaggio (focus one painter) · #leonardo/painted (+ map 2)
function applyHash() {
  const parts = location.hash.replace(/^#/, "").split("/").filter(Boolean);
  const focus = PAINTERS.find(p => p.slug === parts[0]);
  PAINTERS.forEach(p => { state.painters[p.name] = focus ? p === focus : true; });
  if (document.getElementById("painters-btn")) { updatePainterBtn(); renderPainterList(); }
  state.mode = parts.includes("painted") ? "painted" : "current";
  document.querySelectorAll(".mode-btn").forEach(b => b.classList.toggle("active", b.dataset.mode === state.mode));
  document.body.classList.toggle("mode-painted", state.mode === "painted");
}

// painter selector: a button + a searchable checklist popover (scales to many painters)
function buildPainterSelect() {
  const box = document.getElementById("painters");
  if (!box) return;
  box.innerHTML =
    `<button id="painters-btn" class="chip" type="button" aria-expanded="false">All painters ▾</button>` +
    `<div id="painters-pop" class="pop" hidden>` +
    `<input id="painters-search" class="pop-search" placeholder="Search painters or museums…" autocomplete="off">` +
    `<div class="pop-actions">` +
    `<span id="grp-toggle"><button type="button" data-grp="period" class="active">Period</button>` +
    `<button type="button" data-grp="school">School</button></span>` +
    `<button type="button" data-act="all">All</button>` +
    `<button type="button" data-act="none">None</button></div>` +
    `<ul id="painters-list" class="pop-list"></ul></div>`;

  const btn = document.getElementById("painters-btn");
  const pop = document.getElementById("painters-pop");
  const search = document.getElementById("painters-search");

  btn.addEventListener("click", () => {
    const open = pop.hidden;
    pop.hidden = !open; btn.setAttribute("aria-expanded", String(open));
    if (open) { search.value = ""; renderPainterList(); search.focus(); }
  });
  document.addEventListener("click", e => {
    if (!pop.hidden && !box.contains(e.target)) { pop.hidden = true; btn.setAttribute("aria-expanded", "false"); }
  });
  document.addEventListener("keydown", e => { if (e.key === "Escape") pop.hidden = true; });
  search.addEventListener("input", renderPainterList);
  pop.querySelectorAll("[data-grp]").forEach(b => b.addEventListener("click", () => {
    painterGroupBy = b.dataset.grp;
    pop.querySelectorAll("[data-grp]").forEach(x => x.classList.toggle("active", x === b));
    renderPainterList();
  }));
  pop.querySelectorAll("[data-act]").forEach(b => b.addEventListener("click", () => {
    const on = b.dataset.act === "all";
    PAINTERS.forEach(p => { state.painters[p.name] = on; });
    renderPainterList(); updatePainterBtn(); refresh();
  }));
  renderPainterList(); updatePainterBtn();
}

// unified search: painters (toggle) + museums (filter to that venue)
const deacc = s => (s || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
function renderPainterList() {
  const q = deacc((document.getElementById("painters-search")?.value || "").trim());  // accent-insensitive
  const ul = document.getElementById("painters-list");
  let html = "";

  const museumRow = m =>
    `<li class="mrow" data-museum="${esc(m.key)}"><span class="micon">🏛</span><div>` +
    `<div class="mname">${esc(m.location)}</div>` +
    `<div class="msub">${esc([m.city, m.country].filter(Boolean).join(", "))} · ${m.count} works · ` +
    `${m.painters.size} painter${m.painters.size > 1 ? "s" : ""}</div></div></li>`;

  if (q) {   // when searching: matching museums first (there are hundreds otherwise)
    const mus = museumIndex.filter(m =>
      deacc(m.location).includes(q) || deacc(m.city).includes(q)).slice(0, 8);
    if (mus.length) html += `<li class="pop-h">Museums</li>` + mus.map(museumRow).join("");
  }

  const painterRow = p => {
    const on = state.painters[p.name] !== false;
    const yr = BORN[p.slug] ? ` <span class="pyr">b. ${BORN[p.slug]}</span>` : "";
    return `<li class="prow"><label><input type="checkbox" data-painter="${esc(p.name)}"${on ? " checked" : ""}>` +
      `<span class="sw" style="background:${on ? colorFor(p.name) : "#cfc7bd"}"></span>${esc(p.name)}${yr}</label>` +
      `<button type="button" class="only" data-only="${esc(p.name)}">only</button></li>`;
  };
  const pnt = PAINTERS.filter(p => deacc(p.name).includes(q) || deacc(nickOf(p)).includes(q));
  if (pnt.length) {
    if (q) {                                   // searching → flat list under one header (if mixed with museums)
      if (html) html += `<li class="pop-h">Painters</li>`;
      html += pnt.map(painterRow).join("");
    } else {                                   // idle → grouped by the active axis (period or school)
      const groups = painterGroupBy === "school" ? SCHOOLS : ERAS;
      const keysOf = painterGroupBy === "school" ? schoolsOf : erasOf;
      for (const g of groups) {
        const inGroup = pnt.filter(p => keysOf(p.slug).includes(g.key))
          .sort((a, z) => bornOf(a.slug) - bornOf(z.slug));   // chronological within the group
        if (!inGroup.length) continue;
        const allOn = inGroup.every(p => state.painters[p.name] !== false);
        html += `<li class="pop-h grp">` +
          `<label class="grp-tick" title="Tick/untick the whole ${esc(g.label)} group">` +
          `<input type="checkbox" data-grp-tick="${esc(g.key)}"${allOn ? " checked" : ""}>` +
          `<span>${esc(g.label)}</span></label>` +
          `<button type="button" class="grp-only" data-grp-only="${esc(g.key)}" ` +
          `title="Show only the ${esc(g.label)} painters">only</button></li>` +
          inGroup.map(painterRow).join("");
      }
    }
  }

  if (!q && museumIndex.length) {   // idle state: surface the museum search
    html += `<li class="pop-h">Popular museums · type to search all ${museumIndex.length}</li>` +
      museumIndex.slice(0, 6).map(museumRow).join("");
  }
  ul.innerHTML = html || `<li class="pop-empty">no match</li>`;

  ul.querySelectorAll("input[data-painter]").forEach(cb => cb.addEventListener("change", () => {
    state.painters[cb.dataset.painter] = cb.checked;
    refresh(); updatePainterBtn(); renderPainterList();
  }));
  // "only" (Kayak-style): deselect everyone, keep just this painter
  ul.querySelectorAll("button[data-only]").forEach(b => b.addEventListener("click", e => {
    e.preventDefault(); e.stopPropagation();
    PAINTERS.forEach(p => { state.painters[p.name] = p.name === b.dataset.only; });
    refresh(); updatePainterBtn(); renderPainterList();
  }));
  // group "only": isolate a whole period/school (uses the active grouping axis)
  ul.querySelectorAll("button[data-grp-only]").forEach(b => b.addEventListener("click", e => {
    e.preventDefault(); e.stopPropagation();
    const gk = b.dataset.grpOnly;
    const keysOf = painterGroupBy === "school" ? schoolsOf : erasOf;
    PAINTERS.forEach(p => { state.painters[p.name] = keysOf(p.slug).includes(gk); });
    refresh(); updatePainterBtn(); renderPainterList();
  }));
  // group tick: add/remove a whole period/school without disturbing the others
  ul.querySelectorAll("input[data-grp-tick]").forEach(cb => cb.addEventListener("change", () => {
    const gk = cb.dataset.grpTick;
    const keysOf = painterGroupBy === "school" ? schoolsOf : erasOf;
    PAINTERS.forEach(p => { if (keysOf(p.slug).includes(gk)) state.painters[p.name] = cb.checked; });
    refresh(); updatePainterBtn(); renderPainterList();
  }));
  ul.querySelectorAll(".mrow").forEach(row => row.addEventListener("click", () => selectMuseum(row.dataset.museum)));
}

function selectMuseum(key) {
  state.museumFilter = key;
  const mu = museumIndex.find(m => m.key === key);
  const pop = document.getElementById("painters-pop");
  pop.hidden = true; document.getElementById("painters-btn").setAttribute("aria-expanded", "false");
  if (mu) { if (view.table) setTableView(false); map.setView([mu.lat, mu.lon], 14); }
  history.replaceState(null, "", location.pathname + "?m=" + encodeURIComponent(key) + location.hash);
  renderMuseumChip(); refresh();
}
function clearMuseum() {
  state.museumFilter = null;
  if (new URLSearchParams(location.search).has("m")) history.replaceState(null, "", location.pathname + location.hash);
  renderMuseumChip(); refresh();
}
function renderMuseumChip() {
  let el = document.getElementById("museum-chip");
  if (!state.museumFilter) { if (el) el.remove(); return; }
  const mu = museumIndex.find(m => m.key === state.museumFilter);
  if (!el) {
    el = document.createElement("span"); el.id = "museum-chip"; el.className = "chip mchip";
    document.getElementById("painters").after(el);
  }
  el.innerHTML = `🏛 ${esc(mu ? mu.location : "Museum")}${mu && mu.city ? ", " + esc(mu.city) : ""} ` +
    `<button type="button" aria-label="Clear museum">✕</button>`;
  el.querySelector("button").addEventListener("click", clearMuseum);
}

function updatePainterBtn() {
  const btn = document.getElementById("painters-btn");
  const sel = PAINTERS.filter(p => state.painters[p.name] !== false);
  const label = sel.length === PAINTERS.length ? `All ${PAINTERS.length} painters`
    : sel.length === 0 ? "No painters"
      : sel.length <= 3 ? sel.map(nickOf).join(", ")
        : `${sel.length} painters`;
  btn.textContent = "🎨 " + label + " ▾";
}

// filters
document.querySelectorAll('.filters input[data-kind]').forEach(cb => {
  cb.addEventListener("change", () => { state[cb.dataset.kind] = cb.checked; refresh(); });
});
document.getElementById("accepted-only").addEventListener("change", e => {
  state.acceptedOnly = e.target.checked; refresh();
});

// ── two top-level views: "Map & list" (map + side list, always together) vs "Table" ──
// The map's own options (Now in / Painted in) live under the map view — they don't apply to
// the table. The side list always accompanies the map, so there's no separate list toggle.
const view = { map: true, panel: true };
function setView() {
  document.body.classList.toggle("hide-map", !view.map);
  document.body.classList.toggle("hide-panel", !view.panel);
  if (view.map) setTimeout(() => map.invalidateSize(), 60);
  if (state.near) renderNearMe(); else renderPanel();
}

// ── database view: WORKS or MUSEUMS as a sortable, filterable, exportable table ──
const TABLE_COLS = [
  { key: "img", label: "", sortable: false },
  { key: "painter", label: "Painter" },
  { key: "title", label: "Title" },
  { key: "year", label: "Year", num: true },
  { key: "medium", label: "Technique" },
  { key: "dimensions", label: "Size" },
  { key: "attribution", label: "Attribution" },
  { key: "location", label: "Museum / venue" },
  { key: "city", label: "City" },
  { key: "country", label: "Country" },
  { key: "links", label: "Links", sortable: false },
];
const MUSEUM_COLS = [
  { key: "location", label: "Museum / venue" },
  { key: "city", label: "City" },
  { key: "country", label: "Country" },
  { key: "count", label: "Works", num: true },
  { key: "npainters", label: "Painters", num: true },
];
let tableMode = "works";
let tableSort = { key: "painter", dir: 1 };
let museumSort = { key: "count", dir: -1 };
let tableRowCache = [];
view.table = false;

// tables respect the painter / attribution / year / museum filters (not the map-only kind toggles)
function tablePass(p) {
  return state.painters[p.painter] !== false
    && (!state.acceptedOnly || ATTR_ACCEPTED.has(p.attribution))
    && (!state.museumFilter || museumKey(p) === state.museumFilter)
    && inYear(p);
}
function tableSearch() { return (document.getElementById("table-search")?.value || "").toLowerCase().trim(); }
function tableRows() {
  const q = tableSearch();
  let rows = allFeatures.map(f => f.properties).filter(tablePass);
  if (q) rows = rows.filter(p => [p.painter, p.title, p.location, p.city, p.country, p.year, p.medium]
    .some(v => (v || "").toString().toLowerCase().includes(q)));
  const k = tableSort.key, num = TABLE_COLS.find(c => c.key === k)?.num;
  rows.sort((a, b) => {
    const va = num ? (yearNum(a) ?? -1e9) : (a[k] || "").toString().toLowerCase();
    const vb = num ? (yearNum(b) ?? -1e9) : (b[k] || "").toString().toLowerCase();
    return (va < vb ? -1 : va > vb ? 1 : 0) * tableSort.dir;
  });
  return rows;
}
// aggregate the same filtered works by venue → one row per museum
function museumRows() {
  const q = tableSearch();
  const m = new Map();
  for (const f of allFeatures) {
    const p = f.properties;
    if (!p.location || !tablePass(p)) continue;
    const k = museumKey(p);
    if (!m.has(k)) m.set(k, { key: k, location: p.location, city: p.city || "", country: p.country || "",
      lat: f.geometry.coordinates[1], lon: f.geometry.coordinates[0], painters: new Set(), count: 0 });
    const e = m.get(k); e.painters.add(p.painter); e.count++;
  }
  let rows = [...m.values()].map(r => (r.npainters = r.painters.size, r));
  if (q) rows = rows.filter(r => [r.location, r.city, r.country].some(v => (v || "").toLowerCase().includes(q)));
  const k = museumSort.key, num = MUSEUM_COLS.find(c => c.key === k)?.num;
  rows.sort((a, b) => {
    const va = num ? (a[k] || 0) : (a[k] || "").toLowerCase();
    const vb = num ? (b[k] || 0) : (b[k] || "").toLowerCase();
    return (va < vb ? -1 : va > vb ? 1 : 0) * museumSort.dir;
  });
  return rows;
}
function headHTML(cols, sort) {
  return "<tr>" + cols.map(c => {
    if (c.sortable === false) return `<th class="th-${c.key}">${esc(c.label)}</th>`;
    const arrow = sort.key === c.key ? (sort.dir === 1 ? " ▲" : " ▼") : "";
    return `<th class="th-${c.key} sortable" data-key="${c.key}">${esc(c.label)}<span class="ar">${arrow}</span></th>`;
  }).join("") + "</tr>";
}
function wireSort(thead, sort) {
  thead.querySelectorAll("th.sortable").forEach(th => th.addEventListener("click", () => {
    const k = th.dataset.key;
    if (sort.key === k) sort.dir *= -1; else { sort.key = k; sort.dir = 1; }
    renderTable();
  }));
}
function renderTable() {
  const isWorks = tableMode === "works";
  document.getElementById("table-view").style.display = isWorks ? "" : "none";   // gallery toggle: Works only
  const tbl = document.getElementById("works-table"), gal = document.getElementById("table-gallery");
  if (isWorks && tableGallery) return renderWorksGallery();
  tbl.hidden = false; gal.hidden = true;
  return isWorks ? renderWorksTable() : renderMuseumsTable();
}

function renderWorksTable() {
  const thead = document.querySelector("#works-table thead");
  const tbody = document.querySelector("#works-table tbody");
  if (!thead) return;
  thead.innerHTML = headHTML(TABLE_COLS, tableSort);
  const rows = tableRows();
  tableRowCache = rows;
  document.getElementById("table-count").textContent =
    `${rows.length.toLocaleString()} work${rows.length === 1 ? "" : "s"}`;
  tbody.innerHTML = rows.map((p, i) => {
    const thumb = p.image
      ? `<img class="tth" src="${esc(p.image)}" data-full="${esc(fullImage(p.image))}" data-cap="${esc((p.title || "") + " — " + (p.location || ""))}" alt="" loading="lazy">`
      : `<span class="tth ph"></span>`;
    const att = p.attribution && !ATTR_ACCEPTED.has(p.attribution)
      ? `<span class="tag att">${esc(p.attribution)}</span>` : esc(p.attribution || "");
    return `<tr data-ri="${i}">` +
      `<td class="c-img">${thumb}</td>` +
      `<td class="c-painter"><span class="sw" style="background:${colorFor(p.painter)}"></span>${esc(p.painter)}</td>` +
      `<td class="c-title">${esc(p.title || "Untitled")}</td>` +
      `<td class="c-year">${esc(p.year || "")}</td>` +
      `<td class="c-medium">${esc(p.medium || "")}</td>` +
      `<td class="c-dim">${esc(p.dimensions || "")}</td>` +
      `<td class="c-attr">${att}</td>` +
      `<td class="c-loc">${esc(p.location || "")}</td>` +
      `<td class="c-city">${esc(p.city || "")}</td>` +
      `<td class="c-country">${esc(p.country || "")}</td>` +
      `<td class="c-links">${linksRow(p)}</td>` +
      "</tr>";
  }).join("");
  wireSort(thead, tableSort);
  tbody.querySelectorAll(".tth[data-full]").forEach(img => img.addEventListener("click", () =>
    openLightbox(img.dataset.full, img.dataset.cap)));
  tbody.querySelectorAll("tr[data-ri]").forEach(tr => tr.addEventListener("click", e => {
    if (e.target.closest("a, img")) return;
    const p = tableRowCache[+tr.dataset.ri];
    const w = p && works.find(w => w.p === p);
    if (!w) return;
    setTableView(false);
    if (!view.map) { view.map = true; setView(); }
    setTimeout(() => { map.setView([w.lat, w.lon], Math.max(map.getZoom(), 13));
      cluster.zoomToShowLayer(w.marker, () => w.marker.openPopup()); }, 80);
  }));
}

function renderMuseumsTable() {
  const thead = document.querySelector("#works-table thead");
  const tbody = document.querySelector("#works-table tbody");
  if (!thead) return;
  thead.innerHTML = headHTML(MUSEUM_COLS, museumSort);
  const rows = museumRows();
  document.getElementById("table-count").textContent =
    `${rows.length.toLocaleString()} museum${rows.length === 1 ? "" : "s"}`;
  tbody.innerHTML = rows.map(r =>
    `<tr data-rk="${esc(r.key)}">` +
    `<td class="c-title">🏛 ${esc(r.location)}</td>` +
    `<td class="c-city">${esc(r.city)}</td>` +
    `<td class="c-country">${esc(r.country)}</td>` +
    `<td class="c-num">${r.count}</td>` +
    `<td class="c-num">${r.npainters}</td>` +
    "</tr>").join("");
  wireSort(thead, museumSort);
  tbody.querySelectorAll("tr[data-rk]").forEach(tr => tr.addEventListener("click", () => {
    setTableView(false);
    if (!view.map) { view.map = true; setView(); }
    setTimeout(() => selectMuseum(tr.dataset.rk), 80);
  }));
}

// ── Works table in gallery mode: the same tiles as the map panel, streamed with lazy images ──
let tableGallery = true, tGalVis = [], tGalRows = [], tGalCursor = 0;   // Pictures grid by default
const TGAL_CHUNK = 60;
function tGalAppend() {
  const g = document.getElementById("table-gallery");
  const end = Math.min(tGalCursor + TGAL_CHUNK, tGalRows.length);
  let html = "";
  for (; tGalCursor < end; tGalCursor++) html += tileHTML({ p: tGalRows[tGalCursor] }, tGalVis);
  g.insertAdjacentHTML("beforeend", html);
}
function renderWorksGallery() {
  document.getElementById("works-table").hidden = true;
  const g = document.getElementById("table-gallery"); g.hidden = false;
  tGalRows = tableRows();
  document.getElementById("table-count").textContent =
    `${tGalRows.length.toLocaleString()} work${tGalRows.length === 1 ? "" : "s"}`;
  tGalVis = []; tGalCursor = 0; g.innerHTML = "";
  g.style.setProperty("--thumb", document.getElementById("tv-thumb").value + "px");
  tGalAppend();
}
(function wireTableView() {
  const slider = document.getElementById("tv-thumb");
  const setMode = on => {
    tableGallery = on;
    document.getElementById("tv-grid").classList.toggle("active", on);
    document.getElementById("tv-list").classList.toggle("active", !on);
    slider.hidden = !on;
    if (view.table && tableMode === "works") renderTable();
  };
  document.getElementById("tv-list").addEventListener("click", () => setMode(false));
  document.getElementById("tv-grid").addEventListener("click", () => setMode(true));
  slider.addEventListener("input", () =>
    document.getElementById("table-gallery").style.setProperty("--thumb", slider.value + "px"));
  document.getElementById("table-wrap").addEventListener("scroll", e => {
    const el = e.target;
    if (tableGallery && tableMode === "works" && tGalCursor < tGalRows.length &&
        el.scrollTop + el.clientHeight >= el.scrollHeight - 700) tGalAppend();
  });
  document.getElementById("table-gallery").addEventListener("click", e => {
    const sh = e.target.closest(".gshare");
    if (sh) { e.stopPropagation(); shareWork(tGalVis[+sh.dataset.i].p); return; }   // 🔗 → share
    if (e.target.closest("img.th")) return;               // image → lightbox (global handler)
    const cell = e.target.closest(".gcell");
    if (cell) openWorkCard(tGalVis[+cell.dataset.i]);      // caption → the work ficha
  });
})();

function setTableView(on) {
  view.table = on;
  if (on) {                                   // always land on the Works tab
    tableMode = "works";
    document.querySelectorAll("#table-tabs .ttab").forEach(x => x.classList.toggle("active", x.dataset.tmode === "works"));
  } else {                                     // back to the map view → map + list together
    view.map = true; view.panel = true;
  }
  document.body.classList.toggle("show-table", on);
  document.getElementById("v-table").classList.toggle("active", on);
  document.getElementById("v-mapview").classList.toggle("active", !on);
  document.getElementById("mapopts").hidden = on;      // Now in / Painted in only apply to the map
  document.getElementById("table").hidden = !on;
  document.getElementById("main").hidden = on;
  if (on) renderTable();
  else setView();
}
document.getElementById("v-table").addEventListener("click", () => setTableView(true));
document.getElementById("v-mapview").addEventListener("click", () => setTableView(false));
document.getElementById("table-search").addEventListener("input", renderTable);
document.querySelectorAll("#table-tabs .ttab").forEach(b => b.addEventListener("click", () => {
  tableMode = b.dataset.tmode;
  document.querySelectorAll("#table-tabs .ttab").forEach(x => x.classList.toggle("active", x === b));
  document.getElementById("table-search").value = "";
  document.getElementById("table-wrap").scrollTop = 0;
  renderTable();
}));

// ── map mode: "where they are today" (venues) vs "where they were painted" (cities) ──
document.querySelectorAll(".mode-btn").forEach(btn => {
  btn.addEventListener("click", () => {
    if (state.mode === btn.dataset.mode) return;
    state.mode = btn.dataset.mode;
    document.querySelectorAll(".mode-btn").forEach(b => b.classList.toggle("active", b === btn));
    document.body.classList.toggle("mode-painted", state.mode === "painted");
    if (nearestLine) { map.removeLayer(nearestLine); nearestLine = null; }
    buildMarkers();   // regroup by the active coordinate + refresh
  });
});

// ── time slider: filter the map + panel by year of creation (dual-handle range) ──
function buildTimeline(min, max) {
  const lo = document.getElementById("tl-min");
  const hi = document.getElementById("tl-max");
  const label = document.getElementById("tl-label");
  const fill = document.getElementById("tl-fill");
  lo.min = hi.min = min; lo.max = hi.max = max;
  lo.value = min; hi.value = max;
  state.yearMin = min; state.yearMax = max;

  const paint = () => {
    const span = max - min || 1;
    const a = (state.yearMin - min) / span * 100;
    const b = (state.yearMax - min) / span * 100;
    fill.style.left = a + "%"; fill.style.right = (100 - b) + "%";
    label.textContent = state.yearMin === state.yearMax ? `${state.yearMin}` : `${state.yearMin}–${state.yearMax}`;
  };
  const update = () => {
    let a = +lo.value, b = +hi.value;
    if (a > b) { if (document.activeElement === lo) { b = a; hi.value = b; } else { a = b; lo.value = a; } }
    state.yearMin = a; state.yearMax = b;
    paint(); refresh();
  };
  lo.addEventListener("input", update);
  hi.addEventListener("input", update);
  paint();
}

// ── side panel: the works currently within the map viewport, grouped by venue ──
// Infinite scroll: render the list in chunks and append more as the user nears the bottom.
// Only a few thumbnails are ever near the viewport, so this stays smooth on mobile while
// still reaching every work — nothing is dropped. Lazy <img> means only visible thumbs fetch.
const PANEL_CHUNK = 80;
let panelQueue = [];    // flat render plan: {grp} headers and {w} work rows, in display order
let panelCursor = 0;
let panelIO = null;
let panelMode = "list";   // "list" | "gallery" (thumbnail grid)

// gallery tile — lazy thumbnail (click → lightbox) + caption (click → the work "ficha").
// `vis` is the index array the caption click resolves against (panelVis or the table's own).
function tileHTML(w, vis) {
  const i = vis.length; vis.push(w);
  const p = w.p;
  const cap = `${p.title || ""}${p.year ? ` (${p.year})` : ""} — ${p.location || ""}`;
  const img = p.image
    ? `<img class="th" src="${esc(p.image)}" data-full="${esc(fullImage(p.image))}" data-cap="${esc(cap)}" alt="" loading="lazy">`
    : `<span class="th ph"></span>`;
  const share = p.qid ? `<button class="gshare" data-i="${i}" title="Share this painting" aria-label="Share">🔗</button>` : "";
  return `<li class="gcell" data-i="${i}" title="${esc(cap)}">${img}${share}<div class="gmeta">` +
    `<div class="gm1">${esc(p.painter)}${p.year ? ` <span class="gy">· ${esc(p.year)}</span>` : ""}</div>` +
    (p.location ? `<div class="gm2">${esc(p.location)}${p.city ? `, ${esc(p.city)}` : ""}</div>` : "") +
    `</div></li>`;
}
function panelCellHTML(w) { return tileHTML(w, panelVis); }

function panelRowHTML(w) {
  const i = panelVis.length; panelVis.push(w);
  const p = w.p;
  const cap = `${p.title || ""}${p.year ? ` (${p.year})` : ""} — ${p.location || ""}`;
  const thumb = p.image
    ? `<img class="th" src="${esc(p.image)}" data-full="${esc(fullImage(p.image))}" data-cap="${esc(cap)}" alt="" loading="lazy">`
    : `<span class="th"></span>`;
  return `<li data-i="${i}">${thumb}<div>` +
    `<div class="wt">${esc(p.title || "Untitled")}${p.year ? ` <span class="sub">${esc(p.year)}</span>` : ""}${disputedMark(p)}</div>` +
    `<div class="sub">${painterTag(p)}${p.medium ? " · " + esc(p.medium) : ""}</div></div></li>`;
}

function appendPanelChunk() {
  const ul = document.getElementById("worklist");
  const oldSentinel = ul.querySelector(".sentinel");
  if (oldSentinel) oldSentinel.remove();
  const end = Math.min(panelCursor + PANEL_CHUNK, panelQueue.length);
  let html = "";
  for (; panelCursor < end; panelCursor++) {
    const e = panelQueue[panelCursor];
    if (e.grp) {
      if (panelMode === "gallery") continue;   // gallery is a flat grid — museum is on each tile
      html += `<li class="grp"><span>${esc(e.grp.location)}${e.grp.city ? ` · ${esc(e.grp.city)}` : ""}</span>` +
        `<span class="n">${e.grp.count}</span></li>`;
    } else {
      html += panelMode === "gallery" ? panelCellHTML(e.w) : panelRowHTML(e.w);
    }
  }
  ul.insertAdjacentHTML("beforeend", html);
  if (panelCursor < panelQueue.length) {           // more to come → sentinel + observe
    ul.insertAdjacentHTML("beforeend", `<li class="sentinel" aria-hidden="true"></li>`);
    const s = ul.querySelector(".sentinel");
    if (!panelIO) panelIO = new IntersectionObserver(
      es => { if (es.some(x => x.isIntersecting)) appendPanelChunk(); }, { rootMargin: "400px" });
    else panelIO.disconnect();
    panelIO.observe(s);
  } else if (panelIO) { panelIO.disconnect(); }
}

function renderPanel() {
  if (state.near) return;                       // near-me mode owns the side panel (renderNearMe)
  if (panelIO) panelIO.disconnect();
  const bounded = view.map;                    // when the map is hidden, list ALL works (no bounds)
  const b = bounded ? map.getBounds() : null;
  const vis = works.filter(w => passesAll(w.p) && (!bounded || b.contains([w.lat, w.lon])));

  // group by the active place (venue on map 1, creation city on map 2)
  const painted = state.mode === "painted";
  const groups = new Map();
  for (const w of vis) {
    const k = `${w.lat.toFixed(5)},${w.lon.toFixed(5)}`;
    if (!groups.has(k)) groups.set(k, {
      location: painted ? (w.p.creation_place || "Unknown") : (w.p.location || "Location"),
      city: painted ? "" : (w.p.city || ""), items: [],
    });
    groups.get(k).items.push(w);
  }
  const ordered = [...groups.values()].sort((a, z) =>
    (a.city || "zzz").localeCompare(z.city || "zzz") || a.location.localeCompare(z.location));

  document.getElementById("panel-head").textContent =
    `${vis.length} work${vis.length === 1 ? "" : "s"}${bounded ? " in view" : ""}`;

  const ul = document.getElementById("worklist");
  panelVis = [];
  if (!vis.length) {
    ul.innerHTML = `<li class="empty">Pan or zoom the map — the works in view are listed here.</li>`;
    return;
  }
  // flatten to a render plan, then stream it in chunks
  panelQueue = [];
  for (const g of ordered) {
    g.items.sort((a, z) => (yearNum(a.p) || 9999) - (yearNum(z.p) || 9999));
    panelQueue.push({ grp: { location: g.location, city: g.city, count: g.items.length } });
    for (const w of g.items) panelQueue.push({ w });
  }
  panelCursor = 0;
  ul.innerHTML = "";
  appendPanelChunk();
}

document.getElementById("worklist").addEventListener("click", e => {
  const sh = e.target.closest(".gshare");
  if (sh) { e.stopPropagation(); shareWork(panelVis[+sh.dataset.i].p); return; }   // 🔗 → share
  if (e.target.closest("img.th")) return;          // thumbnail → lightbox (handled below)
  const cell = e.target.closest(".gcell");
  if (cell) { openWorkCard(panelVis[+cell.dataset.i]); return; }   // gallery caption → the work ficha
  const li = e.target.closest("li[data-i]");
  if (!li) return;
  const w = panelVis[+li.dataset.i];
  if (!w) return;
  const go = () => {
    map.setView([w.lat, w.lon], Math.max(map.getZoom(), 13));
    cluster.zoomToShowLayer(w.marker, () => w.marker.openPopup());
  };
  if (!view.map) { view.map = true; setView(); setTimeout(go, 120); } else go();
});

// ── panel view: list vs gallery (thumbnail grid) + a size slider ──
(function wirePanelView() {
  const ul = document.getElementById("worklist");
  const slider = document.getElementById("thumb-size");
  const setMode = m => {
    panelMode = m;
    ul.classList.toggle("gallery", m === "gallery");
    document.getElementById("pv-list").classList.toggle("active", m === "list");
    document.getElementById("pv-grid").classList.toggle("active", m === "gallery");
    slider.hidden = m !== "gallery";
    if (!state.near) renderPanel();               // re-render the same in-view works in the new mode
  };
  document.getElementById("pv-list").addEventListener("click", () => setMode("list"));
  document.getElementById("pv-grid").addEventListener("click", () => setMode("gallery"));
  const applySize = () => ul.style.setProperty("--thumb", slider.value + "px");
  slider.addEventListener("input", applySize);
  applySize();
  // Reliable infinite-scroll trigger: append the next chunk when the scroll container nears the
  // bottom. Covers both scrollers (#panel with the map, #main when the map is hidden) and backs
  // up the IntersectionObserver, which is flaky with nested scroll containers.
  ["panel", "main"].forEach(id => {
    const el = document.getElementById(id);
    if (el) el.addEventListener("scroll", () => {
      if (!state.near && panelCursor < panelQueue.length &&
          el.scrollTop + el.clientHeight >= el.scrollHeight - 700) appendPanelChunk();
    });
  });
})();

// ── draggable panel width (desktop): a splitter between the map and the side panel ──
(function wirePanelResize() {
  const handle = document.getElementById("panel-resize");
  if (!handle) return;
  const MIN = 240, MAX = 720, root = document.documentElement;
  const saved = parseInt(localStorage.getItem("atlasPanelW") || "", 10);
  if (saved >= MIN && saved <= MAX) root.style.setProperty("--panel-w", saved + "px");
  let dragging = false, raf = 0;
  const onMove = e => {
    if (!dragging) return;
    const r = document.getElementById("main").getBoundingClientRect();
    const w = Math.max(MIN, Math.min(MAX, Math.round(r.right - e.clientX)));
    root.style.setProperty("--panel-w", w + "px");
    if (!raf) raf = requestAnimationFrame(() => { raf = 0; if (typeof map !== "undefined") map.invalidateSize(); });
  };
  handle.addEventListener("mousedown", e => { dragging = true; document.body.classList.add("resizing"); e.preventDefault(); });
  window.addEventListener("mousemove", onMove);
  window.addEventListener("mouseup", () => {
    if (!dragging) return;
    dragging = false; document.body.classList.remove("resizing");
    const w = parseInt(root.style.getPropertyValue("--panel-w"), 10);
    if (w) localStorage.setItem("atlasPanelW", w);
    if (typeof map !== "undefined") map.invalidateSize();
  });
})();

// ── lightbox: the painting at full size ──
function fullImage(thumbUrl) {
  if (!thumbUrl) return "";
  return /width=\d+/.test(thumbUrl) ? thumbUrl.replace(/width=\d+/, "width=1600") : thumbUrl;
}
// Every image is hosted on Wikimedia Commons (Special:FilePath or upload.wikimedia.org).
// Derive the file description page so the viewer can see the actual licence — we credit
// the source rather than asserting a licence per file.
function commonsPage(url) {
  if (!url) return "";
  const m = url.match(/Special:FilePath\/([^?]+)/);
  let name;
  if (m) { name = m[1]; }
  else {
    const parts = url.split("?")[0].split("/");
    name = url.includes("/thumb/") ? parts[parts.length - 2] : parts[parts.length - 1];
  }
  return name ? "https://commons.wikimedia.org/wiki/File:" + name : "";
}
const lb = document.getElementById("lightbox");
function openLightbox(url, cap) {
  document.getElementById("lb-img").src = url;
  const page = commonsPage(url);
  const credit = page
    ? `<a class="lb-credit" href="${esc(page)}" target="_blank" rel="noopener">Wikimedia Commons — licence ↗</a>`
    : "";
  document.getElementById("lb-cap").innerHTML = (cap ? esc(cap) : "") + credit;
  lb.hidden = false;
}
function closeLightbox() { lb.hidden = true; document.getElementById("lb-img").src = ""; }
document.getElementById("lb-close").addEventListener("click", closeLightbox);
lb.addEventListener("click", e => { if (e.target === lb) closeLightbox(); });
document.addEventListener("keydown", e => { if (e.key === "Escape") closeLightbox(); });
document.addEventListener("click", e => {
  const img = e.target.closest("img.th");
  if (img && img.dataset.full) openLightbox(img.dataset.full, img.dataset.cap);
});

// ── work "ficha": the full record for one painting (image + facts + links) ──
const workCard = document.getElementById("work-card");
let wcWork = null;
function openWorkCard(w) {
  if (!w) return;
  wcWork = w;
  const p = w.p;
  const cap = `${p.title || ""}${p.year ? ` (${p.year})` : ""} — ${p.location || ""}`;
  const img = p.image
    ? `<img class="th wc-img" src="${esc(fullImage(p.image))}" data-full="${esc(fullImage(p.image))}" data-cap="${esc(cap)}" alt="">`
    : `<div class="wc-noimg">no image on Wikimedia Commons</div>`;
  const row = (k, v) => v ? `<div class="wc-row"><span class="wc-k">${k}</span><span>${v}</span></div>` : "";
  const venue = [p.location, p.city, p.country].filter(Boolean).join(", ");
  const attr = (p.attribution && !ATTR_ACCEPTED.has(p.attribution))
    ? esc(p.attribution) + (p.attribution_note ? ` — <span class="wc-note">${esc(p.attribution_note)}</span>` : "") : "";
  const links = linksRow(p);
  document.getElementById("wc-body").innerHTML =
    `<div class="wc-imgwrap">${img}</div>` +
    `<div class="wc-info"><h3 class="wc-title">${esc(p.title || "Untitled")}</h3>` +
    row("Painter", painterTag(p)) + row("Date", esc(p.year || "")) + row("Where", esc(venue)) +
    row("Technique", esc(p.medium || "")) + row("Size", esc(p.dimensions || "")) + row("Attribution", attr) +
    (links ? `<div class="wc-links">${links}</div>` : "") +
    `<div class="wc-actions"><button type="button" class="wc-share">🔗 Share</button>` +
    `<span class="wc-hint">or just copy the address bar</span></div></div>`;
  workCard.hidden = false;
  // reflect the open painting in the address bar → copying the URL shares this exact work
  if (p.qid) history.replaceState(null, "", location.pathname + "?w=" + p.qid + location.hash);
}
function closeWorkCard() {
  workCard.hidden = true; wcWork = null; document.getElementById("wc-body").innerHTML = "";
  if (new URLSearchParams(location.search).has("w"))
    history.replaceState(null, "", location.pathname + location.hash);   // drop ?w= when closed
}
document.getElementById("wc-close").addEventListener("click", closeWorkCard);
workCard.addEventListener("click", e => {
  if (e.target.closest(".wc-share") && wcWork) { shareWork(wcWork.p); return; }
  if (e.target === workCard) closeWorkCard();
});
document.addEventListener("keydown", e => { if (e.key === "Escape") closeWorkCard(); });

// ── sharing: a link that reopens the atlas on this exact painting (or museum) ──
let toastT = 0;
function toast(msg) {
  let el = document.getElementById("toast");
  if (!el) { el = document.createElement("div"); el.id = "toast"; document.body.appendChild(el); }
  el.textContent = msg; el.classList.add("on");
  clearTimeout(toastT); toastT = setTimeout(() => el.classList.remove("on"), 1700);
}
function shareWork(p) {
  // share the per-work stub page (carries this painting's og:image so previews unfurl) — it
  // redirects into the app at ?w=<qid>. Falls back to the app URL if there's no qid.
  const url = p.qid ? new URL("atlas/w/" + p.qid + ".html", location.href).href : location.href;
  const title = `${p.title || "Painting"}${p.painter ? " — " + p.painter : ""}`;
  if (navigator.share) navigator.share({ title, url }).catch(() => {});
  else if (navigator.clipboard) navigator.clipboard.writeText(url).then(() => toast("Link copied ✓")).catch(() => toast("Copy failed"));
  else toast(url);
}
function deepLink() {   // ?w=<qid> → open that painting's ficha; ?m=<museum key> → that museum
  const q = new URLSearchParams(location.search);
  const w = q.get("w"), m = q.get("m");
  if (w) { const hit = works.find(x => x.p.qid === w); if (hit) return openWorkCard(hit); }
  if (m && museumIndex.some(x => x.key === m)) selectMuseum(m);
}
// Wikimedia Commons occasionally resets HTTP/2 under a burst of thumbnail requests
// (big popup/table). Degrade a failed thumbnail to the neutral placeholder box instead
// of a broken-image icon. (Capture phase — <img> error events don't bubble.)
document.addEventListener("error", e => {
  const img = e.target;
  if (img.tagName === "IMG" && (img.classList.contains("th") || img.classList.contains("tth"))) {
    img.classList.add("ph"); img.removeAttribute("src"); img.removeAttribute("data-full");
  }
}, true);

// ── geolocation: your nearest Caravaggio ──
function haversine(lat1, lon1, lat2, lon2) {
  const R = 6371, r = x => x * Math.PI / 180;
  const dLat = r(lat2 - lat1), dLon = r(lon2 - lon1);
  const s = Math.sin(dLat / 2) ** 2 + Math.cos(r(lat1)) * Math.cos(r(lat2)) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(s));
}
let userMarker = null, nearestLine = null;
function showBanner(html) {
  let el = document.getElementById("banner");
  if (!el) { el = document.createElement("div"); el.id = "banner"; document.body.appendChild(el); }
  el.innerHTML = `${html} <button id="banner-x" aria-label="Dismiss">✕</button>`;
  el.hidden = false;
  document.getElementById("banner-x").onclick = () => { el.hidden = true; };
}
// "Near me" = share your location, then browse the PLACES that hold works within a radius you
// choose (1–250 km). Useful in a city (lots nearby) and in a village (bump the radius to reach
// the nearest cities). The map shows your position + a radius circle; the side panel lists the
// places by distance. Click "Near me" again to clear and restore the previous view.
let nearMePrevView = null, nearCircle = null;
const NEAR_RADII = [1, 5, 25, 50, 100, 250];   // km presets

function nearVenues(lat, lon) {                 // filtered venues, with distance, sorted nearest-first
  const g = new Map();
  for (const w of works) {
    if (!passesAll(w.p)) continue;
    const k = `${w.lat.toFixed(5)},${w.lon.toFixed(5)}`;
    let v = g.get(k);
    if (!v) { v = { lat: w.lat, lon: w.lon, location: w.p.location || "—",
      city: w.p.city || "", country: w.p.country || "", count: 0 }; g.set(k, v); }
    v.count++;
  }
  return [...g.values()].map(v => ({ ...v, d: haversine(lat, lon, v.lat, v.lon) }))
    .sort((a, z) => a.d - z.d);
}

function clearNearMe() {
  const btn = document.getElementById("locate");
  if (userMarker) { map.removeLayer(userMarker); userMarker = null; }
  if (nearCircle) { map.removeLayer(nearCircle); nearCircle = null; }
  btn.textContent = "📍 Near me"; btn.classList.remove("active"); btn.disabled = false;
  state.near = null;
  if (nearMePrevView) { map.setView(nearMePrevView.center, nearMePrevView.zoom); nearMePrevView = null; }
  refresh();                                    // restore the normal viewport list
}

function setNearRadius(r) { if (state.near) { state.near.radiusKm = r; renderNearMe(); } }

function drawNearMe() {                          // user marker + radius circle, fit to the circle
  const { lat, lon, radiusKm } = state.near;
  if (nearCircle) map.removeLayer(nearCircle);
  if (userMarker) map.removeLayer(userMarker);
  userMarker = L.marker([lat, lon], { icon: L.divIcon({ className: "",
    html: `<div class="me"></div>`, iconSize: [16, 16], iconAnchor: [8, 8] }), zIndexOffset: 1000 })
    .addTo(map).bindPopup("You are here");
  nearCircle = L.circle([lat, lon], { radius: radiusKm * 1000,
    color: "#1a73e8", weight: 1, fillColor: "#1a73e8", fillOpacity: .06 }).addTo(map);
  map.fitBounds(nearCircle.getBounds(), { padding: [30, 30] });
}

function renderNearMe() {                        // owns the side panel while near-me is active
  if (!state.near) return;
  const { lat, lon, radiusKm } = state.near;
  const within = nearVenues(lat, lon).filter(v => v.d <= radiusKm);
  document.getElementById("panel-head").textContent =
    `${within.length} place${within.length === 1 ? "" : "s"} within ${radiusKm} km`;
  const chips = NEAR_RADII.map(r =>
    `<button type="button" class="rchip${r === radiusKm ? " on" : ""}" data-r="${r}">${r}</button>`).join("");
  let html = `<li class="near-ctrl"><span class="near-lbl">Radius km</span>${chips}</li>`;
  if (!within.length) html += `<li class="empty">Nothing within ${radiusKm} km — try a larger radius.</li>`;
  for (const v of within) {
    const km = v.d < 1 ? `${Math.round(v.d * 1000)} m` : `${v.d < 10 ? v.d.toFixed(1) : Math.round(v.d)} km`;
    html += `<li class="near-row" data-lat="${v.lat}" data-lon="${v.lon}"><span class="micon">🏛</span><div>` +
      `<div class="mname">${esc(v.location)}</div>` +
      `<div class="msub">${esc([v.city, v.country].filter(Boolean).join(", "))} · ${v.count} work${v.count === 1 ? "" : "s"} · <b>${km}</b></div></div></li>`;
  }
  const ul = document.getElementById("worklist"); ul.innerHTML = html;
  ul.querySelectorAll(".rchip").forEach(b => b.addEventListener("click", () => setNearRadius(+b.dataset.r)));
  ul.querySelectorAll(".near-row").forEach(row => row.addEventListener("click", () => {
    if (!view.map) { view.map = true; setView(); }
    map.setView([+row.dataset.lat, +row.dataset.lon], 15);
  }));
  drawNearMe();
}

document.getElementById("locate").addEventListener("click", () => {
  const btn = document.getElementById("locate");
  if (state.near) { clearNearMe(); return; }                // toggle off → restore
  if (!navigator.geolocation) { showBanner("Geolocation is not available in this browser."); return; }
  btn.textContent = "📍 Locating…"; btn.disabled = true;
  navigator.geolocation.getCurrentPosition(pos => {
    btn.disabled = false;
    const { latitude: lat, longitude: lon } = pos.coords;
    if (view.table) setTableView(false);   // near-me lives on the map → leave the table view
    nearMePrevView = { center: map.getCenter(), zoom: map.getZoom() };   // remember, to restore on clear
    // adaptive default radius: smallest preset that reaches the nearest place
    const vs = nearVenues(lat, lon);
    const d0 = vs.length ? vs[0].d : Infinity;
    state.near = { lat, lon, radiusKm: NEAR_RADII.find(r => r >= d0) || NEAR_RADII[NEAR_RADII.length - 1] };
    btn.textContent = "📍 Near me"; btn.classList.add("active");
    renderNearMe();
  }, err => {
    btn.textContent = "📍 Near me"; btn.disabled = false;
    showBanner("Could not get your location: " + esc(err.message));
  }, { enableHighAccuracy: false, timeout: 10000, maximumAge: 60000 });
});
