
"use strict";
/* Pastatlas: Italian pasta shapes x sauces. Conventions: ../../LLM.md (shared) and ../LLM.md (project). */
const DATA_V = "0.8.0";          /* version = cache-bust; bump per LLM.md section 3 */
const BUILD_AT = "2026-09-25 23:45";              /* stamped by scripts/stamp_build.py when deploying */

/* Data lives in pastatlas/data/*.json and is loaded by boot() at the bottom of this file.
   base.json, i18n.json, popularity.json, sources.json, media.json: edited by hand or by research.
   regional.json, italy_regions.json: GENERATED by scripts/, never edit them by hand. */
let REG, REG_ORDER, AREA, CITY, DOUGH, FRESH, SHAPE, SHAPE_G, P, FAM, ING, SFAM, S, R, DISH, NOTE, T, RULES,
    POP, PATHS, SRC, MEDIA, POP_SET;
const LI = {it:0,es:1,en:2};
const tri = (it,es,en) => ({it,es,en});

/* ================= DATA ================= */
const AREA_OF = r => ["PIE","VDA","LOM","TAA","VEN","FVG","LIG","EMR"].includes(r)?"nord":["TOS","UMB","MAR","LAZ"].includes(r)?"centro":["SIC","SAR"].includes(r)?"isole":"sud";







/* ratings: -1 sacrilege, 0 unusual, 1 compatible, 2 traditional, 3 canonical (named dish) */
const rate=(p,s)=>(R[p]&&R[p][s])||0;


const eggDough = d => d==="uovo"||d==="semolauovo"||d==="segale";
/* dietary preferences */
const DIET = {
  veg:{l:tri("Vegetariano","Vegetariano","Vegetarian"),s:f=>!["maiale","manzo","selvaggina","pollame","agnello","mare"].some(x=>f.has(x))},
  vegan:{l:tri("Vegano","Vegano","Vegan"),s:f=>!["maiale","manzo","selvaggina","pollame","agnello","mare","formaggio","latte","uovo"].some(x=>f.has(x)),p:p=>!eggDough(p.dough)},
  noegg:{l:tri("Senza uova","Sin huevo","Egg-free"),s:f=>!f.has("uovo"),p:p=>!eggDough(p.dough)},
  nodairy:{l:tri("Senza latticini","Sin lácteos","Dairy-free"),s:f=>!f.has("formaggio")&&!f.has("latte")},
  nopork:{l:tri("Senza maiale","Sin cerdo","No pork"),s:f=>!f.has("maiale")},
  nofish:{l:tri("Senza pesce","Sin pescado ni marisco","No fish or seafood"),s:f=>!f.has("mare")},
  nospicy:{l:tri("Non piccante","Sin picante","Not spicy"),s:f=>!f.has("peperoncino")}
};




/* ================= REGIONAL DATA (pastatlas/data/regional.json, built by scripts/build_regional.py) ================= */
function mergeRegional(G){
  for(const [k,[it,es,en,fam]] of Object.entries(G.ing)) ING[k]=fam?[tri(it,es,en),fam]:[tri(it,es,en)];
  Object.assign(FAM,G.fam); Object.assign(CITY,G.city); Object.assign(DOUGH,G.dough); Object.assign(SHAPE,G.shape); Object.assign(SHAPE_G,G.shapeG); Object.assign(SFAM,G.sfam);
  P.forEach(x=>x.core=true); S.forEach(x=>x.core=true);
  P.push(...G.pasta); S.push(...G.sauces);
  for(const [pid,row] of Object.entries(G.ratings)) R[pid]=Object.assign(R[pid]||{},row);
  Object.assign(DISH,G.dishes);
  for(const kind of ["pasta","sauce","dish"]) for(const [k,list] of Object.entries(G.sources[kind])){
    const cur=SRC[kind][k]||(SRC[kind][k]=[]); list.forEach(x=>{ if(!cur.some(y=>y.url===x.url)) cur.push(x); });
  }
}

/* ================= POPULARITY (what people choose, vs what tradition says) ================= */
/* what counts as "most popular" for the default matrix view */
function computePopSet(){ const ps=new Set(Object.keys(POP.shapes.rank)), ss=new Set(POP.survey.rank.map(r=>r.s));
  POP.survey.rank.forEach(r=>r.p&&ps.add(r.p));
  POP.cities.forEach(c=>c.top.forEach(x=>{ if(!x[1]) return; const [a,b]=x[1].split("|"); if(a!=="*") ps.add(a); ss.add(b); }));
  POP.areas.forEach(a=>a.s.forEach(x=>ss.add(x)));
  return {ps,ss}; }
const popOf = sid => POP.survey.rank.findIndex(r=>r.s===sid);
const popPair = (pid,sid) => POP.survey.rank.find(r=>r.s===sid&&r.p===pid);
const areaOfReg = r => POP.areas.find(a=>a.regs.includes(r));

/* ================= STATE ================= */
const store = {get(k,d){try{const v=localStorage.getItem(k);return v?JSON.parse(v):d}catch(e){return d}}, set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}};
let lang = store.get("pasta-lang",null) || "it";
let view = "matrix", sel = {type:"cell",p:"trofie",s:"pesto"}, layer = "pasta", atlasPick = null, bubble = null; /* bubble = {r, x, y} in map-box pixels */
const F = {dough:new Set(), fresh:"all", fam:new Set(), area:new Set(), diet:new Set(store.get("pasta-diet",[]))};
let scope = store.get("pasta-scope","pop");
let showPop = store.get("pasta-pop",true);
let groupP = store.get("pasta-gp","shape"), groupS = store.get("pasta-gs","fam");

const L = o => o ? (o[lang]||o.en) : "";
const t = k => L(T[k]);
const regName = c => REG[c][LI[lang]];
const pById = id => P.find(x=>x.id===id), sById = id => S.find(x=>x.id===id);
/* stars drawn as SVG so they always fit the cell, whatever the font */
const STAR='<polygon points="5,0.4 6.2,3.6 9.6,3.7 6.9,5.8 7.9,9.2 5,7.2 2.1,9.2 3.1,5.8 0.4,3.7 3.8,3.6"/>';
const CROSS='<svg class="stars" viewBox="0 0 10 10" width="9" height="9" aria-hidden="true"><path d="M1.5 1.5L8.5 8.5M8.5 1.5L1.5 8.5" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" fill="none"/></svg>';
const RL = r => r<0?T.rx:T.r[r], RD = r => r<0?T.rdx:T.rd[r], rc = r => r<0?"cx":"c"+r;
const stars = r => r<0?CROSS:r===0?"":`<svg class="stars" viewBox="0 0 ${r*10} 10" width="${r*8}" height="8" aria-hidden="true">${Array.from({length:r},(_,i)=>`<g transform="translate(${i*10} 0)">${STAR}</g>`).join("")}</svg>`;
const $ = id => document.getElementById(id);
const esc = s => String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const famsOfIngs = ings => new Set(ings.map(i=>ING[i][1]).filter(Boolean));
const famsOf = s => famsOfIngs(s.ing);
const varIngs = (s,v) => [...s.ing.filter(i=>!(v.rm||[]).includes(i)), ...(v.add||[])];
const dietFits = ings => { const f=famsOfIngs(ings); for(const d of F.diet) if(!DIET[d].s(f)) return false; return true; };
/* a sauce passes the preferences if its base recipe or any recognised variant does */
const sauceDietOK = s => dietFits(s.ing) || (s.v||[]).some(v=>dietFits(varIngs(s,v)));

/* ================= FILTERING ================= */
function pastaOK(p, ignore){
  if(ignore!=="dough" && F.dough.size && !F.dough.has(p.dough)) return false;
  if(F.fresh!=="all" && p.fresh!==(F.fresh==="fresh")) return false;
  if(ignore!=="scope" && scope==="core" && !p.core) return false;
  if(ignore!=="scope" && scope==="pop" && !POP_SET.ps.has(p.id)) return false;
  if(F.area.size && !p.reg.some(r=>F.area.has(AREA_OF(r)))) return false;
  const ff=famsOfIngs(p.fill||[]);
  for(const d of F.diet){ if(DIET[d].p && !DIET[d].p(p)) return false; if(!DIET[d].s(ff)) return false; }
  return true;
}
function sauceOK(s, ignore){
  if(ignore!=="scope" && scope==="core" && !s.core) return false;
  if(ignore!=="scope" && scope==="pop" && !POP_SET.ss.has(s.id)) return false;
  if(F.area.size && !s.reg.some(r=>F.area.has(AREA_OF(r)))) return false;
  const f=famsOf(s);
  if(ignore!=="fam") for(const x of F.fam) if(!f.has(x)) return false;
  return sauceDietOK(s);
}
const visP = ig => P.filter(p=>pastaOK(p,ig)), visS = ig => S.filter(s=>sauceOK(s,ig));

/* ================= GROUPING ================= */
const pGroup = {
  none:{key:()=>"",label:()=>""},
  shape:{key:p=>SHAPE[p.sh].g,get order(){return Object.keys(SHAPE_G)},label:k=>L(SHAPE_G[k])},
  dough:{key:p=>p.dough,get order(){return Object.keys(DOUGH)},label:k=>L(DOUGH[k].l)},
  area:{key:p=>AREA_OF(p.reg[0]),get order(){return Object.keys(AREA)},label:k=>L(AREA[k])}
};
const sGroup = {
  none:{key:()=>"",label:()=>""},
  fam:{key:s=>s.g,get order(){return Object.keys(SFAM)},label:k=>L(SFAM[k])},
  area:{key:s=>AREA_OF(s.reg[0]),get order(){return Object.keys(AREA)},label:k=>L(AREA[k])}
};
function grouped(items, G){
  if(!G.order) return [{k:"",items}];
  return G.order.map(k=>({k,items:items.filter(x=>G.key(x)===k)})).filter(g=>g.items.length);
}

/* ================= MAP ================= */
const K = Math.cos(42*Math.PI/180), SC = 460/11.7;
const proj = ([lat,lon]) => [(lon-6.6)*K*SC, (47.1-lat)*SC];
let patN=0;
/* opts: p/s/d = region lists to tint; cls = extra classes per region; pins = [{city,kind,label,count,data}] */
function mapSVG({p=[],s=[],d=[],cls={},pins=[]}={}){
  const pid="hatch"+(++patN);
  let h=`<svg viewBox="0 0 351 460" role="img" aria-label="Italia"><defs><pattern id="${pid}" width="7" height="7" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="7" height="7" fill="var(--pasta)"/><rect width="3.5" height="7" fill="var(--sauce)"/></pattern></defs>`;
  for(const code of REG_ORDER){
    const inP=p.includes(code), inS=s.includes(code), inD=d.includes(code);
    let c = inP&&inS?"":inP?"p":inS?"s":inD?"d":"";
    if(cls[code]) c+=" "+cls[code];
    h+=`<path class="reg ${c}" data-reg="${code}" d="${PATHS[code]}"${inP&&inS?` style="fill:url(#${pid})"`:""}><title>${esc(regName(code))}</title></path>`;
  }
  // pins, with simple label collision avoidance (biggest first)
  const placed=[]; const seen=new Map();
  pins.forEach(pn=>{ if(!CITY[pn.city]) return; const key=pn.city+"|"+pn.kind; if(!seen.has(key)) seen.set(key,{...pn}); });
  const list=[...seen.values()].sort((a,b)=>(b.count||1)-(a.count||1));
  let out="";
  for(const pn of list){
    const [x,y]=proj(CITY[pn.city]); const right=x<240;
    const r = pn.kind==="dishfill" ? 5+2.2*Math.sqrt(pn.count||1)*1.6 : pn.kind==="dish" ? 7 : 3.6;
    const label = pn.label ?? pn.city;
    const w=label.length*6.2, lx=right?x+r+4:x-r-4-w, box=[lx,y-8,lx+w,y+5];
    const free=!placed.some(b=>!(box[2]<b[0]||box[0]>b[2]||box[3]<b[1]||box[1]>b[3]));
    out+=`<g class="pin ${pn.kind}"${pn.data?` data-city="${esc(pn.city)}"`:""}><circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="${r.toFixed(1)}"><title>${esc(label)}</title></circle>`;
    if(pn.kind==="dishfill" && pn.count>1) out+=`<text x="${x.toFixed(1)}" y="${(y+3.5).toFixed(1)}" text-anchor="middle">${pn.count}</text>`;
    if(free){ placed.push(box); out+=`<text class="lbl" x="${(right?lx:lx+w).toFixed(1)}" y="${(y+4).toFixed(1)}" text-anchor="${right?"start":"end"}">${esc(label)}</text>`; }
    out+="</g>";
  }
  return h+out+"</svg>";
}

/* ================= RENDER: chrome & filters ================= */
function renderText(){
  document.documentElement.lang=lang;
  $("t-sub").textContent=t("sub"); $("t-filters").textContent=t("filters");
  document.querySelectorAll("#viewSeg button").forEach(b=>{b.textContent=t({matrix:"vMatrix",atlas:"vAtlas",cards:"vCards",why:"vWhy"}[b.dataset.view]);b.setAttribute("aria-pressed",b.dataset.view===view)});
  ["geoEyebrow","geoTitle","fine","atlasEyebrow","atlasTitle"].forEach(k=>$("t-"+k).textContent=t(k));
  document.querySelectorAll("#langSeg button").forEach(b=>b.setAttribute("aria-pressed",b.dataset.lang===lang));
  $("legend").innerHTML=[3,2,1,0,-1].map(r=>`<span class="k" title="${esc(L(RD(r)))}"><span class="chip ${rc(r)}">${stars(r)}</span>${esc(L(RL(r)))}</span>`).join("")
    + (showPop?`<span class="k"><span class="pbox" style="flex-direction:row;gap:3px;align-items:flex-end"><span class="pv" style="font-size:11px">46</span><span class="pbar" style="height:12px"></span></span>${esc(t("legBar"))}</span>
      <span class="k"><span class="prank" style="font-size:11px">1°</span>${esc(t("legRank"))}</span>
      <span class="k"><span class="cell c2 popc" style="width:18px;height:16px;margin:0;display:inline-block;cursor:default"></span>${esc(t("legDot"))}</span>`:"");
  const opt=(o,v,cur)=>`<option value="${v}"${v===cur?" selected":""}>${esc(t(o))}</option>`;
  $("groupby").innerHTML=`<label>${esc(t("groupP"))}<select id="gp">${opt("gNone","none",groupP)}${opt("gShape","shape",groupP)}${opt("gDough","dough",groupP)}${opt("gArea","area",groupP)}</select></label>
    <span class="seg" role="group" id="scopeSeg"><button data-scope="pop" aria-pressed="${scope==="pop"}">${esc(t("scPop"))}</button><button data-scope="core" aria-pressed="${scope==="core"}">${esc(t("scCore"))}</button><button data-scope="all" aria-pressed="${scope==="all"}">${esc(t("scAll"))}</button></span>
    <label class="poptoggle"><input type="checkbox" id="popT"${showPop?" checked":""}>${esc(t("pop"))}</label>
    <label>${esc(t("groupS"))}<select id="gs">${opt("gNone","none",groupS)}${opt("gFam","fam",groupS)}${opt("gArea","area",groupS)}</select></label>`;
  $("rules").innerHTML=RULES.map(r=>`<div class="rule"><b>${esc(L(r.t))}</b><span>${esc(L(r.d))}</span></div>`).join("");
}
function renderFilters(){
  const chip=(grp,key,label,on,count,dis)=>`<button class="fchip" data-f="${grp}" data-k="${key}" aria-pressed="${on}"${dis?" disabled":""}>${esc(label)}${count!=null?`<small>${count}</small>`:""}</button>`;
  const dough=Object.keys(DOUGH).map(k=>{const n=P.filter(p=>p.dough===k&&pastaOK(p,"dough")).length;return chip("dough",k,L(DOUGH[k].l),F.dough.has(k),n,!n&&!F.dough.has(k))}).join("");
  const fresh=["all","fresh","dried"].map(k=>chip("fresh",k,k==="all"?t("all"):L(FRESH[k]),F.fresh===k)).join("");
  const fam=Object.keys(FAM).map(k=>{const n=S.filter(s=>sauceOK(s,"fam")&&famsOf(s).has(k)&&[...F.fam].every(x=>famsOf(s).has(x))).length;return chip("fam",k,L(FAM[k]),F.fam.has(k),n,!n&&!F.fam.has(k))}).join("");
  const diet=Object.keys(DIET).map(k=>chip("diet",k,L(DIET[k].l),F.diet.has(k))).join("");
  const area=Object.keys(AREA).map(k=>chip("area",k,L(AREA[k]),F.area.has(k))).join("");
  const anyExplore = F.dough.size||F.fam.size||F.area.size||F.fresh!=="all";
  $("fgrid").innerHTML=`
    <div class="fbox"><span class="eyebrow">${esc(t("fDough"))}</span><div class="chips">${dough}</div>
      <span class="eyebrow" style="margin-top:4px">${esc(t("fFresh"))}</span><div class="chips">${fresh}</div>
      <span class="eyebrow" style="margin-top:4px">${esc(t("fArea"))}</span><div class="chips">${area}</div></div>
    <div class="fbox"><span class="eyebrow">${esc(t("fIng"))}${anyExplore?`<button class="linkbtn" data-clear="explore">${esc(t("clear"))}</button>`:""}</span><div class="chips">${fam}</div></div>
    <div class="fbox pref"><span class="eyebrow">${esc(t("fDiet"))}${F.diet.size?`<button class="linkbtn" data-clear="diet">${esc(t("clear"))}</button>`:""}</span><div class="chips">${diet}</div><p class="fine">${esc(t("fDietNote"))}</p></div>`;
  $("fcount").textContent=`${visP().length} × ${visS().length} ${t("showing")}`;
  const act=[...[...F.area].map(k=>L(AREA[k])),...[...F.dough].map(k=>L(DOUGH[k].l)),...(F.fresh!=="all"?[L(FRESH[F.fresh])]:[]),...[...F.fam].map(k=>L(FAM[k]))].map(x=>`<span>${esc(x)}</span>`)
    .concat([...F.diet].map(k=>`<span class="pref">${esc(L(DIET[k].l))}</span>`));
  $("factive").innerHTML=act.join("");
  $("ftoggle").textContent=t($("filters").open?"hideF":"showF");
}

/* ================= RENDER: matrix ================= */
function renderMatrix(){
  const ps=visP(), ss=visS();
  const mx=$("mx");
  if(!ps.length||!ss.length){ mx.className="mx"; mx.innerHTML=`<tbody><tr><td class="empty">${esc(t("empty"))}</td></tr></tbody>`; return; }
  const pg=grouped(ps,pGroup[groupP]||pGroup.none), sg=grouped(ss,sGroup[groupS]||sGroup.none);
  const hasG = groupS!=="none";
  const cols=[]; sg.forEach(g=>g.items.forEach((s,i)=>cols.push({s,first:i===0&&hasG})));
  const dense=cols.length>26;
  let h="<thead>";
  const nHead=(hasG?2:1)+(showPop?1:0);
  if(hasG){
    h+=`<tr class="groups"><th class="corner" rowspan="${nHead}"><span class="eyebrow">${esc(t("corner"))}</span></th>`;
    sg.forEach(g=>h+=`<th colspan="${g.items.length}" title="${esc(sGroup[groupS].label(g.k))}">${esc(sGroup[groupS].label(g.k))}</th>`);
    h+=`</tr><tr class="names">`;
  } else h+=`<tr class="names"><th class="corner" rowspan="${nHead}"><span class="eyebrow">${esc(t("corner"))}</span></th>`;
  cols.forEach(({s,first},j)=>h+=`<th data-col="${j}"${first?' class="gl"':""}><button class="colh" data-s="${s.id}">${esc(s.n)}<small>${s.reg[0]}</small></button>${thumb("s",s.id)}</th>`);
  h+="</tr>";
  if(showPop){
    const max=POP.survey.rank[0].pct;
    h+=`<tr class="pop">`+cols.map(({s,first})=>{const i=popOf(s.id); if(i<0) return `<th${first?' class="gl"':""}></th>`; const r=POP.survey.rank[i];
      return `<th${first?' class="gl"':""} title="#${i+1} ${esc(t("popRank"))} · ${r.pct}%"><span class="pbox"><span class="pv">${Math.round(r.pct)}</span><span class="pbar" style="height:${Math.round(4+14*r.pct/max)}px"></span></span></th>`}).join("")+`</tr>`;
  }
  h+="</thead><tbody>";
  pg.forEach(g=>{
    if(g.k) h+=`<tr class="grp"><td colspan="${cols.length+1}"><span>${esc(pGroup[groupP].label(g.k))}</span></td></tr>`;
    g.items.forEach(p=>{
      h+=`<tr data-p="${p.id}"><th><button class="rowh" data-p="${p.id}">${thumb("p",p.id)}${esc(p.n)}${showPop&&POP.shapes.rank[p.id]?`<span class="prank" title="${esc(t("legRank"))}">${POP.shapes.rank[p.id]}°</span>`:""}<small>${p.reg[0]}</small></button></th>`;
      cols.forEach(({s,first},j)=>{const r=rate(p.id,s.id);
        h+=`<td data-col="${j}"${first?' class="gl"':""}><button class="cell ${rc(r)}${showPop&&popPair(p.id,s.id)?" popc":""}" data-p="${p.id}" data-s="${s.id}" aria-label="${esc(p.n)} × ${esc(s.n)}: ${esc(L(RL(r)))}" title="${esc(p.n)} × ${esc(s.n)} · ${esc(L(RL(r)))}">${r<0?CROSS:r?(dense?(r===3?stars(1):""):stars(r)):""}</button></td>`});
      h+="</tr>";
    });
  });
  mx.className="mx"+(hasG?" hasg":"")+(dense?" dense":"");
  mx.innerHTML=h+"</tbody>";
  markSel();
  showCellBubble(null);
  watchHead(); if(pageScrolls) headFromScroll();
}
/* ---- floating column header ---- */
let headIO=null, pageScrolls=false;
function setHeadOffset(px){
  const mx=$("mx"), head=mx.tHead; if(!head) return;
  const max=Math.max(0, mx.offsetHeight - head.offsetHeight - 40);
  const y=Math.round(Math.max(0,Math.min(px,max)));
  head.querySelectorAll("th").forEach(th=>th.style.transform=y?`translateY(${y}px)`:"");
  head.classList.toggle("floating",y>0);
}
function headFromScroll(){ pageScrolls=true; if(view==="matrix") setHeadOffset(-$("mx").getBoundingClientRect().top); }
function watchHead(){
  // IntersectionObserver sees the real visible area even when the page is framed at full height
  headIO?.disconnect();
  const mx=$("mx"); if(!mx.tHead) return;
  headIO=new IntersectionObserver(es=>{ if(pageScrolls) return; es.forEach(en=>setHeadOffset(en.intersectionRect.top-en.boundingClientRect.top)); },
    {threshold:Array.from({length:401},(_,i)=>i/400)});
  headIO.observe(mx);
}
window.addEventListener("scroll",headFromScroll,{passive:true});

/* ---- bubble on a matrix cell ---- */
function showCellBubble(btn){
  document.querySelector(".cellbubble")?.remove();
  if(!btn) return;
  const p=pById(btn.dataset.p), s=sById(btn.dataset.s), r=rate(p.id,s.id), key=p.id+"|"+s.id, dish=DISH[key], note=NOTE[key];
  const wrap=$("mxScroll"), wr=wrap.getBoundingClientRect(), cr=btn.getBoundingClientRect();
  const cx=cr.left-wr.left+wrap.scrollLeft+cr.width/2, top=cr.top-wr.top, bw=Math.min(270,wrap.clientWidth-16);
  const left=Math.max(8,Math.min(wrap.scrollWidth-bw-8,cx-bw/2));
  const origin=x=>`${x.reg.map(regName).join(" · ")}${x.city?` (${x.city})`:""}`;
  let body;
  if(dish) body=`<span class="dn">${esc(L(dish.n))}</span>${dish.unc?`<span class="badge">${esc(t("uncDish"))}</span>`:""}<span class="wh">${esc(t("typical"))}: ${esc(dish.city)}, ${esc(regName(dish.reg))}</span><span class="wh">${esc(L(dish.t))}</span>`;
  else body=`${note?`<span>${esc(L(note))}</span>`:""}<span class="wh">${esc(t("origins"))}: ${esc(p.n)} · ${esc(origin(p))}; ${esc(s.n)} · ${esc(origin(s))}</span>`;
  const el=document.createElement("div");
  el.className="cellbubble"; el.setAttribute("role","button"); el.tabIndex=0;
  el.innerHTML=`<button class="x" data-closecell="1" aria-label="×">×</button><span class="ttl">${esc(p.n)} × ${esc(s.n)}</span>
    <span class="v"><span class="chip ${rc(r)}">${stars(r)}</span><b>${esc(L(RL(r)))}</b></span>${body}<span class="more">${esc(t("seeSheet"))}</span>`;
  el.style.left=left+"px"; el.style.width=bw+"px"; el.style.setProperty("--ax",(cx-left)+"px");
  wrap.appendChild(el);
  const h=el.offsetHeight, up = top-h-12 > 0;
  el.classList.add(up?"up":"down");
  el.style.top=(up? top-h-10 : top+cr.height+10)+"px";
}

function markSel(){
  const mx=$("mx");
  mx.querySelectorAll(".sel,.on,.hl,.dim").forEach(e=>e.classList.remove("sel","on","hl","dim"));
  if(sel.type==="cell") mx.querySelector(`.cell[data-p="${sel.p}"][data-s="${sel.s}"]`)?.classList.add("sel");
  if(sel.p) mx.querySelector(`.rowh[data-p="${sel.p}"]`)?.classList.add("on");
  if(sel.s) mx.querySelector(`.colh[data-s="${sel.s}"]`)?.classList.add("on");
  if(sel.type==="pasta") mx.querySelectorAll("tbody tr[data-p]").forEach(tr=>{ if(tr.dataset.p!==sel.p) tr.querySelectorAll("td").forEach(td=>td.classList.add("dim")) });
  if(sel.type==="sauce"){ const th=mx.querySelector(`.colh[data-s="${sel.s}"]`)?.parentElement; const j=th?th.dataset.col:null; mx.querySelectorAll("tbody td[data-col]").forEach(td=>{ if(td.dataset.col!==j) td.classList.add("dim") }); }
}

/* ================= RENDER: panel ================= */
function where(item,color){
  return `<span><span class="dot" style="background:var(--${color})"></span>${esc(item.reg.map(regName).join(" · "))}${item.city?` · ${esc(item.city)}`:""}${item.unc?`<span class="badge">${esc(t("unc"))}</span>`:""}</span>`;
}
const li=(kind,item,r)=>`<li><button data-open="${kind}" data-id="${item.id}"><span class="chip ${rc(r)}">${stars(r)}</span><i>${esc(item.n)}</i><small>${item.reg.join("·")}</small></button></li>`;
const ingChips = s => `<div class="ings">${s.ing.map(i=>`<span class="ing">${esc(L(ING[i][0]))}</span>`).join("")}</div>`;
function variantList(s){
  if(!s.v||!s.v.length) return "";
  const baseOK=dietFits(s.ing);
  return `<div class="sub"><span class="eyebrow">${esc(t("variants"))}</span>${F.diet.size&&!baseOK?`<p class="hiddenby">${esc(t("onlyVar"))}</p>`:""}<ul class="vars">${s.v.map(v=>{
    const ok=F.diet.size&&!baseOK&&dietFits(varIngs(s,v));
    return `<li><b>${esc(L(v.n))}</b>${v.where?` <small style="color:var(--muted)">· ${esc(v.where)}</small>`:""}${ok?`<span class="ok">✓ ${esc(t("fits"))}</span>`:""}<span class="ch">${esc(L(v.c))}</span></li>`}).join("")}</ul></div>`;
}
const srcItems = list => (list||[]).map(x=>`<li><a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.t)}</a><small>${esc(x.pub)}${x.sup?` · ${esc(x.sup)}`:""}</small></li>`).join("");
function sourceBlock(groups){
  const body=groups.filter(g=>g.list&&g.list.length).map(g=>(g.label?`<li class="grp">${esc(g.label)}</li>`:"")+srcItems(g.list)).join("");
  return body?`<div class="sub"><span class="eyebrow">${esc(t("sources"))}</span><ul class="srcs">${body}</ul></div>`:"";
}
function renderBiblio(){
  const map=new Map();
  const add=(list,label)=>(list||[]).forEach(x=>{ if(!map.has(x.url)) map.set(x.url,{...x,used:new Set()}); map.get(x.url).used.add(label); });
  P.forEach(p=>add(SRC.pasta[p.id],p.n)); S.forEach(s=>add(SRC.sauce[s.id],s.n));
  Object.entries(SRC.dish).forEach(([k,list])=>{const [a,b]=k.split("|");const pp=pById(a),ss=sById(b);if(pp&&ss) add(list,`${pp.n} × ${ss.n}`)});
  const all=[...map.values()].sort((a,b)=>a.pub.localeCompare(b.pub)||a.t.localeCompare(b.t));
  const open=$("biblio").open;
  $("biblio").innerHTML=`<summary>${esc(t("biblio"))} <small class="fine" style="font-family:var(--mono);font-size:12px">(${all.length})</small></summary><p class="fine" style="margin-top:8px">${esc(t("biblioNote"))}</p><ol>${all.map(x=>`<li><a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.t)}</a> <small>· ${esc(x.pub)}. ${esc(t("usedFor"))}: ${esc([...x.used].join(", "))}</small></li>`).join("")}</ol>`;
  $("biblio").open=open;
}
const srcLink = x => `<a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.pub)}, ${x.year}</a>`;
function popBlock({pid,sid,reg}){
  const out=[];
  if(sid){
    const i=popOf(sid), pr=pid&&popPair(pid,sid);
    if(i>=0){ const r=POP.survey.rank[i];
      out.push(`<p class="popline"><b>#${i+1}</b> ${esc(t("popRank"))} · <b>${r.pct}%</b>${r.p&&!pid?` (${esc(pById(r.p).n)})`:""}${pr?"":""} · <span class="fine">${esc(L(POP.survey.m))} ${srcLink(POP.survey)}</span>${r.gen?`<br><span class="fine">${esc(t("popGen"))}</span>`:""}</p>`); }
    const hits=[]; POP.cities.forEach(c=>c.top.forEach((x,k)=>{ if(!x[1]) return; const [a,b]=x[1].split("|"); if(b===sid&&(!pid||a===pid||a==="*")) hits.push(`${c.city} #${k+1}${x[2]?` (${x[2]})`:""}`)}));
    if(hits.length) out.push(`<p class="popline">${esc(t("popCities"))}: ${esc(hits.join(" · "))} <span class="fine">(Just Eat)</span></p>`);
    const ar=POP.areas.filter(a=>a.s.includes(sid)).map(a=>L(a.l));
    if(ar.length) out.push(`<p class="popline">${esc(t("popArea"))}: ${esc(ar.join(", "))} <span class="fine">(${srcLink(POP.src.yg23)})</span></p>`);
  }
  if(pid&&!sid){ const r=POP.shapes.rank[pid]; if(r) out.push(`<p class="popline"><b>#${r}</b> ${esc(t("popShape"))} <span class="fine">(${srcLink(POP.shapes)})</span></p>`); }
  if(reg){
    const a=areaOfReg(reg);
    if(a) out.push(`<p class="popline">${esc(t("popArea"))} (${esc(L(a.l))}): ${esc(a.s.map(x=>sById(x).n).join(", "))}${a.note?` · ${esc(L(a.note))}`:""} <span class="fine">(${srcLink(POP.src.yg23)})</span></p>`);
    const cs=POP.cities.filter(c=>c.reg===reg);
    out.push(cs.length?cs.map(c=>`<div class="citycard"><b>${esc(c.city)}</b> <small>${esc(t("popCities").toLowerCase())} · ${srcLink(POP.src[c.src])}</small><ol>${c.top.map(x=>`<li>${esc(x[0])}${x[2]?` <small>${esc(x[2])}</small>`:""}</li>`).join("")}</ol></div>`).join(""):`<p class="hiddenby">${esc(t("noCityData"))}</p>`);
  }
  if(!out.length) out.push(`<p class="hiddenby">${esc(t("popNone"))}</p>`);
  return `<div class="sub"><span class="eyebrow">${esc(t("pop"))}</span>${out.join("")}</div>`;
}
const med = (k,id) => (k==="p"?MEDIA.pasta:MEDIA.cond)[id];
const thumb = (k,id) => { const m=med(k,id); return m&&m.img?`<img class="th" src="${esc(m.img)}" alt="" loading="lazy" decoding="async">`:""; };
function hero(items){
  const ms=items.map(([k,id])=>med(k,id)).filter(m=>m&&m.img); if(!ms.length) return "";
  return `<figure class="hero${ms.length>1?" duo":""}">${ms.map(m=>`<img src="${esc(m.img)}" alt="">`).join("")}<figcaption>${ms.map(m=>`${esc(m.author||"")} · <a href="${esc(m.commons)}" target="_blank" rel="noopener">${esc(m.license||"")}</a>`).join(" · ")}</figcaption></figure>`;
}
function wikiBlock(w){
  if(!w) return ""; const order=[lang,...["it","es","en"].filter(x=>x!==lang)].filter(x=>w[x]);
  return order.length?`<div class="sub"><span class="eyebrow">${esc(t("wiki"))}</span><div class="links">${order.map(x=>`<a href="${esc(w[x])}" target="_blank" rel="noopener">${x.toUpperCase()}</a>`).join("")}</div></div>`:"";
}
function rankList(kind,pairs,hiddenCount){
  const best=pairs.filter(([,v])=>v>=2), ok=pairs.filter(([,v])=>v===1), no=pairs.filter(([,v])=>v<0);
  let h="";
  if(best.length) h+=`<div class="sub"><span class="eyebrow">${esc(t(kind==="cell-s"?"best":"bestP"))}</span><ul class="list">${best.map(([x,v])=>li(kind,x,v)).join("")}</ul></div>`;
  if(ok.length) h+=`<div class="sub"><span class="eyebrow">${esc(t("also"))}</span><ul class="list">${ok.map(([x,v])=>li(kind,x,v)).join("")}</ul></div>`;
  if(no.length) h+=`<div class="sub"><span class="eyebrow">${esc(t("avoid"))}</span><p style="margin:4px 0 0;color:var(--muted);font-size:13.5px">${no.map(([x])=>esc(x.n)).join(", ")}</p></div>`;
  if(hiddenCount) h+=`<p class="hiddenby">+${hiddenCount} ${esc(t("hiddenN"))}</p>`;
  return h;
}
function renderPanel(){
  let h="";
  if(sel.type==="cell"){
    const p=pById(sel.p), s=sById(sel.s), r=rate(p.id,s.id), key=p.id+"|"+s.id, dish=DISH[key], note=NOTE[key];
    const others=visP().filter(x=>x.id!==p.id).map(x=>[x,rate(x.id,s.id)]).filter(([,v])=>v>=2).sort((a,b)=>b[1]-a[1]).slice(0,6);
    const pins=[{city:p.city,kind:"pt"},{city:s.city,kind:"pt"}]; if(dish) pins.push({city:dish.city,kind:"dish",label:dish.city,count:9});
    h=`${hero([["p",p.id],["s",s.id]])}<div class="eyebrow">${esc(t("pasta"))} × ${esc(t("sauce"))}</div>
      <h3><i>${esc(p.n)}</i><span class="x">×</span><i>${esc(s.n)}</i></h3>
      <div class="verdict"><span class="chip ${rc(r)}">${stars(r)}</span><b>${esc(L(RL(r)))}</b></div>
      <div style="color:var(--muted);font-size:13.5px">${esc(L(RD(r)))}</div>
      ${dish?`<div class="note"><b>${esc(L(dish.n))}${dish.unc?`<span class="badge">${esc(t("uncDish"))}</span>`:""}</b>${esc(L(dish.t))}</div>`:note?`<div class="note">${esc(L(note))}</div>`:""}
      <div class="mapbox">${mapSVG({p:p.reg,s:s.reg,pins})}</div>
      <div class="maplegend"><span><span class="sw" style="background:var(--pasta)"></span>${esc(t("mkP"))}</span><span><span class="sw" style="background:var(--sauce)"></span>${esc(t("mkS"))}</span>${dish?`<span><span class="ring"></span>${esc(t("mkD"))}: ${esc(dish.city)}</span>`:""}</div>
      <div class="kv">
        <div><span class="eyebrow">${esc(t("shape"))} · ${esc(p.n)}</span>${esc(L(p.shd||SHAPE[p.sh].d))}</div>
        <div><span class="eyebrow">${esc(t("dough"))} · ${esc(p.n)}</span>${esc(L(DOUGH[p.dough].l))} · ${esc(L(FRESH[p.fresh?"fresh":"dried"]))}</div>
        ${s.w?`<div><span class="eyebrow">${esc(t("wants"))} · ${esc(s.n)}</span>${esc(L(s.w))}</div>`:""}
        <div><span class="eyebrow">${esc(t("ings"))} · ${esc(s.n)}</span>${ingChips(s)}</div>
      </div>
      ${others.length?`<div class="sub"><span class="eyebrow">${esc(t("alt"))}</span><ul class="list">${others.map(([x,v])=>li("cell-p",x,v)).join("")}</ul></div>`:""}
      ${popBlock({pid:p.id,sid:s.id})}
      ${variantList(s)}
      ${SRC.dish[key]?"":`<p class="hiddenby" style="margin-top:16px">${esc(t("noSrc"))}</p>`}
      ${wikiBlock((MEDIA.dish[key]||{}).wiki)}
      ${sourceBlock([{label:SRC.dish[key]?(dish?L(dish.n):`${p.n} × ${s.n}`):"",list:SRC.dish[key]},{label:p.n,list:SRC.pasta[p.id]},{label:s.n,list:SRC.sauce[s.id]}])}`;
    if(!pastaOK(p)||!sauceOK(s)) h=`<p class="hiddenby">${esc(t("outFilter"))}</p>`+h;
  } else if(sel.type==="region"){
    const r=sel.r, {ps,ss,ds}=regionData(r);
    const bestOf=p=>{const b=visS().map(s=>[s,rate(p.id,s.id)]).sort((a,c)=>c[1]-a[1])[0];return b&&b[1]>=2?b[0].n:""};
    const local=[]; ps.forEach(p=>ss.forEach(s=>{const v=rate(p.id,s.id); if(v>=2) local.push([p,s,v])})); local.sort((a,b)=>b[2]-a[2]);
    const pins=[...ps,...ss].filter(x=>x.city).map(x=>({city:x.city,kind:"pt"})).concat(ds.map(d=>({city:d.city,kind:"dish",count:9})));
    h=`<div class="eyebrow">${esc(t("region"))} · ${esc(L(AREA[AREA_OF(r)]))}</div><h3><i>${esc(regName(r))}</i></h3>
      <div class="mapbox">${mapSVG({d:[r],pins})}</div>
      ${!ps.length&&!ss.length&&!ds.length?`<p class="hiddenby">${esc(t("nothingHere"))}</p>`:""}
      ${ds.length?`<div class="sub"><span class="eyebrow">${esc(t("dishesHere"))}</span><ul class="list">${ds.map(d=>{const [pp,sx]=d.k.split("|");return `<li><button data-open="dishcell" data-id="${d.k}"><span class="chip c3">${stars(3)}</span><i>${esc(L(d.n))}</i><small>${esc(d.city)}</small></button></li>`}).join("")}</ul></div>`:""}
      ${ps.length?`<div class="sub"><span class="eyebrow">${esc(t("pastaHere"))}</span><ul class="list">${ps.map(p=>`<li><button data-open="pasta" data-id="${p.id}"><span class="dot" style="background:var(--pasta)"></span><i>${esc(p.n)}</i><small>${bestOf(p)?esc(t("bestWith"))+" "+esc(bestOf(p)):""}</small></button></li>`).join("")}</ul></div>`:""}
      ${ss.length?`<div class="sub"><span class="eyebrow">${esc(t("sauceHere"))}</span><ul class="list">${ss.map(s=>`<li><button data-open="sauce" data-id="${s.id}"><span class="dot" style="background:var(--sauce)"></span><i>${esc(s.n)}</i><small>${esc(s.city||"")}</small></button></li>`).join("")}</ul></div>`:""}
      ${local.length?`<div class="sub"><span class="eyebrow">${esc(t("localPairs"))}</span><p class="hiddenby" style="margin:2px 0 0">${esc(t("localNote"))}</p><ul class="list">${local.map(([p,s,v])=>`<li><button data-open="dishcell" data-id="${p.id}|${s.id}"><span class="chip ${rc(v)}">${stars(v)}</span><i>${esc(p.n)} × ${esc(s.n)}</i></button></li>`).join("")}</ul></div>`:""}
      ${popBlock({reg:r})}`;
  } else if(sel.type==="pasta"){
    const p=pById(sel.p), vs=visS("scope");
    h=`${hero([["p",p.id]])}<div class="eyebrow">${esc(t("pasta"))}</div><h3><i>${esc(p.n)}</i></h3>
      <div class="where">${where(p,"pasta")}</div>
      <div class="mapbox">${mapSVG({p:p.reg,pins:[{city:p.city,kind:"pt"}]})}</div>
      <p>${esc(L(p.d))}</p>
      <div class="kv"><div><span class="eyebrow">${esc(t("dough"))}</span>${esc(L(DOUGH[p.dough].d))} ${esc(L(FRESH[p.fresh?"fresh":"dried"]))}.</div>
        <div><span class="eyebrow">${esc(t("shape"))}</span>${esc(L(p.shd||SHAPE[p.sh].d))}</div></div>
      ${rankList("cell-s",vs.map(s=>[s,rate(p.id,s.id)]).sort((a,b)=>b[1]-a[1]),S.length-vs.length)}
      ${popBlock({pid:p.id})}
      ${wikiBlock((med("p",p.id)||{}).wiki)}
      ${sourceBlock([{list:SRC.pasta[p.id]}])}`;
  } else {
    const s=sById(sel.s), vp=visP("scope");
    h=`${hero([["s",s.id]])}<div class="eyebrow">${esc(t("sauce"))}</div><h3><i>${esc(s.n)}</i></h3>
      <div class="where">${where(s,"sauce")}</div>
      <div class="mapbox">${mapSVG({s:s.reg,pins:[{city:s.city,kind:"pt"}]})}</div>
      <p>${esc(L(s.d))}</p>
      <div class="kv"><div><span class="eyebrow">${esc(t("ings"))}</span>${ingChips(s)}</div>
        ${s.w?`<div><span class="eyebrow">${esc(t("wants"))}</span>${esc(L(s.w))}</div>`:""}</div>
      ${popBlock({sid:s.id})}
      ${variantList(s)}
      ${rankList("cell-p",vp.map(p=>[p,rate(p.id,s.id)]).sort((a,b)=>b[1]-a[1]),P.length-vp.length)}
      ${wikiBlock((med("s",s.id)||{}).wiki)}
      ${sourceBlock([{list:SRC.sauce[s.id]}])}`;
  }
  $("panel").innerHTML=`<button class="closep" data-closepanel="1" aria-label="${esc(t("close"))}">×</button>`+h;
}

/* ================= RENDER: atlas ================= */
function visDishes(){
  const vp=new Set(visP().map(p=>p.id)), vs=new Set(visS().map(s=>s.id));
  return Object.entries(DISH).filter(([k])=>{const [p,s]=k.split("|");return vp.has(p)&&vs.has(s)}).map(([k,d])=>({k,...d}));
}
function regionData(r){
  const ps=visP().filter(p=>p.reg.includes(r)), ss=visS().filter(s=>s.reg.includes(r)), ds=visDishes().filter(d=>d.reg===r);
  return {ps,ss,ds};
}
function renderBubble(){
  const box=$("atlasMap"); box.querySelector(".bubble")?.remove();
  if(!bubble) return;
  const {ps,ss,ds}=regionData(bubble.r);
  const W=box.clientWidth, bw=Math.min(250,W-16);
  const popMode = layer==="pop";
  const left=Math.max(8,Math.min(W-bw-8,bubble.x-bw/2));
  const up = bubble.y>200;
  const cities=POP.cities.filter(c=>c.reg===bubble.r), area=areaOfReg(bubble.r);
  const items = popMode ? [...cities.map(c=>`<li>${esc(c.city)}: ${esc(c.top[0][0])} <small>${POP.src[c.src].year}</small></li>`), ...(area?[`<li><small>${esc(L(area.l))}:</small> ${esc(area.s.map(x=>sById(x).n).join(", "))}</li>`]:[])]
    : ds.length ? ds.slice(0,5).map(d=>`<li>${esc(L(d.n))} <small>${esc(d.city)}</small></li>`)
    : [...ps.map(p=>`<li>${esc(p.n)} <small>${esc(t("pasta").toLowerCase())}</small></li>`),...ss.map(x=>`<li>${esc(x.n)} <small>${esc(t("sauce").toLowerCase())}</small></li>`)].slice(0,5);
  const more = popMode ? 0 : (ds.length?ds.length:ps.length+ss.length)-items.length;
  const el=document.createElement("div");
  el.className="bubble "+(up?"up":"down"); el.setAttribute("role","button"); el.tabIndex=0; el.dataset.bubble=bubble.r;
  el.style.left=left+"px"; el.style.width=bw+"px"; el.style.setProperty("--ax",(bubble.x-left)+"px");
  el.innerHTML=`<button class="x" data-closebubble="1" aria-label="×">×</button><b>${esc(regName(bubble.r))}</b>
    <span class="cnt">${ps.length} ${esc(t("nPasta"))} · ${ss.length} ${esc(t("nSauce"))} · ${ds.length} ${esc(t("nDish"))}</span>
    ${items.length?`<ul>${items.join("")}${more>0?`<li><small>+${more}</small></li>`:""}</ul>`:`<span class="fine">${esc(t("none"))}</span>`}
    <span class="more">${esc(t("openSheet"))}</span>`;
  box.appendChild(el);
  // place above or below the click point once its height is known
  el.style.top = (up ? bubble.y-el.offsetHeight-12 : bubble.y+14)+"px";
}
function openRegion(r){ bubble=null; atlasPick=r; renderAtlas(); select({type:"region",r}); }
function renderAtlasPop(){
  const cls={}; POP.areas.forEach((a,i)=>a.regs.forEach(r=>cls[r]="a"+i));
  if(atlasPick) cls[atlasPick]+=" pick";
  $("atlasMap").innerHTML=mapSVG({cls,pins:POP.cities.map(c=>({city:c.city,kind:"popfill",count:1,data:1}))});
  renderBubble();
  const regs = atlasPick ? [atlasPick] : REG_ORDER.filter(r=>POP.cities.some(c=>c.reg===r));
  $("regionList").innerHTML = POP.areas.map(a=>`<div class="region-card"><h4>${esc(L(a.l))}<small>YouGov 2023</small></h4><div class="tags">${a.s.map(x=>`<button class="tag s" data-open="sauce" data-id="${x}">${esc(sById(x).n)}</button>`).join("")}${a.note?`<span class="fine" style="align-self:center">${esc(L(a.note))}</span>`:""}</div></div>`).join("")
    + regs.map(r=>`<div class="region-card${atlasPick===r?" pick":""}"><h4 data-reg="${r}">${esc(regName(r))}<small>Just Eat</small></h4>${popBlock({reg:r}).replace(/^<div class="sub">/,"<div>")}</div>`).join("");
}
function renderAtlas(){
  document.querySelectorAll("#layerSeg button").forEach(b=>{b.textContent=t({pasta:"lPasta",sauce:"lSauce",dish:"lDish",pop:"lPop"}[b.dataset.layer]);b.setAttribute("aria-pressed",b.dataset.layer===layer)});
  $("atlasView").className="atlas L-"+layer; $("atlasView").hidden = view!=="atlas";
  $("layerQ").textContent=t({pasta:"qPasta",sauce:"qSauce",dish:"qDish",pop:"qPop"}[layer]);
  $("atlasKey").textContent=t(layer==="pop"?"keyPop":"keyShade");
  if(layer==="pop") return renderAtlasPop();
  const byReg={}; const add=(r,x)=>(byReg[r]=byReg[r]||[]).push(x);
  let pins=[];
  if(layer==="dish"){
    const ds=visDishes(); ds.forEach(d=>add(d.reg,d));
    const byCity={}; ds.forEach(d=>byCity[d.city]=(byCity[d.city]||0)+1);
    pins=Object.entries(byCity).map(([city,count])=>({city,count,kind:"dishfill",data:1}));
  } else {
    const items = layer==="pasta"?visP():visS();
    items.forEach(it=>it.reg.forEach(r=>add(r,it)));
    pins=items.filter(x=>x.city).map(x=>({city:x.city,kind:"pt"}));
  }
  const cls={}; for(const r in byReg) cls[r]="h"+Math.min(3,Math.ceil(byReg[r].length/ (layer==="dish"?2:1.5)));
  if(atlasPick) cls[atlasPick]=(cls[atlasPick]||"")+" pick";
  $("atlasMap").innerHTML=mapSVG({cls,pins});
  renderBubble();
  const regs = atlasPick ? [atlasPick] : REG_ORDER.filter(r=>byReg[r]);
  const tag = x => layer==="dish"
    ? `<button class="tag d" data-open="dishcell" data-id="${x.k}">${esc(L(x.n))}<small>${esc(x.city)}</small></button>`
    : `<button class="tag ${layer==="pasta"?"p":"s"}" data-open="${layer}" data-id="${x.id}">${esc(x.n)}</button>`;
  $("regionList").innerHTML = regs.map(r=>{
    const xs=byReg[r]||[];
    return `<div class="region-card${atlasPick===r?" pick":""}"><h4 data-reg="${r}">${esc(regName(r))}<small>${xs.length} ${esc(t("items"))}</small></h4><div class="tags">${xs.length?xs.map(tag).join(""):`<span class="fine">${esc(t("none"))}</span>`}</div></div>`;
  }).join("") || `<p class="fine">${esc(t("empty"))}</p>`;
}

/* ================= WIRING ================= */
let cardKind="p";
function renderCards(){
  document.querySelectorAll("#cardSeg button").forEach(b=>{b.textContent=t(b.dataset.cards==="p"?"lPasta":"lSauce");b.setAttribute("aria-pressed",b.dataset.cards===cardKind)});
  const items = cardKind==="p" ? visP("scope") : visS("scope");
  $("cardCount").textContent=`${items.length} ${t("items")}`;
  $("cards").innerHTML=items.map(x=>{ const m=med(cardKind,x.id);
    const sub = cardKind==="p" ? `${L(DOUGH[x.dough].l)} · ${L(FRESH[x.fresh?"fresh":"dried"])}` : x.ing.slice(0,4).map(i=>L(ING[i][0])).join(", ");
    return `<button class="card" data-open="${cardKind==="p"?"pasta":"sauce"}" data-id="${x.id}"><span class="ph">${m&&m.img?`<img src="${esc(m.img)}" alt="" loading="lazy">`:esc(x.n[0])}</span><span class="bd"><b>${esc(x.n)}</b><span class="rg">${esc(x.reg.map(regName).join(" · "))}</span><small>${esc(sub)}</small></span></button>`; }).join("");
}
function renderCredits(){
  const rows=[...Object.entries(MEDIA.pasta).map(([id,m])=>[pById(id),m]),...Object.entries(MEDIA.cond).map(([id,m])=>[sById(id),m])].filter(([x,m])=>x&&m&&m.img);
  const open=$("credits").open;
  $("credits").innerHTML=`<summary>${esc(t("credits"))} <small class="fine" style="font-family:var(--mono);font-size:12px">(${rows.length})</small></summary><p class="fine" style="margin-top:8px">${esc(t("creditsNote"))}</p><ol>${rows.map(([x,m])=>`<li>${esc(x.n)}: ${esc(m.author||"")}, <a href="${esc(m.commons)}" target="_blank" rel="noopener">${esc(m.license||"")}</a></li>`).join("")}</ol>`;
  $("credits").open=open;
}
function renderAll(){ renderText(); renderBiblio(); renderCredits(); renderCards(); $("cardsView").hidden = view!=="cards"; renderFilters(); renderMatrix(); renderPanel(); renderAtlas(); $("matrixView").hidden = view!=="matrix"; $("whyView").hidden = view!=="why"; document.querySelector(".layout").classList.toggle("wide", view!=="matrix"); }
function refreshData(){ renderFilters(); renderMatrix(); renderPanel(); renderAtlas(); renderCards(); }
const small = () => window.innerWidth<=1100;
function openPanel(){ if(!small()) return; $("panel").classList.add("open"); $("scrim").hidden=false; }
function closePanel(){ $("panel").classList.remove("open"); $("scrim").hidden=true; }
function select(next, open=true){ sel=next; markSel(); renderPanel(); $("panel").scrollTop=0; if(open) openPanel(); writeURL(true); }

document.addEventListener("click",e=>{
  if(e.target.closest("a")) return;
  if(e.target.closest("[data-closebubble]")){ bubble=null; return renderBubble(); }
  if(e.target.closest("[data-closecell]")) return showCellBubble(null);
  if(e.target.closest(".cellbubble")){ showCellBubble(null); return openPanel(); }
  if(e.target.closest("[data-closepanel]")||e.target.id==="scrim") return closePanel();
  if(!e.target.closest(".cell")) document.querySelector(".cellbubble")?.remove();
  const bub=e.target.closest(".bubble"); if(bub) return openRegion(bub.dataset.bubble);
  if(bubble && !e.target.closest("#atlasMap [data-reg], #atlasMap [data-city]")){ bubble=null; renderBubble(); }
  const b=e.target.closest("button,[data-reg],[data-city]"); if(!b) return;
  if(b.dataset.lang){ lang=b.dataset.lang; store.set("pasta-lang",lang); return renderAll(); }
  if(b.dataset.view){ view=b.dataset.view; renderAll(); return writeURL(true); }
  if(b.dataset.cards){ cardKind=b.dataset.cards; return renderCards(); }
  if(b.dataset.scope){ scope=b.dataset.scope; store.set("pasta-scope",scope); renderText(); return refreshData(); }
  if(b.dataset.layer){ layer=b.dataset.layer; atlasPick=null; bubble=null; return renderAtlas(); }
  if(b.dataset.f){
    const g=b.dataset.f,k=b.dataset.k;
    if(g==="fresh") F.fresh=k; else { F[g].has(k)?F[g].delete(k):F[g].add(k); }
    if(g==="diet") store.set("pasta-diet",[...F.diet]);
    return refreshData();
  }
  if(b.dataset.clear){ if(b.dataset.clear==="diet"){F.diet.clear();store.set("pasta-diet",[])} else {F.dough.clear();F.fam.clear();F.area.clear();F.fresh="all"} return refreshData(); }
  if(b.classList.contains("cell")){ select({type:"cell",p:b.dataset.p,s:b.dataset.s},false); return showCellBubble(b); }
  if(b.classList.contains("rowh")) return select({type:"pasta",p:b.dataset.p});
  if(b.classList.contains("colh")) return select({type:"sauce",s:b.dataset.s});
  const o=b.dataset.open, id=b.dataset.id;
  if(o==="cell-p") return select({type:"cell",p:id,s:sel.s||S[0].id});
  if(o==="cell-s") return select({type:"cell",p:sel.p||P[0].id,s:id});
  if(o==="pasta") return select({type:"pasta",p:id});
  if(o==="sauce") return select({type:"sauce",s:id});
  if(o==="dishcell"){ const [p,s]=id.split("|"); return select({type:"cell",p,s}); }
  if(b.closest("#atlasView")){
    let r=b.dataset.reg;
    if(b.dataset.city){ const d=visDishes().find(x=>x.city===b.dataset.city)||POP.cities.find(x=>x.city===b.dataset.city); r=d?d.reg:null; }
    if(!r) return;
    if(!b.closest("#atlasMap")) return openRegion(r);          // heading in the region list
    if(bubble && bubble.r===r) return openRegion(r);          // second click on the same region
    const box=$("atlasMap").getBoundingClientRect();
    bubble={r,x:e.clientX-box.left,y:e.clientY-box.top}; atlasPick=r; return renderAtlas();
  }
});
document.addEventListener("keydown",e=>{
  if(e.key==="Escape"){ if(bubble){ bubble=null; renderBubble(); } showCellBubble(null); closePanel(); }
  if((e.key==="Enter"||e.key===" ")&&e.target.classList?.contains("bubble")){ e.preventDefault(); openRegion(e.target.dataset.bubble); }
});
$("filters").addEventListener("toggle",()=>{ $("ftoggle").textContent=t($("filters").open?"hideF":"showF"); });
document.addEventListener("change",e=>{
  if(e.target.id==="gp"){ groupP=e.target.value; store.set("pasta-gp",groupP); renderMatrix(); }
  if(e.target.id==="popT"){ showPop=e.target.checked; store.set("pasta-pop",showPop); renderText(); renderMatrix(); }
  if(e.target.id==="gs"){ groupS=e.target.value; store.set("pasta-gs",groupS); renderMatrix(); }
});
$("mx").addEventListener("mouseover",e=>{
  const td=e.target.closest("td[data-col]"); const mx=$("mx");
  mx.querySelectorAll("tr.hl,th.hl").forEach(x=>x.classList.remove("hl"));
  if(!td) return; td.parentElement.classList.add("hl");
  mx.querySelector(`thead th[data-col="${td.dataset.col}"]`)?.classList.add("hl");
});
$("mx").addEventListener("mouseleave",()=>$("mx").querySelectorAll("tr.hl,th.hl").forEach(x=>x.classList.remove("hl")));
/* ================= URL STATE: every screen is a link (LLM.md section 2c) ================= */
function stateToHash(){
  const q=new URLSearchParams();
  q.set("view",view); q.set("lang",lang);
  if(scope!=="pop") q.set("scope",scope);
  if(sel.type==="cell") q.set("sel",`${sel.p}.${sel.s}`); else if(sel.type==="pasta") q.set("p",sel.p);
  else if(sel.type==="sauce") q.set("s",sel.s); else if(sel.type==="region") q.set("r",sel.r);
  if(view==="atlas") q.set("layer",layer);
  if(view==="cards") q.set("cards",cardKind);
  for(const k of ["dough","fam","area","diet"]) if(F[k].size) q.set(k,[...F[k]].join(","));
  if(F.fresh!=="all") q.set("fresh",F.fresh);
  return "#"+q.toString();
}
function writeURL(push){ const h=stateToHash(); if(h===location.hash) return; history[push?"pushState":"replaceState"](null,"",h); }
function readURL(){
  const q=new URLSearchParams(location.hash.slice(1)); if(![...q.keys()].length) return;
  const one=(k,ok,set)=>{ const v=q.get(k); if(v!==null&&ok(v)) set(v); };
  one("view",v=>["matrix","atlas","cards","why"].includes(v),v=>view=v);
  one("lang",v=>v in LI,v=>lang=v);
  one("scope",v=>["pop","core","all"].includes(v),v=>scope=v);
  one("layer",v=>["pasta","sauce","dish","pop"].includes(v),v=>layer=v);
  one("cards",v=>["p","s"].includes(v),v=>cardKind=v);
  one("fresh",v=>["all","fresh","dried"].includes(v),v=>F.fresh=v);
  for(const k of ["dough","fam","area","diet"]) one(k,()=>true,v=>{ F[k]=new Set(v.split(",").filter(Boolean)); });
  one("sel",v=>{const [a,b]=v.split(".");return pById(a)&&sById(b)},v=>{const [a,b]=v.split(".");sel={type:"cell",p:a,s:b}});
  one("p",v=>pById(v),v=>sel={type:"pasta",p:v});
  one("s",v=>sById(v),v=>sel={type:"sauce",s:v});
  one("r",v=>v in REG,v=>sel={type:"region",r:v});
}
window.addEventListener("popstate",()=>{ readURL(); renderAll(); });
/* refinements replace the entry; moves (view, selection) push one, see select() and the view switch */
document.addEventListener("click",()=>setTimeout(()=>writeURL(false)));
document.addEventListener("change",()=>setTimeout(()=>writeURL(false)));

/* ================= PANEL WIDTH: the reader can drag its edge, and it is remembered ================= */
function initGrip(){
  const grip=$("grip"), panel=$("panel");
  const set=w=>{ w=Math.max(300,Math.min(720,w)); panel.style.flexBasis=w+"px"; return w; };
  const saved=store.get("pasta-panelw",null); if(saved) set(saved);
  grip.addEventListener("pointerdown",e=>{
    e.preventDefault(); grip.setPointerCapture(e.pointerId);
    const x0=e.clientX, w0=panel.getBoundingClientRect().width;
    const move=ev=>set(w0-(ev.clientX-x0));
    const up=()=>{ grip.removeEventListener("pointermove",move); grip.removeEventListener("pointerup",up); store.set("pasta-panelw",panel.getBoundingClientRect().width); };
    grip.addEventListener("pointermove",move); grip.addEventListener("pointerup",up);
  });
}

/* ================= BOOT ================= */
async function boot(){
  const get = f => window.__PASTATLAS_DATA ? Promise.resolve(window.__PASTATLAS_DATA[f])
    : fetch(`pastatlas/data/${f}?v=${DATA_V}`).then(r=>{ if(!r.ok) throw new Error(`${f}: ${r.status}`); return r.json(); });
  const [base, i18n, pop, regional, sources, media, paths] = await Promise.all(
    ["base.json","i18n.json","popularity.json","regional.json","sources.json","media.json","italy_regions.json"].map(get));
  ({REG, REG_ORDER, AREA, CITY, DOUGH, FRESH, SHAPE, SHAPE_G, FAM, ING, SFAM} = base);
  P=base.pasta; S=base.sauces; R=base.ratings; DISH=base.dishes; NOTE=base.notes; RULES=base.rules;
  T=i18n; POP=pop; SRC=sources; PATHS=paths;
  MEDIA=Object.assign({pasta:{},cond:{},dish:{}}, media);
  for(const kind of ["pasta","cond"]) for(const m of Object.values(MEDIA[kind])) if(m&&m.img&&!m.img.startsWith("pastatlas/")) m.img="pastatlas/"+m.img;
  mergeRegional(regional);
  POP_SET=computePopSet();
  readURL();
  $("build").textContent=`v${DATA_V}${BUILD_AT?` · ${BUILD_AT}`:""}`;
  document.querySelector(".brand").addEventListener("click",e=>{ e.preventDefault(); history.replaceState(null,"",location.pathname); location.reload(); });
  initGrip();
  renderAll();
  writeURL(false);
}
boot().catch(err=>{ document.getElementById("mx").innerHTML=`<tbody><tr><td class="empty">Data failed to load: ${String(err.message||err)}</td></tr></tbody>`; });
